### ISSUE TITLE
Enlarge image - content disappears

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#100]
1.Take an Image with Snipping Tool 
2.Copy&Paste to CollaBoard
3.Enlarge image
4.When enlarging the image there is a sort of zoom in. Then not all the content is visible anymore
5.When brining the image back to original size all the content is visible again. 

05.02.2017 15:50
HP Desktop PC + Surface Pro 4
Any project 
Version 1.3.6.0

Screen-Shot Taken with Snipping Tool
![image](https://cloud.githubusercontent.com/assets/19570958/22627050/ef6ba070-ebba-11e6-8644-3859d395b90e.png)

Screen-Shot after zooming in
![image](https://cloud.githubusercontent.com/assets/19570958/22627070/313698ca-ebbb-11e6-8fcc-fc7e16d76e3c.png)

**Comment by corradocavalli** [comment]
I refactored the entire sizing engine to that it meets aspect ratio better. Please try again with next release and make a deep szing testing with various picture & pdf sizes since change impacts the entire tile engine. If ok, please close the issue.
/cc @agorog @teguria

**Comment by gsantopaolo** [comment]
yes please use the sideload because we desperately need readable traces

**Comment by agorog** [comment]
Ok, I need the link for the download, have not received until now.

**Comment by agorog** [comment]
I don't know how to proceed. Test with production 1.3.6.0 it is not ok. To sideload I dont know where to get the version to sideload.

**Comment by corradocavalli** [comment]
It should be available in yesterday's release.

On 7 Feb 2017, at 15:39, agorog <notifications@github.com<mailto:notifications@github.com>> wrote:


I don't know how to proceed. Test with production 1.3.6.0 it is not ok. To sideload I dont know where to get the version to sideload.

**Comment by agorog** [comment]
1.3.10.0 for me it is ok

**Comment by mtg1986** [comment]
1.3.10.0 for me ok as well.
