### ISSUE TITLE
Cant ink first added sticky note

### ISSUE THREAD

**Issue by agorog** [IBVSoftware/CollaBoard-Feedback#103]
Project Code: 3708
Project Key: fnb4z
ibv-collaboard:open?code=3708&key=fnb4z
Version: 1.3.9.0
Date: 08.02.2017 20:15

Added 4 sticky note. Try to ink after adding all of them. Cant ink first sticky. 2-4 ok. Close project, load again same situation cant ink first sticky.

**Comment by agorog** [comment]
![grafik](https://cloud.githubusercontent.com/assets/19590642/22753306/f9019b02-ee3b-11e6-800d-64d60eedd602.png)

**Comment by corradocavalli** [comment]
Please provide a reproducible sequence for the mentioned issue. I have did that at least 100 times today... :-)

On 8 Feb 2017, at 20:22, agorog <notifications@github.com<mailto:notifications@github.com>> wrote:


[grafik]<https://cloud.githubusercontent.com/assets/19590642/22753306/f9019b02-ee3b-11e6-800d-64d60eedd602.png>

**Comment by agorog** [comment]
I will try. What happened in the meantime is that all tiles disappeared in this project. When testing what happens if you loose network connection and restoring the connection I all tiles where without ink and when moving around just created a new tile, very strange. After closing and loading the project againg the project was empty. 
![grafik](https://cloud.githubusercontent.com/assets/19590642/22754529/1f65b234-ee40-11e6-8331-75cde91af713.png)

**Comment by agorog** [comment]
Here is the reproduction: Add 2 sticky. Overlap them. Make second on top of first. Click on first that this is top. Try to ink first sticky. Not possible. Close project, load it again. You still cant ink first sticky. 
I think there is a problem with the correct addressing/index of the tiles as soon as you move them over each other and then try to work with them. It can result in lot of different problems, loosing ink, loosing tiles and so on. I think this is the same problem as #59

**Comment by agorog** [comment]
Try project 3711 / qp2i9  You cannot ink sticky 1

**Comment by corradocavalli** [comment]
Spot the cause: it is a regression introduced by the fix for issue #58 also identified the reason but need to discuss with @gsantopaolo because it is far than obvious.

**Comment by corradocavalli** [comment]
We're trying to find a solution for that, it is a side effect of the famous 128 instances workaround we had to implement.

On 8 Feb 2017, at 21:12, agorog <notifications@github.com<mailto:notifications@github.com>> wrote:


Try project 3711 / qp2i9 You cannot ink sticky 1

**Comment by corradocavalli** [comment]
We just found (another) workaround that should fix this issue, please try again when the new version will be available.

**Comment by agorog** [comment]
ok with 1.3.10.0
