### ISSUE TITLE
CollaBoard hangs, after not syncing one tile on Surface

### ISSUE THREAD

**Issue by agorog** [IBVSoftware/CollaBoard-Feedback#104]
Project Code: 3808
Project Key: ewo29
ibv-collaboard:open?code=3808&key=ewo29
Version 1.3.10.0
Date 10.02.2017 15:10 : 15:30 

Project open on 3 devices, Hub, NB, Surfaca.
Added 3 sticky, everything ok on all devices
Ink 1 on NB, ink 2 on Surface everthing ok on all device
Ink3 on Hub, everthing ok on Hub and on Nb.
On Surface Ink is not showed, wait a few minutes, then try to move a sticky around on Surface, not possible, seems that CollaBoard hangs on this devices, cant do anything in CollaBoard, can minimize, maximize, but not close the app. On the other two devices everything ok. Have to kill CollaBoard on Surface with Task Manager, in Task Manager CollaBoard i shown with 0.2 MB Memory. After canceling in Task Manager, CollaBoard is active again, but the Welcome screen is shown unsharp. Cancel again. Start again. Load project all tiles are shown correctly.

**Comment by agorog** [comment]
Tried to reproduce. Different sequence but similar problem. 
3810 / ufv1p 10.02. 15:59. 
Inking the 3 stickys on the different devices. After inking sticky 2 (yellow background) on the hub, ink is shown on hub and NB, but not on NB. NB shows sticky 2 empty, ink then sticky 2 on NB, save, overwrites and the original ink is lost.

**Comment by agorog** [comment]
Project 3808: sticky with green background no ink shown on Surface, Surface hangs
![grafik](https://cloud.githubusercontent.com/assets/19590642/22831365/6d315192-efaa-11e6-8ba7-d75fcc612de9.png)

**Comment by agorog** [comment]
Project 3810: Sticky with yello background is shown on NB without ink. Then ink on the PC the ink which is shown on the other 2 devices is erased after saving the ink on NB.
![grafik](https://cloud.githubusercontent.com/assets/19590642/22832397/2b6adfd6-efae-11e6-8cfd-da42d20c9f61.png)
****

**Comment by corradocavalli** [comment]
Does the same happen with 2 devices? (tried but can't reproduce it) if so, do you have a repro sequence?

**Comment by agorog** [comment]
I only had it with 3 device. We have to do some testing on Monday with more devices and see what happens

**Comment by agorog** [comment]
1.3.12.0 fixed
