### ISSUE TITLE
Welcome Message stays on Canvas 

### ISSUE THREAD

**Issue by agorog** [IBVSoftware/CollaBoard-Feedback#106]
Project Code: 3814
Project Key: 4wl2a
ibv-collaboard:open?code=3814&key=4wl2a
Version: 1.3.10.0 
Date 10.02.2017 16:51 

Create new project (radial menu) 
Key is shown, Welcome message still displayed
Add Sticky, Welcome message still displayed 

![grafik](https://cloud.githubusercontent.com/assets/19590642/22833225/68ca2d20-efb1-11e6-9a76-8d49dd6d865a.png)

**Comment by agorog** [comment]
Close Project / Load Project: All ok

**Comment by corradocavalli** [comment]
Good catch. Fixed.
