### ISSUE TITLE
Error after leaving project open 

### ISSUE THREAD

**Issue by agorog** [IBVSoftware/CollaBoard-Feedback#108]
Project Code: 3872
Project Key: 47rjm
ibv-collaboard:open?code=3872&key=47rjm
Version 1.3.10.0 
Date 13.02.2017 Left device with open projectg at 09:30 , come back at 11:10 
All Devices 

When having project open and then leaving device for a longer time running unattended, we get an error (see screenshot). Clicking ok, closes project, but CollaBoard stays active.
Had this bug in earlier version is now back again. 

![grafik](https://cloud.githubusercontent.com/assets/19590642/22879239/56da1390-f1dd-11e6-9188-06efee94759f.png)
****

**Comment by corradocavalli** [comment]
After closing the project, can you continue working even without restarting CollaBoard?

**Comment by agorog** [comment]
Yes, just load project again, everything ok.

**Comment by corradocavalli** [comment]
Can you give us more info about that? That is a general application exception and doesn't give us enough information to start investigating.

**Comment by agorog** [comment]
I checked again, sometimes it happens, sometimes not. How can we test, so you get the information you need, I can sideload on my Surfaceif necessary to get the debug information ?

**Comment by corradocavalli** [comment]
Yes, that would help. Is there a way to simulate the error? Is someone using the same project on other machines? does machine goes into suspension or whatever?

**Comment by agorog** [comment]
Behaviouer changed with 1.3.12.0 I close this issue and open new one.
