### ISSUE TITLE
Moving out Sticky from Grid library ink is not shown in Sticky

### ISSUE THREAD

**Issue by agorog** [IBVSoftware/CollaBoard-Feedback#109]
Project Code: 670
Project Key: kelpr
ibv-collaboard:open?code=670&key=kelpr
Version 1.3.11.0
Date 13.02.2017 19:15 

Library Grid named test has 2 sticky notes inked with 3 and 4. Ink is shown correctly in library grid. 

![grafik](https://cloud.githubusercontent.com/assets/19590642/22896677/4a2ec8ea-f221-11e6-93b4-7a91b68441ce.png)

Moving out the sticky notes show them without ink in the canvas: 

![grafik](https://cloud.githubusercontent.com/assets/19590642/22896709/64e38a72-f221-11e6-8948-087ffd467daf.png)
****

Editing the sticky note shows the ink correctly, moving the sticky back without editing shows the sticky in the grid library without ink. Moving the sticky out again and edit it ink will be shown correctly.

**Comment by corradocavalli** [comment]
So moving tiles in & out of the library makes the ink temporarily vanish until you enter edit mode on it? Is this correct?

On 13 Feb 2017, at 19:21, agorog <notifications@github.com<mailto:notifications@github.com>> wrote:


Project Code: 670
Project Key: kelpr
ibv-collaboard:open?code=670&key=kelpr
Version 1.3.11.0
Date 13.02.2017 19:15

Library Grid named test has 2 sticky notes inked with 3 and 4. Ink is shown correctly in library grid.

[grafik]<https://cloud.githubusercontent.com/assets/19590642/22896677/4a2ec8ea-f221-11e6-93b4-7a91b68441ce.png>

Moving out the sticky notes show them without ink in the canvas:

[grafik]<https://cloud.githubusercontent.com/assets/19590642/22896709/64e38a72-f221-11e6-8948-087ffd467daf.png>

________________________________

Editing the sticky note shows the ink correctly, moving the sticky back without editing shows the sticky in the grid library without ink. Moving the sticky out again and edit it ink will be shown correctly.

**Comment by agorog** [comment]
yes exactly

**Comment by corradocavalli** [comment]
Problem fixed, please test it with new release and close if ok.

**Comment by agorog** [comment]
1.3.12.0 fixed
