### ISSUE TITLE
After reloading project on 3 devices, only one device ok

### ISSUE THREAD

**Issue by agorog** [IBVSoftware/CollaBoard-Feedback#110]
Project Code: 3969
Project Key: ybunf
ibv-collaboard:open?code=3969&key=ybunf
Version 1.3.12.0 
Date 20170214 14:35 (but happened probably before) 

Project open on 3 devices. Leave office for about half an hour. When come back and activate screen, CollaBoard on all 3 devices says "Servers ask to reload project" click ok, reloads project. On the hub and on Surface only gridlibrary and library is shown. Own Notebook PDF and Sticky note on Canvas is displayed.

**Comment by agorog** [comment]
![grafik](https://cloud.githubusercontent.com/assets/19590642/22931337/89f33922-f2c4-11e6-8282-01b623b70d2a.png)

**Comment by corradocavalli** [comment]
What if you reload the project the hub?

**Comment by agorog** [comment]
1.3.15.0 fixed
