### ISSUE TITLE
Reload Project no message "we are making things ready for you..."

### ISSUE THREAD

**Issue by agorog** [IBVSoftware/CollaBoard-Feedback#112]
1.3.12.0 
When the server brings the message the it has to reload the project after click ok, the user has no information if something happens or not.  The same message as when loading a project should be displayed.

**Comment by corradocavalli** [comment]
That's actual behavior when you reload the project, think the bug is that request might appaear when no project is loaded. Added a fix, please check with the next release and verify that you get the message only when a project is loaded.

**Comment by agorog** [comment]
1.3.15.0 fixed
