### ISSUE TITLE
Background of Audio records tile not saved or not loaded 

### ISSUE THREAD

**Issue by agorog** [IBVSoftware/CollaBoard-Feedback#113]
Project Code: 3995
Project Key: ho0ed
ibv-collaboard:open?code=3995&key=ho0ed
Version: 1.3.12.0 
Date: 14.02:2017 19:00 

Project has only one tile a recorded adio. Ink is all ok. 
Background is grey. Change background, will correctly shown on all devices where project is actually open. 
Close on one device. Load again, tile will be displayed with grey background.

**Comment by corradocavalli** [comment]
Fixed, please test it with next release.

**Comment by agorog** [comment]
1.3.13.0 fixed
