### ISSUE TITLE
Device changes tile sequence when going to sleep mode and then activating/reloading

### ISSUE THREAD

**Issue by agorog** [IBVSoftware/CollaBoard-Feedback#114]
Project Code: 3808
Project Key: ewo29
ibv-collaboard:open?code=3808&key=ewo29
Version: 1.3.12.0 
Date 14.02.2017 19:20 

Project is open on 3 devices, 10 sticky notes stacked. Leave room and come back some minutes later. Hub shows start menu. Activate CollaBoard, message "Server has to reload project" and then stickys are displayed in different order. Audio recording is shown without inking. Close/Load project on Hub same result. Other devices ok, close/load also ok. Dont know if this is bug specific as the other stayed active.

**Comment by agorog** [comment]
![grafik](https://cloud.githubusercontent.com/assets/19590642/22943558/3e6cdaf6-f2ee-11e6-9a86-5e0337f0d730.png)

**Comment by agorog** [comment]
It is not hub specific. It happened now also on the Surface after it was inactive for a certain time. CB says the its not you, it us and has to reload project, then in the background you already see the misarranged tiles and then after loading it stays like this. On the device which was all the time active I can close and reload the project and everything is displayed correctly.

**Comment by corradocavalli** [comment]
Tried several times but got the effect only one time, I've anyway refactored suspend/resume procedure so that reload project shouldn't be no longer necessary unless the realtime connection wit the server drops.
Let us know if you find a reproducible sequence.

**Comment by agorog** [comment]
1.3.13.0  still same on Hub and on Surface

**Comment by agorog** [comment]
1.3.14.0 still same

**Comment by agorog** [comment]
1.3.15.0  Project 4120 v3x6q 
Opening still same as with 1.3.14.0 

Also found: Project has 10 Sticky notes, 2x5 stacked. Open on 3 devices. If I ink on one device, leave 2 stickys in edit mode and move them to the stack again, then sticky on the other devices will be shown not in the correct stack sequence.

**Comment by corradocavalli** [comment]
We have added an internal synchronization mechanism to fix the stacking issue, though not perfect (best solution would heavily impact on real-time communication performances) it reduce the stacking issue to rare cases. Please test it with v 17.

**Comment by agorog** [comment]
Could reproduce with 1.3.30.0  Project 1647 / c8iuy
Open project on two devices. One device go to sleep mode, on other device we change stack for sticky notes and grid libs. The 4 sticky notes and the 3 grid libraries are not shown in the stack after device coming from sleep mode and then sychronizing the project. After closing / opening the project on this device stacks are still shown different then in the other project, where the tiles have been stacked.

**Comment by agorog** [comment]
Teste with 1.3.41.0 Project 1647 / c8iuy still same problem

**Comment by agorog** [comment]
We have new issues describing it better
