### ISSUE TITLE
Settings on Hub

### ISSUE THREAD

**Issue by agorog** [IBVSoftware/CollaBoard-Feedback#117]
I prefer to work with With Background instead of Black. This is in Settings and on NB, Surface if I update to a new version, this settings will be kept. On the hub however the settings are not kept, i.e. Background is black after updatin Hub to a new version of CollaBoard (without shut down Hub or ending actual session).

**Comment by corradocavalli** [comment]
Is just background color info that get lost or all the entire settings (e.g Language, Voice commands...)

**Comment by agorog** [comment]
I havent checked, I think radial menu also. I will check with next update

**Comment by agorog** [comment]
V1.3.15.0: All settings

**Comment by corradocavalli** [comment]
So this happens on Surface Hub only right?

**Comment by agorog** [comment]
This is only on Hub and I checked it with the other apps. As long as you do not login in an app, you loose your settings (Edge, Word, Excel), when you reset or restart the hub and probably also you when you update from the store.  When you login you have your settings (Bullclip, Drawboard, Mural, Stormboard)
We close this issue and will discuss what to do when we talk about login on the hub.
