### ISSUE TITLE
Info Windows not update when creating project

### ISSUE THREAD

**Issue by agorog** [IBVSoftware/CollaBoard-Feedback#118]
Littel bug:
Version 4.1.15.0 
Date 17.02.2017 09:08 

Start CollaBoard, Click on Info. Version and Registration is displayed.
Now create new project. Will be created, Info Window moves, but stays same, i.e. Project ID/Key are not displayed. 
Close Info Window, Open it again, everything ok.

**Comment by corradocavalli** [comment]
fixed in  1.3.16
