### ISSUE TITLE
Voice Commands stopped working

### ISSUE THREAD

**Issue by teguria** [IBVSoftware/CollaBoard-Feedback#119]
v 1.3.16.0
HP Spectre x360
Project Code: 3205
Project Key: a5qxr

I started to use voice commands and everything worked fine. At some point (after 2 minutes almost) the app wasn't recognize anything anymore. Maybe it's my audio, need to test it on another device

**Comment by teguria** [comment]
Switching from the web browser and back to app resumed the audio

**Comment by corradocavalli** [comment]
can we close this then?

**Comment by teguria** [comment]
Yes, thanks
