### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by tamarawasser** [IBVSoftware/CollaBoard-Feedback#121]
It would be cool, when I'm working on a project and my canvas is full with tiles, when I could use a voice command to call a tile into my field of view of the canvas. For example, the grid library is in the right corner down of the canvas, but I'm working in the left corner up. Then I can use the voice command "Collaboard, search grid library" (or something else) and the grid library appears in my field of view on the canvas. If I have more than one grid library they appear all side by side.

**Comment by gsantopaolo** [comment]
@tamarawasser  please add to the CB FDS and close
