### ISSUE TITLE
Record Audio disturb Demo version

### ISSUE THREAD

**Issue by tamarawasser** [IBVSoftware/CollaBoard-Feedback#122]
Surface Pro
24th of February 
Demo Version

09:02
Record audio runs
Info appear that I’m in the demo version and that I have to wait for a few seconds
I click on close
CollaBoard runs for a few minutes

09:07
Record audio runs
Info appear that I’m in the demo version and that I have to wait for a few seconds (but this time the information is not readable (see picture)) 
![demo version](https://cloud.githubusercontent.com/assets/25382402/23296063/b8d2cb70-fa73-11e6-89bd-cede6724a0a0.PNG)
I close CollaBoard by clicking on the cross in the corner right up

Open CollaBoard again
09:19 no audio runs in the background
Info appear that I’m in the demo version and that I have to wait for a few seconds
I click on close

09:22
No audio  in the background
Info appear that I’m in the demo version and that I have to wait for a few seconds
I click on close

09:25
Audio runs in the background
I can’t read the information again, it looks like in the pictures and I need to close CollaBoard by clicking on the  cross in the corner right up

**Comment by corradocavalli** [comment]
Issue has been fixed in the next release (v17) please verify it when available and close this issue if ok.
