### ISSUE TITLE
[Minor Issue] Radial Menu on Text

### ISSUE THREAD

**Issue by teguria** [IBVSoftware/CollaBoard-Feedback#124]
Hp Spectre x360
v. 1.3.16.0

When you pass through with the Radial Menu onto some text, the lines between the menus are dashed lines (see screenshots)
![screen](https://cloud.githubusercontent.com/assets/19929395/23342917/0477f3c0-fc63-11e6-921e-1cffa2c3b7d4.jpg)
![screen2](https://cloud.githubusercontent.com/assets/19929395/23342916/0476dd3c-fc63-11e6-9ed1-e7515a2b22f6.jpg)

**Comment by gsantopaolo** [comment]
I've also noticed it

**Comment by gsantopaolo** [comment]
by design .. .sorry :)
