### ISSUE TITLE
PDF shows ink of sticky after moving out of grid lib

### ISSUE THREAD

**Issue by agorog** [IBVSoftware/CollaBoard-Feedback#127]
Project Code: 1646
Project Key: 8c2xc
Project description: Test 25 pdf ink
ibv-collaboard:open?code=1646&key=8c2xc
Version: 1.3.26.0 
Date: 05.03.2017 09:30 

Single User: 
Open project
Move pdf to grid library 
Move pdf back to canvas 
Move sticky not to grid libary 
Move sticky not back to canvas
The ink of the sticky note is shown on the pdf. 

Multi User: 
Open now project on second device 
pdf is shown without ink

**Comment by corradocavalli** [comment]
Found an odd ink duplicating issue that might be related to this and fixed it, need to be tested deeply with all tile configurations to discover any possible side effect.

**Comment by agorog** [comment]
Fixed with 1.3.27.0
