### ISSUE TITLE
Leave project open for hours then come back, menu and key are not displayed 

### ISSUE THREAD

**Issue by agorog** [IBVSoftware/CollaBoard-Feedback#130]
Project Code: 1648
Project Key: naynj
Project description: Ink need 2 clicks/taps ?
ibv-collaboard:open?code=1648&key=naynj
Version 1.3.26.0 
Date: 05.03.2017 
Device: Notebook 

Let project open for some hours, then come back. CollaBoard reloads project, takes a while then project is displayed correctly. 
Change background on sticky, ok. 
Click Info. Code and Key are not displayed, 
Radial menu shows options before loading a project, i.e. can not add tile. 
Click on Load project brings message, do you really want close project, do that reload project then everything is ok. 

Info without Code/Key:
![grafik](https://cloud.githubusercontent.com/assets/19590642/23588422/acaef7b4-01bd-11e7-8d88-024bc5e1fe17.png)
****

**Comment by agorog** [comment]
The background of the sticky was changed correctly and when loading project it show the correct background, i.e. changes to project were possible during the time were the project info was not correct and no new tiles could be added.

**Comment by corradocavalli** [comment]
This should be fixed on recent build. even the one you have, can you try it?

**Comment by agorog** [comment]
Tested again with 1.3.41.0, is fixed.
