### ISSUE TITLE
Grid Library name not locked, when edited

### ISSUE THREAD

**Issue by agorog** [IBVSoftware/CollaBoard-Feedback#131]
Version 1.3.26.0 

Open project on 2 devices
Add grid library 
Edit title on first device, Title abc
Edit title on second device, Title xyz 
Click ok on second devbice, Title xyz is stored an will be displayed on other device. 
Click on on first device, xyz will be overwritten with abc

**Comment by corradocavalli** [comment]
Tile is now locked also in these cases: Tile deleting, Background color panel selection, Library header editing and Grid Library size selection. Available from build 27.

**Comment by agorog** [comment]
Fixed with 1.3.30.0
