### ISSUE TITLE
Gird library title ink: CollaBoard hangs

### ISSUE THREAD

**Issue by agorog** [IBVSoftware/CollaBoard-Feedback#132]
Project Code: 1648
Project Key: naynj
Project description: Ink need 2 clicks/taps ?
ibv-collaboard:open?code=1648&key=naynj
Version 1.3.26.0 
Date 5.3.2017 16:10 
Devices: Hub, Surface Pro 4

Edit and existing Grid library name, remove the text,  Ink something in textbox. CollaBoard hangs. Have to end with X. 
If CollaBoard does not hang the first time, do it once more: save the title, edit it, remove text, ink it. Before ink is converted to text, CollaBoard hangs.

**Comment by corradocavalli** [comment]
tried several times but can't reproduce it on the same project, was it happening systematically?

**Comment by agorog** [comment]
fixed with 1.3.27.0
