### ISSUE TITLE
Cant stack 3 or more grid library over each other

### ISSUE THREAD

**Issue by agorog** [IBVSoftware/CollaBoard-Feedback#133]
Project Code: 1648
Project Key: naynj
Project description: Ink need 2 clicks/taps ?
ibv-collaboard:open?code=1648&key=naynj
Version: 1.3.26.0 
Date: 05.04.2017 16: 30

Only happens sometimes, not easy to reproduce. 
Project has 3 grid libraries gl01, gl02, gl03. Try to stack 02 on 01 (ok), the 03 on 02 (nok). Project is open on 4 devices. One devices get (not the one where the stacking is done) message "The server asked to reload the project" The other device are ok, but show the grid libraries different, then on the device where the stacking was done. 

It never happend to me with libraries, only with grid librariey.

**Comment by corradocavalli** [comment]
Tried a few times but can't reproduce, please give us a reproducible scenario.

**Comment by agorog** [comment]
Fixed with 1.3.30.0
