### ISSUE TITLE
Edit different sticky notes on different devices at same time crashes CollaBoard 

### ISSUE THREAD

**Issue by agorog** [IBVSoftware/CollaBoard-Feedback#134]
Project Code: 1648
Project Key: naynj
Project description: Ink need 2 clicks/taps ?
ibv-collaboard:open?code=1648&key=naynj
Version: 1.3.26.0
Date: 05.04.2017 17:10

Difficult to reproduce. Does not happen all the time, but enough, so has to be fixed. 

Have project open on 3 devices. 6 sticky notes. Put 4 sticky notes in edit mode on first device. put 1 sticky note in edit mode on second device. put 1 sticky note in edit mode on third device. Ink the sticky notes. Now save on first device the 4 sticky notes in edit mode. On of the other devices get the "It seems we have an error...". CollaBoard closes project, then either you cant to anything in CollaBoard and have to end with X or CollaBoard ends himself.

**Comment by corradocavalli** [comment]
Tried but can't reproduce it, again, please provide a repro scenario.

**Comment by agorog** [comment]
We have issues better describing the problem, so we close this
