### ISSUE TITLE
"Enter" button to submit Project Key and Code

### ISSUE THREAD

**Issue by Livia-F** [IBVSoftware/CollaBoard-Feedback#139]
When I put in the Project Key and Code, in order to Submit ("OK" button) I need to click on it (with touch or mouse). It would be nice to be able to just press Enter on the keyboard to submit the Key and Code.

Tested on Surface Hub at 17:18 and on Surface 3 at 17:20 on March 7th, 2017.

**Comment by corradocavalli** [comment]
Done
