### ISSUE TITLE
[feature request] Sticky note

### ISSUE THREAD

**Issue by tamarawasser** [IBVSoftware/CollaBoard-Feedback#141]
I'm working in the same Project with Michael and Ale. I start working on a Sticky Note, enter edit mode and start inking. Then Ale starts working on a sticky note. Now Ale's sticky note is in front of mine. I have to touch my sticky note, that I can start editing again. 
It would be nice if the sticky note one Person is working on is still in the front.

**Comment by gsantopaolo** [comment]
@tamarawasser  please add to the CB FDS and close
