### ISSUE TITLE
Wav format able to load, unable to reproduce

### ISSUE THREAD

**Issue by teguria** [IBVSoftware/CollaBoard-Feedback#143]
Usually, I cannot see the files I cannot load on CollaBoard. For WAV FIles, I can upload them but cannot reproduce them

**Comment by teguria** [comment]
This is still happening

**Comment by corradocavalli** [comment]
It works on my machines. 
Does your machine is able to play wav files? can you try with the sample you have at this link? http://freewavesamples.com/kurzweil-k2000-dual-bass-c1

**Comment by teguria** [comment]
this works now (tested on several machines). Closing
