### ISSUE TITLE
Video is not working while sb is uploading big datas

### ISSUE THREAD

**Issue by tamarawasser** [IBVSoftware/CollaBoard-Feedback#146]
9th of March 2017
10:15
Tamara on a Surface Pro 4
Marina on a Surface Pro 3
Project Code: 1713
Project Key: obob7

Marina is uploading a big PDF file (100 pages and a lot of Pictures included). In the meantime I try to record a Video. When I stop recording, the Video is not saved. When Marina's PDF is uploaded I try to record a Video again. I stopped the Video and it's saved.

**Comment by gsantopaolo** [comment]
@tamarawasser  can you try if this is same with the latest version for beta tester and close please if is now ok?
thanks

**Comment by teguria** [comment]
Right now @tamarawasser cannot install the dev version, she has issues with her laptop. I think you can close at the moment and then we reopen as long as we are all in the beta test environment.
