### ISSUE TITLE
CB will delete grid library

### ISSUE THREAD

**Issue by tamarawasser** [IBVSoftware/CollaBoard-Feedback#147]
9th of March 2017
Project Code: 1715
Project Key: dayxc

There is a grid library with 9 fields to fill stuff in it. When the grid library is full with stuff (so 9 tiles in it) and you will make the size smaller, for example just 4 fields, CollaBoard ask you if you want to delete the tile. The message should be another like: You can't resize this grid library because ther is too much stuff in it to resize....

**Comment by gsantopaolo** [comment]
@tamarawasser  can you please check if with .52 you still have this issue? Once you will confirm we will investigate as soon as we will finish our actual dev sprint.
Expect an answer next week, thank you.
