### ISSUE TITLE
Ink not shown completly after moving out of grid lib

### ISSUE THREAD

**Issue by agorog** [IBVSoftware/CollaBoard-Feedback#148]
Project Code: 1719
Project Key: f5y6w
Project description: Test 36 from Template Corrado 16
ibv-collaboard:open?code=1719&key=f5y6w
Version 1.3.36.0
Date 09.03.2017 11:55 

Move Sticky note 3h from grid lib new to canvas. Not all ink is shown. Edit sticky note, ink is shown. Reproducable.

**Comment by agorog** [comment]
Version 1.3.50.0 still same, when moving the 3h sticky note out of grid lib new the lila ink is not shown, only after you got edit mode and then save.

**Comment by gsantopaolo** [comment]
@agorog  can you please verify this with the latest beta and close if solved please?

**Comment by agorog** [comment]
Fixed with 1.3.60.0
