### ISSUE TITLE
Internet connection missing (but it's not)

### ISSUE THREAD

**Issue by teguria** [IBVSoftware/CollaBoard-Feedback#150]
A reseller tried to launch CollaBoard on his Surface Hub and got the following error message (in attach). This also happened to another reseller a week ago, same error message. Both of them confirmed me they were able to use Internet (one of them showed me he was connected by browsing the web) @corradocavalli @gsantopaolo 
![img_1033 003](https://cloud.githubusercontent.com/assets/19929395/23748820/834eb1ec-04c5-11e7-82b5-be9467a41fc7.jpg)

**Comment by gsantopaolo** [comment]
@teguria  can you verify if is still like this on the latest beta please?

**Comment by teguria** [comment]
I can confirm this didn't happen anymore
