### ISSUE TITLE
CollaBoard in Demo Version aftern Login by FB, twitter or Google

### ISSUE THREAD

**Issue by tamarawasser** [IBVSoftware/CollaBoard-Feedback#151]
9th March 2017
16:39
Surface Pro 4

I was logged in with my Microsoft Account. Then I logged out and registered by using my Facebook account. When I was logged in with the Facebook Account I'm in Demo Version and I don't have the possibility to choos one of the Project I already createt. The Project list is empty.

**Comment by gsantopaolo** [comment]
@tamarawasser   can you please check if with .52 you still have this issue? Once you will confirm we will investigate as soon as we will finish our actual dev sprint.
Expect an answer next week, thank you.

**Comment by tamarawasser** [comment]
It's the same as it was before. 
But I talked about that with Michael, it's not an bug, it's more a thing who needs a decision how we want to have it. Let's talk and think about it.
