### ISSUE TITLE
URGENT wrong blob statusid when tile is parent of

### ISSUE THREAD

**Issue by gsantopaolo** [IBVSoftware/CollaBoard-Feedback#153]
If a tile is on a grid, when dropped the wrong status id is passed.
Please fix asap

**Comment by gsantopaolo** [comment]
please check postupdate when dropping

**Comment by corradocavalli** [comment]
If a tile is on a grid how can it be dropped? You mean undropped? Can you provide a repro case?

On 14 Mar 2017, at 02:02, Gian Paolo Santopaolo <notifications@github.com<mailto:notifications@github.com>> wrote:


If a tile is on a grid, when dropped the wrong status id is passed.
Please fix asap

**Comment by gsantopaolo** [comment]
I do not think is right that you make a polemical comment on a bug reported at 2.00 am because I'm pushing very hard.
Please fix it ASAP thank you

**Comment by gsantopaolo** [comment]
@corradocavalli  it it that fixed?
