### ISSUE TITLE
URGENT blob status messed up when drop undrop

### ISSUE THREAD

**Issue by gsantopaolo** [IBVSoftware/CollaBoard-Feedback#154]
URGENT blob status messed up when drop undrop for both grid and tiles

please fix asap

**Comment by corradocavalli** [comment]
What do you mean exactly with messed up? Any repro case?

On 14 Mar 2017, at 02:29, Gian Paolo Santopaolo <notifications@github.com<mailto:notifications@github.com>> wrote:


URGENT blob status messed up when drop undrop for both grid and tiles

please fix asap

**Comment by gsantopaolo** [comment]
Again: please this is URGENT and simple to reproduce. I want it fixed at the speed of the light, thanks
