### ISSUE TITLE
URGENT app consuming lots of cpu

### ISSUE THREAD

**Issue by gsantopaolo** [IBVSoftware/CollaBoard-Feedback#155]
try to add 2 grid libraries 4x4 and 40 pcs very tiny in terms of bytes
when stat moving app is using a lot of cpu 40-60% 

It is very urgent to inspect and understand witch proces / object is using all that cpu 

**this is prio 1 on Wednesday** 

thank you

**Comment by corradocavalli** [comment]
Can you provide me the same list of items you used?

Thx

On 14 Mar 2017, at 04:16, Gian Paolo Santopaolo <notifications@github.com<mailto:notifications@github.com>> wrote:


try to add 2 grid libraries 4x4 and 40 pcs very tiny in terms of bytes
when stat moving app is using a lot of cpu 40-60%

It is very urgent to inspect and understand witch proces / object is using all that cpu

this is prio 1 on Wednesday

thank you

**Comment by gsantopaolo** [comment]
![image](https://cloud.githubusercontent.com/assets/9937149/23897728/8a8c5c42-08ae-11e7-8320-ac83c1388d0e.png)

try with 40 files all images all under 180K (many of them are under 80Kb drop, wait that they are uploaded (as this process will be improved) and then start manipulating... app is totally unresponsive with cpu up to 50% (running on a i7) 

I need you to investigate witch component object is causing this huge cpu usage, after you find out come back and we will find a solution together (i've already some in mind)

**Comment by gsantopaolo** [comment]
my guess is manipulator or shadows

**Comment by gsantopaolo** [comment]
fixed with minimap work
