### ISSUE TITLE
[Enhancement] - Text color on black sticky note

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#156]
When you add a sticky note with a black background and when you add text with the keyboard, the Color of the text is black as well and almost not readable.

**Comment by corradocavalli** [comment]
What should we do? Please note that we might have several unreadable color combinations not just the one you mentioned.

On 14 Mar 2017, at 09:13, Michael Görög <notifications@github.com<mailto:notifications@github.com>> wrote:


When you add a sticky note with a black background and when you add text with the keyboard, the Color of the text is black as well and almost not readable.

**Comment by gsantopaolo** [comment]
@mtg1986 @corradocavalli our new designer / dev will care about that as soon as we will finalize with him. please remeber me to assign him this task when will be introduced to ibv
thank you

**Comment by gsantopaolo** [comment]
@tamarawasser  please add to the CB FDS and close
