### ISSUE TITLE
Tile added twice to library cause hangs

### ISSUE THREAD

**Issue by gsantopaolo** [IBVSoftware/CollaBoard-Feedback#158]
Dropped a tile on a library, it was added twice causing app to crash
![image](https://cloud.githubusercontent.com/assets/9937149/23902331/0f0e5be8-08c1-11e7-8180-da3de3087362.png)

![image](https://cloud.githubusercontent.com/assets/9937149/23902365/23700226-08c1-11e7-9e01-cacd654a1e6d.png)

Please code in a defensive way: before adding check if the element is already in or not. 
Those kind of bug are not welcome any more

**Comment by corradocavalli** [comment]
A guard has been added to prevent the exception to raise.
