### ISSUE TITLE
different order of the pictures

### ISSUE THREAD

**Issue by tamarawasser** [IBVSoftware/CollaBoard-Feedback#162]
16th March
Surface Hub
Surface Pro 4 and 3
09:47
Project Code: 1765
Project Key: npqq8

On the Surface Hub we uploaded 6 pictures. The order of the pictures on the Surface Hub is one picture next to the other. The order on the Surface Pros is different. The pictures stack one over the other. #

**Comment by gsantopaolo** [comment]
@tamarawasser  can you please check if with .52 you still have this issue? Once you will confirm we will investigate as soon as we will finish our actual dev sprint.
Expect an answer next week, thank you.

**Comment by tamarawasser** [comment]
I uploaded 6 pictures again. The pictures on the Surface Hub and on the Surface Pro stack one over the other but on the Surface Hub one picture is much bigger than the others: 
![different picture size](https://cloud.githubusercontent.com/assets/25382402/24298238/aae3861a-10a5-11e7-8d20-483becbe57b6.PNG)
When I tap the picture on the Surface Pro it becomes as big as the one on the Surface Hub
![different picture size_2](https://cloud.githubusercontent.com/assets/25382402/24298357/1064b928-10a6-11e7-8a3f-a8620d9774c9.PNG)

I uploaded 5 pictures. They had all the same size but the order was different on the Surface Hub and on the Surface Pro:
![order surface hub](https://cloud.githubusercontent.com/assets/25382402/24298848/934b3686-10a7-11e7-8ebf-f534455c9dfd.PNG)
![order surface pro](https://cloud.githubusercontent.com/assets/25382402/24298857/97d2270a-10a7-11e7-94e4-c785025241c7.PNG)

**Comment by gsantopaolo** [comment]
it happens only in few cases, as already discussed this will be a known issues... we will work on that later
