### ISSUE TITLE
Video is not saved

### ISSUE THREAD

**Issue by tamarawasser** [IBVSoftware/CollaBoard-Feedback#164]
16th of March
10:01
Surface Pro 4
Project Code: 1765
Project Key: npqq8

I recorded a video around 20 to 30 seconds. When I clicked to stop the video it wasn't saved. That means I just saw the open camera, but no saved video file. 
It happened again with a 10 seconds video. 
With the third trial it works and the video was saved.

**Comment by agorog** [comment]
See #95
