### ISSUE TITLE
Input data cannot be processed in the non-chronological order

### ISSUE THREAD

**Issue by teguria** [IBVSoftware/CollaBoard-Feedback#165]
When moving a sticky note in CollaBoard I got this error message (Livia from Ale's PC).

This was on HP Spectre at 14:28 on March 16th 2017.
![error_message_project_1777_1428](https://cloud.githubusercontent.com/assets/19929395/23998516/a97332a4-0a55-11e7-8984-109b294188b2.jpg)

**Comment by corradocavalli** [comment]
Added guard to prevent the exception to raise.
