### ISSUE TITLE
Big sticky note issues

### ISSUE THREAD

**Issue by agorog** [IBVSoftware/CollaBoard-Feedback#167]
Project Code: 1801
Project Key: qrrno
Project description: Test big sticky
ibv-collaboard:open?code=1801&key=qrrno
Version 1.3.50.0 
Date 18.03.2017 11:00

Project has only one big sticky note.  There are several problems working with such a sticky: 

1. When you open project minimap is positioned in right bottom, should be left top. 

2. When moving with minimap to left top you see no inking, when you press edit, the ink is shown. 
So if you open the project and move around using minimap you never see the ink, only when you got to edit mode.

3. On not Hub if you want to edit, you cant because the toolbar cant be activated. On Notebook I can put Sticky note in edit mode with mouse right click, but then I still cannot choose pencil/color etc. I also cant save.  The toolbar is generally to small if the tile is so big, has to checked with the ux redesign what we can do here.

4. I have no access to the radial menu, even if I am not in edit mode. So I can't close the project.

5. I can only cancel Collaboard. The sticky note stays then locked for a certain time. On the two other devices where the project was open, sometimes the lock disappeared, sometimes it stayed and when loading project again, lock was not here anymore. This has to be investigated with another project.

**Comment by agorog** [comment]
On Surface Pro I cannot put sticky note to edit mode with right mouse click, neither with Touchpad nor with the same mouse I used on the Notebook

**Comment by gsantopaolo** [comment]
@corradocavalli  can you update?

**Comment by gsantopaolo** [comment]
@agorog  as sai before we will look into this as soon as our dev sprint will end.
Expect an answer by next week, thank you

**Comment by gsantopaolo** [comment]
@corradocavalli  is still like this?

**Comment by agorog** [comment]
V60: after creating a project and adding a sticky not making it big I get panda and cant project anymore, example project 5982 and 5981.

**Comment by gsantopaolo** [comment]
Steps to reproduce it:
1. create new project
2. add sticky 
3. enlarge it with two fingers the most you can
4. you will get  a panda
5. restart project
6. you won't be able to open it because you will get a panda

**Comment by corradocavalli** [comment]
Starting with build 60 every tile has a maximum size of 1000x1000 to avoid this kind of issue. 
Also added an additional check to ensure tile size doesn't exceeded maximum value (this allows loading of projects like 1801)
@agorog can you update us on this an tell us what issues are still affecting latest build?

**Comment by agorog** [comment]
Tested with Version 62 and Project 1952 / txd75, the max size of a sticky is now limit, but in my opinion this is too small. What is going to happen with the project, where we have bigger tiles ?

**Comment by corradocavalli** [comment]
Big tiles will be shrunken to max 1000x1000 size, let's anyway discuss about a more suitable size.

On 13 Apr 2017, at 15:58, agorog <notifications@github.com<mailto:notifications@github.com>> wrote:


Tested with Version 62 and Project 1952 / txd75, the max size of a sticky is now limit, but in my opinion this is too small. What is going to happen with the project, where we have bigger tiles ?

**Comment by agorog** [comment]
The 1000x1000 size has to be changed back asap. On the hub the max size of a sticky is now too small, smaller then on a surface pro. Dont know which pixel type 1000x1000 is. The problem has to fixed generally not by limiting the size of a tile.
