### ISSUE TITLE
Tile lock 

### ISSUE THREAD

**Issue by agorog** [IBVSoftware/CollaBoard-Feedback#168]
Project Code: 1802
Project Key: vpagb
Project description: Test sticky inking
ibv-collaboard:open?code=1802&key=vpagb
Version 1.3.50.0 
Date 18.03.2017 11:50 

Project open on 3 devices. 
I edit sticky note with Ink Lock test, then cancel CollaBoard on Notebook. Sticky not is shown locked on other two devices also after 5 minute wait. Close project on on device and open again, sticky note is shown locked. 
Start CollaBoard on Notebook, where I canceled CollaBoard. Open project, sticky note is not shown locked, well its me who is locking, so it is correct not show locked, but it is also not in edit mode. 

Actually I let the project like this so sticky is shown as locked ba andreas.gorog@ibv.ch

**Comment by gsantopaolo** [comment]
Thanks for your feedback, we will investigate as soon as we will finish our actual dev sprint.
Expect an answer next week, thank you.

**Comment by corradocavalli** [comment]
Tile should enter edit mode automatically with recent builds (>50) when left in edit mode. Can you confirm?
@gsantopaolo Is the 'auto unlock of orphaned tiles' feature in now?

On 23 Mar 2017, at 13:44, Gian Paolo Santopaolo <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks for your feedback, we will investigate as soon as we will finish our actual dev sprint.
Expect an answer next week, thank you.

**Comment by agorog** [comment]
Fixed with 60
