### ISSUE TITLE
Surfache Hub does not show project templates

### ISSUE THREAD

**Issue by agorog** [IBVSoftware/CollaBoard-Feedback#169]
Version: 1.3.50.0
Date 18.03.2017 12:00 

On Hub the available project templates list is empty when creating a new project. 
On PC, Surface Pro templates are shown.

**Comment by corradocavalli** [comment]
Do you see the project list empty or you don't see any list at all?

On 18 Mar 2017, at 12:16, agorog <notifications@github.com<mailto:notifications@github.com>> wrote:


Version: 1.3.50.0
Date 18.03.2017 12:00

On Hub the available project templates list is empty when creating a new project.
On PC, Surface Pro templates are shown.

**Comment by corradocavalli** [comment]
Good catch...
@gsantopaolo are templates supported on tha hub or should client hide them?

On 18 Mar 2017, at 12:16, agorog <notifications@github.com<mailto:notifications@github.com>> wrote:


Version: 1.3.50.0
Date 18.03.2017 12:00

On Hub the available project templates list is empty when creating a new project.
On PC, Surface Pro templates are shown.

**Comment by gsantopaolo** [comment]
done
