### ISSUE TITLE
Tile coming from a previous project

### ISSUE THREAD

**Issue by teguria** [IBVSoftware/CollaBoard-Feedback#173]
1.3.51.0
Project: 5255
Key: uuevp
Device: HP Spectre X360
Time: 15.09 Date: 20/03/2017
I opened a previous project with some sticky notes in it. Then I closed it. I then created a new one (credentials above) and created a sticky note and a recorded an audio.
-> Clicked on edit the audio as I wanted to ink on it -> the ink coming from the previous project appeared on the audio tile.
After finishing to write this, I switched to CollaBoard and the app closed itself automatically.

**Comment by gsantopaolo** [comment]
@teguria  this is a bit old, can you confirm you are still experiencing that issue?

**Comment by teguria** [comment]
not happening anymore. Closing it
