### ISSUE TITLE
[Question] How to change the description of project created on the Surface Hub

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#176]
When I create a project on the Surface Hub, I cannot change the project description on the Hub. I logged in on my personal device and there I cannot change it either.

Is there a way to do that, I do not know?

**Comment by mtg1986** [comment]
When I create a project on my Surface Pro with my user Account then I can change the project description. And I do see the icon.

**Comment by gsantopaolo** [comment]
This is a very good question.
And the answer is: at the moment you can't because project created from a surface hub does not have a real owner.
We have to discuss the best way to pass the ownership of project created from the Surface Hub to registered users....

**Comment by gsantopaolo** [comment]
added to the list of new development
