### ISSUE TITLE
Two user ink one sticky note: Only one ink pencil/colour

### ISSUE THREAD

**Issue by agorog** [IBVSoftware/CollaBoard-Feedback#178]
Project Code: 1839
Project Key: kpion
Project description: Test54
ibv-collaboard:open?code=1839&key=kpion
Version 1.3.54.0 
Date: 23.03.2017 16:50 
Device: Hub 

Two user can ink at the same time the same sticky note. Works fine. 
But only with one pen settings. i.e. I choose red with Pen 1, then green with Pen 2, both inking are done with green, the last choosen pencil.

**Comment by gsantopaolo** [comment]
@agorog  can you try with the latest release and close please?

**Comment by agorog** [comment]
Fixed with 60
