### ISSUE TITLE
Ink Menu ist not multiuser

### ISSUE THREAD

**Issue by agorog** [IBVSoftware/CollaBoard-Feedback#180]
Project Code: 1839
Project Key: kpion
Project description: Test54
ibv-collaboard:open?code=1839&key=kpion
Version 1.3.54.0
Date: 23.03.2017 16:50
Device: Hub

Put 2 sticky in edit mode. 
Select pencil/colour on sticky one, menu with colours is displayed. 
Go to sticky two and Select pencil here. Colour choose on first sticky disappears and colour chooser is displayed on sticky two. Go back to sticky one, select here pencil again, then on sticky two colour chooser  disappears and so on.

**Comment by gsantopaolo** [comment]
@agorog  can you confirm is still like this or can we close this?

**Comment by agorog** [comment]
Similar with 62, change is: you have choose color open on first sticky, then on second sticky you call this menu, then menu disappears on first sticky and no menu is displayed, you then can select option again on the sticky you want.

**Comment by agorog** [comment]
With 82 Search is now fixed, i.e. you can enter Search Kriteria on two Search controls, as soon as Map is pressed on one, then on the other the Map button is disabled. As soon as Search is executed, then the Map button is enabled again.
