### ISSUE TITLE
Hub: Create new project ink description, CB hangs

### ISSUE THREAD

**Issue by agorog** [IBVSoftware/CollaBoard-Feedback#181]
Version 1.3.54 
Date 23.03.2017 17:05 
Device: Hub 

Hub: Create new project. Ink project description, ink stays and App hangs. 
Same on Surface Pro: no Problem

**Comment by gsantopaolo** [comment]
@corradocavalli  any news about this?

**Comment by agorog** [comment]
We will try with 60 in Surface Pro with Flight Mode and then report back

**Comment by gsantopaolo** [comment]
fixed
