### ISSUE TITLE
Hub: Recognition of Pen

### ISSUE THREAD

**Issue by agorog** [IBVSoftware/CollaBoard-Feedback#182]
Version 1.3.54.0 
Date: 23.03.2017 

CollaBoard does not recognize Pen 1 and 2 and so not multiuser inking is possible. 
On Hub Whiteboard you choose the colour with then Pen and then the choosen color is associated with the pen.

**Comment by gsantopaolo** [comment]
I strongly believe whiteboard isn't using the InkCanvas contro exposed by UWP APIs.... this is something we have to investigate...
