### ISSUE TITLE
Install prod version on non hub devices where test/debug version was installed

### ISSUE THREAD

**Issue by agorog** [IBVSoftware/CollaBoard-Feedback#183]
We are not able to install the productive version of CollaBoard on the systems where CB was sideloaded before. We assume it is not the system itself but the storeuser on that system. Independent what store user is logged in you never get the productive version back.

**Comment by gsantopaolo** [comment]
This is something our sys admins has to care of...

**Comment by gsantopaolo** [comment]
@agorog  may I close this issue?
