### ISSUE TITLE
Start with Welcome and radial menu

### ISSUE THREAD

**Issue by agorog** [IBVSoftware/CollaBoard-Feedback#184]
When a user starts CB he has to tab/right mouse click to get the radial menu to do something. 
Can we start CB with the radial menu automatically displayed ?

**Comment by gsantopaolo** [comment]
Hi Andi and thank you for your feedback.
Short answer to your answer is: Yes, we can.

Anyway if we look at this feature from a design point of view I don't think this a good move as there are other ways to engage users.....

**Comment by gsantopaolo** [comment]
Solved with the new start screen
