### ISSUE TITLE
[Template Projects] - Grid Content and Grid Library Title

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#185]
1.I add some sticky notes to the grid library
2.I add a grid library title
3.I close the project
4.I create a new project using a template one

-->The result is, that the grid library is empty and has no title. 

I can send you key & code if needed by E-Mail, as I do not want to make them for the template projects public.

I have tested this: 

On Desktop PC -->Here I get grid library content and title
On Surface Pro 4 --> Here I do not get grid library content and title

Version: 1.3.52.0
Date: 28.03.2017

**Comment by gsantopaolo** [comment]
We will try to investigate and reproduce

**Comment by corradocavalli** [comment]
@gsantopaolo I already investigated and created an issue for you, see issues #186 or greater.

On 31 Mar 2017, at 19:45, Gian Paolo Santopaolo <notifications@github.com<mailto:notifications@github.com>> wrote:


We will try to investigate and reproduce

**Comment by gsantopaolo** [comment]
Hi please try again an let me know if now everything is ok

**Comment by gsantopaolo** [comment]
@mtg1986  can you please check if this is solved? thanks

**Comment by mtg1986** [comment]
@gsantopaolo : Grid Library title does not show yet. 

1.Created a Grid Library in Template Project : Project Code: 5200
2.Added Grid Library Titel 
3.Added Sticky Note to Grid Library
4.Closing Project
5.Using Template project from 5200

Grid Library has no title.  

When I reopen the template project, the title is there

Tested with 1.3.61
10.04.2017 20:52
Desktop PC

**Comment by gsantopaolo** [comment]
@mtg1986  can you please verify with the latest build for beta if this is fixed, thanks

**Comment by mtg1986** [comment]
@gsantopaolo : Tested with .81, but library title does not show, when creating a new project from the template.

1.Changing Grid Library Titel in Template Project : Project Code: 5200
2.Closing Project
5.Using Template project from 5200 "How to work with CollaBoard"
Grid Library has no title.

When I reopen the template project, the title is there
Tested with 1.3.81
01.05.2017 22:05
Surface Pro 4

**Comment by gsantopaolo** [comment]
@mtg1986  any update on this?

**Comment by mtg1986** [comment]
@gsantopaolo : Still the same behavior. The grid library titel from the template project is not shown when I create a new project using the template.

**Comment by teguria** [comment]
We just tested it on a Hub:
created sticky notes
created a Library
tried to name the library using the voice command
and got a Panda (it's not you, it's us).
Trying to reproduce
