### ISSUE TITLE
Ink to Textbox - Only second word is taken

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#186]
1.I start Search
2.I ink "New York" into the text box
3.Text is recognized but only the second Word "York" is transferred into text.

Tested on a Surface Pro 4
Version:1.3.52.0
Any project
Date: 28.03.2017

**Comment by gsantopaolo** [comment]
@mtg1986 , I think a screen shoot (if possible) would make a more clear idea of what you want to mean.

thank you

**Comment by mtg1986** [comment]
Please see here the screenshots. 

![screenshot 141](https://cloud.githubusercontent.com/assets/19570958/24562619/a057d132-164b-11e7-9bde-439f572410f7.png)
![screenshot 142](https://cloud.githubusercontent.com/assets/19570958/24562618/a03190ee-164b-11e7-8ba4-c78ff07e42f5.png)

**Comment by corradocavalli** [comment]
Fixed

**Comment by corradocavalli** [comment]
Michael, can you try with latest build an close if ok?

**Comment by mtg1986** [comment]
Tested 6 times with 1.3.61 . First 5 attempts the app hangs. 6 attempt, it did work and the two words are translated correctly.

Procedure:
1.Create new project 
2.Enter description with keyboard
3.Go to search 
4.Ink to textbox (New York) 
5.App hangs and I need to restart. 

Tested on User Device. Very difficult to figure out why it works not all the time.

**Comment by agorog** [comment]
1.3.61.0 on Hub. Tested 10+ plus times on existing project to ink for Search and to ink for grid library name, 
Worked perfectly.

**Comment by corradocavalli** [comment]
Can yo tell us what model is the device where you experience the issue?

**Comment by mtg1986** [comment]
Tested on Hub and Surface Pro with 1.3.62 
13.04.2017 
Is working now.
