### ISSUE TITLE
Template cloning issue

### ISSUE THREAD

**Issue by corradocavalli** [IBVSoftware/CollaBoard-Feedback#187]
Steps to reproduce:
1-Use PROD environment
2-Create a new project using "Agenda Template" template
3-Generated project has an empty grid library while original has some tiles in it.

Some example of cloned projects are:
5011/bygl5
5607/mfkdm

from initial inspection looks like that cloned project's grid library misses child tiles.

**Comment by gsantopaolo** [comment]
Hi please try again an let me know if now everything is ok

**Comment by gsantopaolo** [comment]
tested and now works
