### ISSUE TITLE
Enhancement Idea: Copy Project Link

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#190]
When coping the key and code of a project it would be nice to have direct an hyperlink that you can send by E-Mail or Chat to someone. 

![image](https://cloud.githubusercontent.com/assets/19570958/24566755/077fc04a-165b-11e7-9641-1a2356992ed8.png)

**Comment by corradocavalli** [comment]
Isn't the last part of copied content what you're asking for?

On 31 Mar 2017, at 21:45, Michael Görög <notifications@github.com<mailto:notifications@github.com>> wrote:


When coping the key and code of a project it would be nice to have direct an hyperlink that you can send by E-Mail or Chat to someone.

[image]<https://cloud.githubusercontent.com/assets/19570958/24566755/077fc04a-165b-11e7-9641-1a2356992ed8.png>

**Comment by mtg1986** [comment]
Yes I get a link there, but when I past the content to Outlook the link is not a hyperlink. 

To make it a hyperlink I need to add an address. It would be nice to have directly a hyperlink.

Project Code: 5592
Project Key: ns2sc
Project description: Test
ibv-collaboard:open?code=5592&key=ns2sc

![image](https://cloud.githubusercontent.com/assets/19570958/24567060/639b3cfa-165c-11e7-888a-355c3d3cc28f.png)

**Comment by gsantopaolo** [comment]
Unfortunately we are not Office expert and from our knowledge this seems not possible, maybe an office expert can help us, but as said we are not so we need to find some that can help us.
@mtg1986  discuss with the board and please feel free to find an office expert to help us or close this 

thank you
-g

**Comment by gsantopaolo** [comment]
@tamarawasser  please add to the CB FDS and close
