### ISSUE TITLE
Got a Panda

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#192]
Time: 00:32 01.04.2017
Last Action: Added a screenshot from snipping tool. I was doing nothing when the panda appeard.
Project was reloaded and I could continue working on.
Device: Desktop PC

I can provide key and code by E-Mail if needed.

**Comment by gsantopaolo** [comment]
as soon as we will calm down a notch we will investigate...

**Comment by gsantopaolo** [comment]
going to close as it is too old...
