### ISSUE TITLE
V 56: Can't save ink 

### ISSUE THREAD

**Issue by agorog** [IBVSoftware/CollaBoard-Feedback#193]
Version 1.3.56.0 
Date 01.04.2014 08:00 
Project: any
Device: any 

I can ink a tile and when I want to save it the panda comes. 
CollaBoard closes project, ink is not stored. 

![grafik](https://cloud.githubusercontent.com/assets/19590642/24598229/96d2785a-184a-11e7-9381-b3a3a30c28ed.png)
****

**Comment by corradocavalli** [comment]
we had a merge issue wit v56, please ignore it and wait for build 57 (coming soon)
