### ISSUE TITLE
V56: Sticky note text background grey 

### ISSUE THREAD

**Issue by agorog** [IBVSoftware/CollaBoard-Feedback#194]
The sticky note background if using keyboard has changed. It is now grey with a very poor contrast, making it difficult to read. Before the background of the text was the same as the background of the ink

Sticky showing:
![grafik](https://cloud.githubusercontent.com/assets/19590642/24598263/cea56fe4-184a-11e7-9688-42d8b9e2a0a6.png)

Sticky editin: 
![grafik](https://cloud.githubusercontent.com/assets/19590642/24598283/e3e1bc6e-184a-11e7-92dc-78ebdd4ed0f2.png)

**Comment by corradocavalli** [comment]
fixed in build 57
