### ISSUE TITLE
Ink to Textbox hangs

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#196]
I tried today to enter a grid library title with Ink to textbox. When I finished inking nothing happend and I needed to restart the application. CollaBoard was somehow freezed. Very difficult to reproduce, as I do not see any pattern and it happens not regularly.

Surface Pro 4
Version: 1.3.52 
Time: apporx. 10:05
Project Code: 5868
Project Key: 38qjd

**Comment by corradocavalli** [comment]
We tried several times without being able to reproduce it, can you please try again with latest release?

**Comment by teguria** [comment]
Not sure if this is the same issue but I got a similar experience while using the search button and ink on it. Basically it's related to inking 2 words. I inked "New York" and CB hanged (version .52).
Device Model: HP Spectre X360

**Comment by mtg1986** [comment]
We tried now on the Hub with 1.3.62 and we faced several issues: 

1.Create new project 
2.Add description with "Ink to Textbox" 

Worked 2 times and it did not work 2 times. I am not able to say, what is the pattern why it is working once and then not anymore.

**Comment by mtg1986** [comment]
Tested several times on Surface Pro. Not able to reproduce. Close Bug
