### ISSUE TITLE
Multiink bugs on Hub with Version 59

### ISSUE THREAD

**Issue by agorog** [IBVSoftware/CollaBoard-Feedback#197]
Version 59
Date 4.4.2017 20:10   
DB: dev and prod (explanation in text) 

Project in dev: 
Project Code: 1900
Project Key: ipage
Project description: Test 59 on hub
ibv-collaboard:open?code=1900&key=ipage

Project in prod (hub, after unplug and reboot) : 
Project Code:  5910 
Project Key: qm7uu

We had several problems. First Hub was pointing to dev db, we worked there. Then we did some multiink and then hub hanged, we even couldnt restart had to unplug. After reboot CB was pointing to prod db, really strange. Rebooted Surface Pro, still pointing to dev. 
We upload a video showing the Surface Hub hanging, not be able to do anything. 

Then we found some bugs multink on the hub. 

1. Inked on two stickys, simultanious ink, does not ink, ink on second sticky deletes ink on first one, see second video which will be uploaded soon. 

2. Erase all ink on first sticky, erase ink on second sticky. After erase we cant ink second sticky, we can ink first sticky and then can ink second sticky but color is not the one selected and after doing this several times we got a panda. See third video.

**Comment by teguria** [comment]
As the files are too big, I uploaded them here: https://ibvinfo.sharepoint.com/sites/mktg/_layouts/15/guestaccess.aspx?guestaccesstoken=jK%2f39yzsf1HTZ44f7B806X3bJVDW61YA%2byQWJB1j%2brA%3d&folderid=2_136f56f9a16e6404da6dd80b54c8c783d&rev=1

**Comment by gsantopaolo** [comment]
@corradocavalli it seems that some instances are shared we need to give a look together at that code...

**Comment by gsantopaolo** [comment]
@teguria can you upload that on your private onedrive? on office 365 i've problem watching that videos

**Comment by teguria** [comment]
Ok, Uploading them here: https://1drv.ms/f/s!AokjDqTnRRs80fsLk1QlKh5QX9aAdw

**Comment by corradocavalli** [comment]
Looks like a 'issue' with the InkToolbar, we had to temporarily remove "Erase all Ink" functionality, please give build 60 a try and let us know your feedback.

**Comment by agorog** [comment]
With 1.3.60.0: Delete ink fixed, i.e. it deletes in the sticky we want not in the other one, I can ink after deleting

**Comment by agorog** [comment]
With 1.3.60.0: Ink on two sticky notes. Still the same as with 59 including deleting ink in first sticky when inking the second

**Comment by corradocavalli** [comment]
What exactly is the issue still present on v60?
Hub/PC or both?

On 5 Apr 2017, at 19:57, agorog <notifications@github.com<mailto:notifications@github.com>> wrote:


With 1.3.60.0: Ink on two sticky notes. Still the same as with 59 including deleting ink in first sticky when inking the second

**Comment by gsantopaolo** [comment]
Step to reproduce it:
Open 2 sticky ink on first, while inking on first start inking on second, ink in first disappears

**Comment by agorog** [comment]
Version 1.3.61.0: Still same, see comment "Step to reproduce it":

**Comment by agorog** [comment]
Inking the same time on 2 different tiles does not work, there is a request at MS. We close for the moment and will investigate again when we have an answer from MS.
