### ISSUE TITLE
CB hangs after moving sticky note to grid library 

### ISSUE THREAD

**Issue by agorog** [IBVSoftware/CollaBoard-Feedback#199]
Project Code: 5970
Project Key: thrjh
Project description: he test 6.4.
ibv-collaboard:open?code=5970&key=thrjh
Version : 1.3.60.0 
Date 06.04.2017 09:11
Device: Surface Pro 4

Moved sticky not to grid library, sticky disappears is not shown in grid library, Collaboard hangs/freezes, can't do anything. After few seconds CollaBoard ends itself. 

Loading the project after restart of CollaBoard, the sticky note is shown outside of the grid library, no data loss. 

Here is the Windows System Log: 
- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Application Error" /> 
  <EventID Qualifiers="0">1000</EventID> 
  <Level>2</Level> 
  <Task>100</Task> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2017-04-06T07:11:49.053287800Z" /> 
  <EventRecordID>24526</EventRecordID> 
  <Channel>Application</Channel> 
  <Computer>DESKTOP-6NN0NPK</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data>CollaBoard.exe</Data> 
  <Data>1.0.0.0</Data> 
  <Data>58e4feb6</Data> 
  <Data>SharedLibrary.dll</Data> 
  <Data>1.4.24201.0</Data> 
  <Data>574e6cd1</Data> 
  <Data>00001007</Data> 
  <Data>000000000041cf48</Data> 
  <Data>51c</Data> 
  <Data>01d2aea0abd75199</Data> 
  <Data>C:\Program Files\WindowsApps\EC97A45D.CollaBoard_1.3.60.0_x64__zsdrwq5td3y3w\CollaBoard.exe</Data> 
  <Data>C:\Program Files\WindowsApps\Microsoft.NET.Native.Framework.1.3_1.3.24201.0_x64__8wekyb3d8bbwe\SharedLibrary.dll</Data> 
  <Data>9cceb929-1d1e-4cb1-a560-3dbdcad024c2</Data> 
  <Data>EC97A45D.CollaBoard_1.3.60.0_x64__zsdrwq5td3y3w</Data> 
  <Data>App</Data> 
  </EventData>
  </Event>

**Comment by gsantopaolo** [comment]
I think this is one of that bug that we need to catch at the next test session

**Comment by agorog** [comment]
Didn't have this problem anymore, so we close
