### ISSUE TITLE
CB freezes after Surface Pro goes to sleep mode

### ISSUE THREAD

**Issue by agorog** [IBVSoftware/CollaBoard-Feedback#201]
Version: 1.3.61.0 
Win 10: Creator's Update 
Date: 10.4.2017 afternoon 

Let Surface Pro 4 with CB project open for a few hours. After coming back and activating the PC, CollaBoard showed still active, it could be minimized, maximized, but in CollaBoard itself I could do anything. Closed App with x. 
Can be reproduced.

**Comment by corradocavalli** [comment]
Tried different combinations but can't reproduce, to better understand:
-Does it happen also if you put device in sleep mode using shutdown option->Sleep. 
-Does it happen with every project?

**Comment by corradocavalli** [comment]
Can this be the same as issue #208? can you try again with build 62?

**Comment by agorog** [comment]
Fixed with 62
