### ISSUE TITLE
When I take out a Sticky from Library, text is partially showed

### ISSUE THREAD

**Issue by teguria** [IBVSoftware/CollaBoard-Feedback#203]
Device: HP Spectre
Time: 20.35
Date: 10/04/2017
Versioning: 1.3.52.0
Project: ibv-collaboard:open?code=5791&key=5lcuv

I put several sticky notes in a grid library (4X4). I then checked one sticky note that was in the library but the text is not shown entirely. When I edit and save it, then it is shown again. When I put it back in the library, it is still shown but when I drag it out from it, the text is partially shown

**Comment by corradocavalli** [comment]
@teguria please try with latest beta build (we did a lot of improvements in that area) and let us know.

**Comment by mtg1986** [comment]
Could not reproduce this bug anymore. 
Tested on Surface Hub and Surface Pro
1.3.62.0 
13.04.2017
