### ISSUE TITLE
Pencil is default pen type selected when creating a new sticky note

### ISSUE THREAD

**Issue by teguria** [IBVSoftware/CollaBoard-Feedback#204]
Device: HP Spectre
Time: 20.39
Date: 10/04/2017
Versioning: 1.3.52.0
Project: ibv-collaboard:open?code=5791&key=5lcuv

Everytime I create a new sticky note, the pencil is the first one "pen type" selected while I think it should be the Ballpoint Pen).

**Comment by corradocavalli** [comment]
@teguria are you sure? the default pen is indeed ballpoint pen (pencil is the 2nd) in any case I've added code to force Ballpoint selection, please verify with next release

**Comment by mtg1986** [comment]
Not able to reproduce on Hub and Surface Pro 4
1.3.62.0

**Comment by teguria** [comment]
Not happening anymore. Closing
