### ISSUE TITLE
Error Message - User not authorized

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#207]
Problem at one of our customers. 

1.Loing on a personal device. 
2.Create a new project
3.Enter description
4.-->Error Message appears and a new project cannot be created. 

Version 1.3.52.0
11.04.2017 approx. 15:50

User is testing the App in German. The translation of the error message is: 

Oops, it seems that the server does not like that.
Oops, it seems that the user is not authorized

![user_not_authorized](https://cloud.githubusercontent.com/assets/19570958/24913014/22aacc8e-1ed0-11e7-8bdf-da662985e1f5.PNG)

What can we do here?

**Comment by gsantopaolo** [comment]
This seems a bug on licensing. Please next week ask me to test. We will need some devices and about one hour to perform all tests

**Comment by corradocavalli** [comment]
@mtg1986 Can we close this?

**Comment by mtg1986** [comment]
@corradocavalli : Still waiting for confirmation from customer (I can't reproduce it)

**Comment by mtg1986** [comment]
Bug does not appear anymore. Therefore closing the issue.
