### ISSUE TITLE
Panda with Lasso on Hub

### ISSUE THREAD

**Issue by agorog** [IBVSoftware/CollaBoard-Feedback#210]
Project Code: 6197
Project Key: cz6a2
Project description: Rrr
ibv-collaboard:open?code=6197&key=cz6a2
Version 1.3.61.0 
Device: SFHub03_Andi
Date: 12.04.2017 15:00 - 15:20 

Project has 3 stickys edit any sticky on Hub and try to lasso somehting produces a Panda. 
No problem on other devices, only on Hub. 

Created new project 6201/0dcpa did same. same problem on Hub only 

Also on Hub we get Panda if on sticky note click on Eraser in these projects.

**Comment by corradocavalli** [comment]
Does it happen on this specific project or with all projects running on hub? Can't replicate so i need to clearly understand what's going on.

**Comment by agorog** [comment]
I think I found the secanrio. It depends on copy/paste. I lasso then copy/paste do this 1-2 times and then I get the panda. From then on even if I close/load project any lasso, erase generates a panda. When I end CB and start again then everything works until I have the first time panda with copy/paste and then the same behaviour until restart of CB.

**Comment by corradocavalli** [comment]
This scenario you discovered is reproducible on non hub devices?

**Comment by mtg1986** [comment]
On the Hub we can reproduce it. 

Tested with project: 
1945
53189

-->Then when we got the Panda we went back to demo version.

**Comment by mtg1986** [comment]
Please see here the screenshot + our whiteboard notes about how to reproduce it: 

![image](https://cloud.githubusercontent.com/assets/19570958/25004739/205a83ca-2056-11e7-8747-91829bc1cfd6.png)

After restarting CB, licensing is working now again.

**Comment by agorog** [comment]
We still have Pandas with 62 and also that after lasso/copy/paste cant ink anymore, or colour is wrong. Different things we have to investigate in the testing week

**Comment by corradocavalli** [comment]
We have added trace in new build to get some telemetry data, we'll debug it on hub next week though.

On 13 Apr 2017, at 15:48, agorog <notifications@github.com<mailto:notifications@github.com>> wrote:


We still have Pandas with 62 and also that after lasso/copy/paste cant ink anymore, or colour is wrong. Different things we have to investigate in the testing week

**Comment by gsantopaolo** [comment]
@agorog  @mtg1986  can you please verify with the latest beta if this is still a bur or is fixed please?

**Comment by agorog** [comment]
fixed 1.3.82
