### ISSUE TITLE
GetProjectList when user isn't logged

### ISSUE THREAD

**Issue by gsantopaolo** [IBVSoftware/CollaBoard-Feedback#211]
version .52
 CollaBoard.ViewModels.ControlCenterViewModels.Units.ProjectListViewModel METHOD: GetProjectList MESSAGE: System.InvalidOperationException: Do you want to use that feature? You just need to log in

if user isn't logged please do not call server

**Comment by corradocavalli** [comment]
I verified that, as discussed via mail, that error is raised by the CollaborationService.**GetTemplateProjectsAync** API. when a demo/Team user tries to retrieve the list of templates. Since feature is available also for non authenticated users think API should be fixed.

**Comment by gsantopaolo** [comment]
@corradocavalli  please test and let me know
