### ISSUE TITLE
Copy & Past Ink with Lasso - Movement not possible on 2nd Sticky Note

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#212]
1.Ink on a sticky note
2.Use lasso and copy the ink 
3.Past Ink to another sticky note 
4.On the sticky note, where I copied the ink, I see the blue navigation icon, but I cannot move the copied ink around. It is not possible to grab the copied ink. If I use the pen it inks directly, altough I try to grab the navigation icon of the copied ink.
I can still move it in the sticky note from where I copied it.

**Comment by corradocavalli** [comment]
On what device are you testing? hub or pc? when you paste on paste on 2nd icon are you using the pen to move pasted ink, if so, toolbar selected item is lasso when you paste?

**Comment by mtg1986** [comment]
Tested on Surface Hub. It is difficult to explain, may be we need to figure this better out during the testing blocks next week.

**Comment by mtg1986** [comment]
Tested again on the Hub. Not reproducable anymore.
