### ISSUE TITLE
Tiles in GridLibrary Dissapear when realoading a project

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#217]
Create a project with multiple Grid Libraries on different devices. 

1.Close CollaBoard on a Surface Pro
2.Relaod the Project 
3.All tiles in grid library are not there

4.Synchronize project (under settings)
5.Project is reloaded
6.Grid Library tiles are there.

Project: 6423
Key: mxx7g

20.04.2017, 10:35
Version: 1.3.71

**Comment by corradocavalli** [comment]
Fixed in 1.3.80, please verify.

**Comment by mtg1986** [comment]
Not able to reproduce anymore. Tested 01.05.2017 with 1.3.81
