### ISSUE TITLE
Changing language doesn't trigger CB to restart

### ISSUE THREAD

**Issue by teguria** [IBVSoftware/CollaBoard-Feedback#222]
V. 74
Device: SFHub
Time: 14.15
Date: 20/04/2017
CB opened, we switched language to German but we didn't get any pop-up message asking us to restart the application. Same with any language we want to switch into.

**Comment by corradocavalli** [comment]
@teguria We never had any popup message, but the label above selection box clearly indicates that a restart is required.
![image](https://cloud.githubusercontent.com/assets/5617938/25389230/52490f54-29d0-11e7-8685-ca598306b7be.png)

**Comment by agorog** [comment]
This is ok. We close this one.
