### ISSUE TITLE
Copy/pasting pictures from Chrome to CB doesn't work

### ISSUE THREAD

**Issue by teguria** [IBVSoftware/CollaBoard-Feedback#223]
Open Chrome, search for an image, right click on Copy Image
Paste with the radial menu into a project. It doesn't paste.

Works perfectly with Edge and Firefox

**Comment by corradocavalli** [comment]
Added a check to prevent the error to appears, in case of failure nothing will be pasted. Please verify with the new release.

**Comment by mtg1986** [comment]
At the moment from Chrom image search, nothing is pasted.
04.05.2017 
Version 1.3.82

**Comment by corradocavalli** [comment]
@mtg1986 It is fixed on build 83, please verify it and close if ok.

**Comment by teguria** [comment]
Works on devices. I assume it works on the Hub as well @mtg1986 ?

**Comment by teguria** [comment]
Works now. closing
