### ISSUE TITLE
Try to record a video until times ends up generate and error

### ISSUE THREAD

**Issue by gsantopaolo** [IBVSoftware/CollaBoard-Feedback#225]
If you start a video recording and you let it record until the end of the allowed time then you get the message below

![image](https://cloud.githubusercontent.com/assets/9937149/25233391/f177b954-25de-11e7-8932-5e6695c92904.png)

**Comment by gsantopaolo** [comment]
Please refer to this document https://docs.microsoft.com/en-us/windows/uwp/audio-video-camera/set-media-encoding-properties to define the right properties so on each device we will have the same amount of bytes per second

thanks

**Comment by corradocavalli** [comment]
Camera sampling rate and size are now server side controlled (default no is 640x480 30 FPS) at these values 15 MB size occupies about 14 MB.
