### ISSUE TITLE
Dropped Files are not in the visible area of canvas

### ISSUE THREAD

**Issue by agorog** [IBVSoftware/CollaBoard-Feedback#226]
Version 1.3.77
Date 21.04.2017 09:20

Open any project. Move to an area with Minimap where no tiles are. Zoom a littlle bit. 
Select several jpgs in Windows Explorer. Copy, 
Paste in CollaBoard, Files are copies but user dont see them as they are copied to an area in the canvas which is not visislbe.

**Comment by corradocavalli** [comment]
Fixed in build 79

**Comment by agorog** [comment]
Fixed with 82
