### ISSUE TITLE
Connecting Docking Station - Panda

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#229]
-Start CollaBoard and work on  a project
-Connect docking station of Surface Pro 4 
-Panda appears (see screen shot 1). 
-When I close the panda, the project closes and I go back to CollaBoard start screen, still seeing the tiles from the project. I can move the tiles from the project but cannot get the radial menu. 

Tested on a Surface Pro 4
Version: 1.3.81.0 
Time: 30.04.2017 17:28
Device: Machine ID: 62c870e7-c797-4a12-861d-6ea0f41d65e8 

![panda1](https://cloud.githubusercontent.com/assets/19570958/25565610/9a295358-2dca-11e7-92a3-b0218b93edc7.PNG)

![panda2](https://cloud.githubusercontent.com/assets/19570958/25565615/aee71672-2dca-11e7-96d3-e3d45f9790f1.PNG)

**Comment by gsantopaolo** [comment]
@mtg1986 @corradocavalli  were you able to reproduce this?

**Comment by corradocavalli** [comment]
Yes, fixed.
