### ISSUE TITLE
Licensing DEV (not sure if this is a dev only problem) 

### ISSUE THREAD

**Issue by agorog** [IBVSoftware/CollaBoard-Feedback#232]
Licensekey not valid, requesting eval says eval already requested.

![grafik](https://cloud.githubusercontent.com/assets/19590642/25696837/f9ad8ef2-30b8-11e7-8b6a-26309b4854b8.png)

**Comment by agorog** [comment]
User data is filled automatically when requesting eval lic 
![grafik](https://cloud.githubusercontent.com/assets/19590642/25696874/2af69008-30b9-11e7-950b-f6decce4dddb.png)

**Comment by agorog** [comment]
This is the lic key: 
13.04.2017 generated for Adrkey 1001: 
GgE9H0tfCYfL0g+oSd3z6f0KHPk6A8LYpDaHYLw4nz6k6mOb6DWqIQvz0KMIHLbOiqN9vMB/xerGrP0GzdXgpVJDUNMuGzJ7E8gkpbYWjZkRt/1ORspuJhsYyqTWRPpxyrptJh+GBftpb0zhQUcDOHXvvJVgMWvAsjuZU2VZRLg=

**Comment by corradocavalli** [comment]
Please try again with build 83 (public) pointing to PROD, we know some licensing issue happens when switching from PROD to DEV for internal testing.

**Comment by gsantopaolo** [comment]
Closing, too old
