### ISSUE TITLE
Tile in Edit mode is locked, but other user can move, loses locked by name

### ISSUE THREAD

**Issue by agorog** [IBVSoftware/CollaBoard-Feedback#233]
Version 1.3.82 

Project open with 3 users. One user add new sticky note, starts do ink sticky. Other user can now move sticky (before it was locked and other user could not move, should be like this). The user who is inking is suddenly inking on Canvas as tile is moved. The moved tile says is locked by first user. Now third user is moving sticky. Sticky is moved, but now the locked by name is lost, it just shows locked. 
First user now goes to moved sticky, he still sees his unsaved ink, saves ink. now everything is ok.

**Comment by agorog** [comment]
Is only this project/Tile. Delete tile and then all ok.

**Comment by agorog** [comment]
Closed wrong one.

**Comment by corradocavalli** [comment]
Fixed in build 83, please test and close is ok.
