### ISSUE TITLE
Order of PDF

### ISSUE THREAD

**Issue by tamarawasser** [IBVSoftware/CollaBoard-Feedback#234]
Project: 1990
Key: c83cr
Device: Dell
Machine ID: 7d525f2b-793b-f89b-20f1-adee628e8de1
Time: 11:24 am

The order of PDFs is different on the Dell than on the Surface Hub after uploading. 

Order on the Surface Hub:

![sh](https://cloud.githubusercontent.com/assets/25382402/25697895/0609e156-30bd-11e7-9ca9-c7770ccdd247.JPG)

Order on the Dell:

![dell](https://cloud.githubusercontent.com/assets/25382402/25697897/081b8634-30bd-11e7-9842-c64e6e42d902.JPG)

**Comment by corradocavalli** [comment]
Loaded on two machines and they look identical, closing since can't reproduce it. Reopen it if you find a reproducible sequence that causes the out-of-sync problem.
