### ISSUE TITLE
different size of a picture after closing and opening project

### ISSUE THREAD

**Issue by tamarawasser** [IBVSoftware/CollaBoard-Feedback#237]
Project: 5011
Key: bygl5I
Device: HP Spectre
Time: 6:23pm

open project
add tiles
load file
upload picture named "Meeting Agenda"
![1](https://cloud.githubusercontent.com/assets/25382402/25909671/320041a6-35ae-11e7-9a41-705a7be27096.JPG)

close project

open project again
the size of the picture is not the same anymore
![2](https://cloud.githubusercontent.com/assets/25382402/25909687/3d5f9d08-35ae-11e7-9f8b-e65394bdf56f.JPG)

**Comment by corradocavalli** [comment]
Can you try uploading the same tile agenda picture to a brand new project, close and reopen it to see if you have the same issue?

On 10 May 2017, at 18:27, tamarawasser <notifications@github.com<mailto:notifications@github.com>> wrote:


Project: 5011
Key: bygl5I
Device: HP Spectre
Time: 6:23pm

open project
add tiles
load file
upload picture named "Meeting Agenda"
[1]<https://cloud.githubusercontent.com/assets/25382402/25909671/320041a6-35ae-11e7-9a41-705a7be27096.JPG>

close project

open project again
the size of the picture is not the same anymore
[2]<https://cloud.githubusercontent.com/assets/25382402/25909687/3d5f9d08-35ae-11e7-9f8b-e65394bdf56f.JPG>

**Comment by tamarawasser** [comment]
I tried it with a new project and the same happened.

**Comment by corradocavalli** [comment]
Cool,
Please send me via mail the image that doesn't properly resize and tell me the exact sequence to follow to reproduce the issue.
Thanks.

On 11 May 2017, at 08:22, tamarawasser <notifications@github.com<mailto:notifications@github.com>> wrote:


I tried it with a new project and the same happened.

**Comment by corradocavalli** [comment]
Problem fixed, please test it with build 84 and, if ok, close it. :-)

**Comment by gsantopaolo** [comment]
@tamarawasser  can you update on this please?

**Comment by tamarawasser** [comment]
I have version 1.3.94 now and it's working.
