### ISSUE TITLE
Splash Screen on Surface Hub

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#238]
There is no possibility to disable the splash screen on the Surface Hub with v. 1.3.83

The issue is that: 
1.I want to load a project using a NFC tag
2.I did not launched CollaBoard yet
3.I use the NFC tag to open a specific project 
4.CollaBoard starts but the project is not loaded as just the splash screen appears. 

The only way to load a project with NFC at the moment is, when CollaBoard is already started and when I clicked on OK, to remove the splash screen. 

I remember this was different before, and for using the NFC tag, it would be nice if I can directly open the project without starting CollaBoard before.

**Comment by corradocavalli** [comment]
It should be fixed in version 84, please test it when available.

**Comment by gsantopaolo** [comment]
@mtg1986  can you update on this please?

**Comment by mtg1986** [comment]
Tested on .94 and it goes now directly to the project.
