### ISSUE TITLE
PDF Brochure in CollaBoard

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#239]
When I load the attached PDF into CollaBoard there is a sizing issue with the first page. Please have a look at the attached screenshot where you see how the pdf looks in Edge and how it looks in CollaBoard. 
For me it is only the first page that is not nice. The rest are good. 
Tested on Version 1.3.83
19.05.2017 

![image](https://cloud.githubusercontent.com/assets/19570958/26240771/7f806912-3c82-11e7-9b6e-9f11f2d20393.png)

[en_USTER_HVI_1000_web_brochure.pdf](https://github.com/IBVSoftware/CollaBoard-Feedback/files/1013684/en_USTER_HVI_1000_web_brochure.pdf)

**Comment by gsantopaolo** [comment]
Hello and thanks for your feedback.
We are not going to develop any more for pdf. What we are going to do for the future is to find a good component that we can implement.
Expect a fix for this only when we will found the right pdf component.

thank you
-g

**Comment by corradocavalli** [comment]
Hi Michael, just to give you more info about the issue: The PDF has a mixed layout, first page is portrait while others are landscape. At the moment we don't have an optimal solution for mixed layout PDF, we hope this scenario will be covered when we'll move to a commercial PDF component.

**Comment by gsantopaolo** [comment]
@tamarawasser  please add to the CB FDS and close
