### ISSUE TITLE
MiniMap does not properly bring selected item to the front when selected

### ISSUE THREAD

**Issue by gsantopaolo** [IBVSoftware/CollaBoard-Feedback#24]
@corradocavalli commented on [Mon Aug 01 2016](https://github.com/IBVSoftware/CollaborationHub/issues/104)

Investigate why ZIndex doesn't work on MiniMap. SCatterView:OnSelectedItemIndexChanged seems ok.

---

@gsantopaolo commented on [Wed Nov 02 2016](https://github.com/IBVSoftware/CollaborationHub/issues/104#issuecomment-257989932)

Issue moved to [IBVSoftware/CollaBoard-Issues #5](https://github.com/IBVSoftware/CollaBoard-Issues/issues/5) via [**ZenHub**](https://www.zenhub.com/)

---

@gsantopaolo commented on [Wed Nov 02 2016](https://github.com/IBVSoftware/CollaborationHub/issues/104#issuecomment-257994589)

@corradocavalli  still open or we can close?

**Comment by corradocavalli** [comment]
Fixed in V135
