### ISSUE TITLE
Cannot connect to Internet

### ISSUE THREAD

**Issue by taoyouh** [IBVSoftware/CollaBoard-Feedback#240]
When I launch the app, it stays within the splash screen for a long time, then it tells me "Internet connection missing, all functionalities are temporarily unavailable."

Time: 2016-06-10 22:00 GMT+8
OS version: 15063.332
Device: Surface Pro 3
City: Shanghai, China

**Comment by corradocavalli** [comment]
Can you reach Google.com<http://Google.com> from that machine? The fact that machine is connected doesn't guarantee that it can effectively reach our servers.

Cheers

On 10 Jun 2017, at 16:01, Huang, Zhaoquan <notifications@github.com<mailto:notifications@github.com>> wrote:


When I launch the app, it stays within the splash screen for a long time, then it tells me "Internet connection missing, all functionalities are temporarily unavailable."

Time: 2016-06-10 22:00 GMT+8
OS version: 15063.332
Device: Surface Pro 3
City: Shanghai, China

**Comment by taoyouh** [comment]
google.com is not available in mainland China.

**Comment by corradocavalli** [comment]
That's the problem, we ping Google.com<http://Google.com> to ensure connection is effectively functional. What reliable site like Google.com<http://Google.com> is reachable from mainland China?

On 11 Jun 2017, at 06:02, Huang, Zhaoquan <notifications@github.com<mailto:notifications@github.com>> wrote:


google.com<http://google.com> is not available in mainland China.

**Comment by taoyouh** [comment]
Baidu.com is one of the most popular search engines in mainland China. Bing.com is also reliable and reachable.

**Comment by corradocavalli** [comment]
What about microsoft.com<http://microsoft.com>?

On 11 Jun 2017, at 09:41, Huang, Zhaoquan <notifications@github.com<mailto:notifications@github.com>> wrote:


Baidu.com<http://Baidu.com> is one of the most popular search engines in mainland China. Bing.com<http://Bing.com> is also reliable and reachable.

**Comment by taoyouh** [comment]
Microsoft.com is very stable as far as I know.

**Comment by corradocavalli** [comment]
Thanks, we will move to Microsoft.com<http://Microsoft.com> with the next release. Sorry for the inconvenience.

On 11 Jun 2017, at 11:53, Huang, Zhaoquan <notifications@github.com<mailto:notifications@github.com>> wrote:


Microsoft.com<http://Microsoft.com> is very stable as far as I know.

**Comment by corradocavalli** [comment]
Move initial connectivity check from Google.com to Microsoft.com
