### ISSUE TITLE
Info Tile does not move or moves slower

### ISSUE THREAD

**Issue by teguria** [IBVSoftware/CollaBoard-Feedback#241]
.86
Info tile does not move correctly. Plus, I cannot move it with the mouse
![info](https://user-images.githubusercontent.com/19929395/27068997-0c3d699c-5013-11e7-81f3-d689e563815c.png)

**Comment by corradocavalli** [comment]
Can't reproduce it, please show it to me later.

**Comment by teguria** [comment]
One more screenshot related to non-ability to move the info tile
![untitled2](https://user-images.githubusercontent.com/19929395/27069638-ff009454-5015-11e7-8a2d-e5d8ee4b521d.png)

**Comment by corradocavalli** [comment]
send me via s4b the project info/key please...

**Comment by gsantopaolo** [comment]
@teguria  did you sent?

**Comment by gsantopaolo** [comment]
@corradocavalli  my feeling is that this is connected with #247 because of the single tile memory consumption...

**Comment by teguria** [comment]
Works now. Closing
