### ISSUE TITLE
Change Project Owernship - Information for Users

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#243]
When we change the project ownership to a person, that is not looged into the project, this person does not get an information that he is now the owner of the project. 

If the person is logged into the project, then there is a message from CollaBoard itself, that he is now the owner of the project.

**Comment by gsantopaolo** [comment]
@corradocavalli  is this solved now?

**Comment by gsantopaolo** [comment]
@mtg1986  this is a nice feature request. Please add it to the list of feature to be added:
To add a pop up message when you become owner of a project.

**Comment by corradocavalli** [comment]
Michael request is to send an email to the user informing it that it has been designated as the new project owner.

**Comment by gsantopaolo** [comment]
@tamarawasser  please verify with @corradocavalli  if this is already in as functionality otherwise add to the CB FDS and close
