### ISSUE TITLE
Tile Rotation - Application or Project Level?

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#244]
We encountered the following issue: 

1.Create a new project and log-in with multiple devices to the project. 
2.On one device tiles are rotated
3.On the other device in the setting tile rotation is disabled. Now the tiles move back on this device into horizontal order. On the other device they are still rotated. So there is a different behaviour on two devices. 

Suggestion was to have tile rotation setting on project level. May be there are also other ways...

Version: 1.3.91

**Comment by gsantopaolo** [comment]
hello Michael, 
   this is a nice suggestion and I also agree.
Unfortunately this is more a feature request than a bug fix so please keep it for the list of future features and we'll care about it.

thx

**Comment by gsantopaolo** [comment]
same of #300

**Comment by gsantopaolo** [comment]
@tamarawasser  please add to the CB FDS and close
