### ISSUE TITLE
Delete Project - Deleted project still in the "Load project list"

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#246]
1.Create a project with User 1 
2.Login to the project with User 2
3.User 1 deletes project 
4.User 2 clicks on load project and go to "Project you joined" there he sees the project. User 1 sees the project not under "Project you created" 

Tested with project: 2112, 2113 

Version: 1.3.92
Time: 14.062017 15:40
Devices: Surface Pro 4 + DELL Laptop

**Comment by gsantopaolo** [comment]
@mtg1986 @corradocavalli  this was fixed on the, please try it out and close if fixed

thank you

**Comment by mtg1986** [comment]
Tested and it works-->Closed
