### ISSUE TITLE
Sticky note to use too much memory

### ISSUE THREAD

**Issue by gsantopaolo** [IBVSoftware/CollaBoard-Feedback#247]
It seems that when a sticky note is loaded (without stroke or text) it is actually using and enormous amount of memory.
Please investigate, I would like to know witch component is using that much memory.

**Comment by corradocavalli** [comment]
This is indeed a different case, looks like that nesting a FlipView inside a tile generates some touch conflicts with manipulation stuff making the tile not properly reacting to touch movements.

**Comment by gsantopaolo** [comment]
@corradocavalli close if fixed please
