### ISSUE TITLE
Connect and Disconnetc Surface Pro from Charger

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#249]
I am in a CollaBoard project. 

I disconnect my Surface Pro 4 charger and I reconnect. CollBoard shows shortly that the project is synchronized. 

Each time I do that a new user is added to the user overview list. I am logged in with two devices to this project. I disconnected 3 times and 3 new users are added.

Version 1.3.94
19.06.2917 10:11

![image](https://user-images.githubusercontent.com/19570958/27275347-42828cb2-54d7-11e7-8e50-18f48d4f6fba.png)

**Comment by gsantopaolo** [comment]
@mtg1986  i do need project key

**Comment by mtg1986** [comment]
Was not able to reproduce anymore. Therefore Issue closed.
