### ISSUE TITLE
List of Projects (when loading a project) not always up to date

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#250]
When I create a new project or when I delete a project, sometimes these changes are not immediately up to date in the project list. 

Example: 
-Create a new project 
-Close the project 
-Go to load project and then to the list "Projcets you created"
-Sometimes the created project is show sometimes not. 

Sometimes pressing on load project again solves it.
The problem is that it seems to happen randomly, and I cannot reproduce that on command. 

Version 1.3.94
Surface Pro 4 19.06.2017

**Comment by tamarawasser** [comment]
I had the same Problem today. 
Version 1.3.94
HP Spectre 21st of June 2017

Create a new Project: Project Code: 7792 / Project Key: qfu5k
Close the Project
Wanted to reopen it and it's not in the Project list. But when I type Code and key into the field, the Project opens.

**Comment by corradocavalli** [comment]
Is hould be fixed in build 95 out today, please verify and close if ok.

**Comment by tamarawasser** [comment]
It's working now. I can't Close the issue, because I didn't creat it.
