### ISSUE TITLE
Unable to load templates

### ISSUE THREAD

**Issue by teguria** [IBVSoftware/CollaBoard-Feedback#251]
1.3.95
26/06/2017 around 15.20 (during a demo)
27/06/2017 09.44
New Project - Available Project Templates
I don't see all the templates listed here. The circle goes around with its dots but it doesn't happen anything. I waited 2 minutes as I thought maybe it's a connection issue but all the other things work.

**Comment by corradocavalli** [comment]
Looks like an issue on some machines (mine is ok) I've re-added a tweak removed on build 95.
Test it with 96 and close if ok.

On 27 Jun 2017, at 09:44, alead <notifications@github.com<mailto:notifications@github.com>> wrote:


1.3.95
26/06/2017 around 15.5 (during a demo)
27/06/2017 09.44
New Project - Available Project Templates
I don't see all the templates listed here. The circle goes around with its dots but it doesn't happen anything. I waited 2 minutes as I thought maybe it's a connection issue but all the other things work.

**Comment by teguria** [comment]
It works now. Closing
