### ISSUE TITLE
Tile Movement stops when releaseing finger

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#252]
Once it was possible to "throw" a tile with a touch gesture from on angel of the canvas to another. Now movement of the tile stops, as soon as I release the finger. If this is not on purpose, it would be nice to have to old behaviour back.

1.3.96.0
Surface Pro
03.07.2017

Thx
Michael

**Comment by corradocavalli** [comment]
Thanks, sounds like a regression to fix, do you remember if it was ok on previous build 95?

On 3 Jul 2017, at 11:41, Michael Görög <notifications@github.com<mailto:notifications@github.com>> wrote:


Once it was possible to "throw" a tile with a touch gesture from on angel of the canvas to another. Now movement of the tile stops, as soon as I release the finger. If this is not on purpose, it would be nice to have to old behaviour back.

1.3.96.0
Surface Pro
03.07.2017

Thx
Michael

**Comment by mtg1986** [comment]
Hi Corrado, 
very good question.... I cannot tell you when I faced this issue the first time and in which version it was ok and when it changed. Sorry.

**Comment by corradocavalli** [comment]
Fixed in build 97, please try it and close if ok.

**Comment by mtg1986** [comment]
Hi Corrado, 
I downloaded the new version. Tile movement works again as expected. Thanks for that. I encountered another problem (but may be it is not a problem), that the canvas is limited. No zoom in and out is possible anymore. Let me know if I should add this as a new issue or not. 

Tested: 1.3.97.0
Surface Pro 4
17.07.2017

**Comment by corradocavalli** [comment]
You're right, that's a regression I'll fix it asap, you can use Ctrl+Mousewheel in the meantime, Sorry about that.

**Comment by corradocavalli** [comment]
Can't reproduce it again on my machine, can you try again and if happen again send me via mail key/code of a project failing? Thanks.

**Comment by corradocavalli** [comment]
Fixed in build 98, please test it again, thanks.

**Comment by mtg1986** [comment]
Tested on Surface Pro 4. It's working, closing.
