### ISSUE TITLE
Authentification Problem with ADFS

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#253]
A customer is using ADFS Server to authenticate his users for O365. Now he wants to use these accounts to log-in to CollaBoard. When he is doing that he receives the message: 
"At the moment it is not possible to establish a connection with this service. Please check your network connections or try again later" (Translated from German)

Could this be something related to ADFS Server settings? I assume it is not CollaBoard as in the same network, private Microsoft accounts work for authentication.

**Comment by mtg1986** [comment]
May be this could be a solution: 
The support guys reached out and fixed this on the first email.  My ADFS server didn't have forms authentication enabled on the Intranet.  Steps to enable forms authentication are below.

Open ADFS Console.
Click on Authentication Policies.
Click on Edit Global Primary Authentication.
In the Intranet box tick Forms Auhtentication.
Click OK.
Forms Authentication should now be enabled.

**Comment by corradocavalli** [comment]
Ok, let us know if it works now and close if solved.

On 3 Jul 2017, at 13:16, Michael Görög <notifications@github.com<mailto:notifications@github.com>> wrote:


May be this could be a solution:
The support guys reached out and fixed this on the first email.  My ADFS server didn't have forms authentication enabled on the Intranet.  Steps to enable forms authentication are below.

Open ADFS Console.
Click on Authentication Policies.
Click on Edit Global Primary Authentication.
In the Intranet box tick Forms Auhtentication.
Click OK.
Forms Authentication should now be enabled.

**Comment by corradocavalli** [comment]
Also make a note of this issue for further reference, having a sort of publuc knowledge base would be nice.

On 3 Jul 2017, at 13:16, Michael Görög <notifications@github.com<mailto:notifications@github.com>> wrote:


May be this could be a solution:
The support guys reached out and fixed this on the first email.  My ADFS server didn't have forms authentication enabled on the Intranet.  Steps to enable forms authentication are below.

Open ADFS Console.
Click on Authentication Policies.
Click on Edit Global Primary Authentication.
In the Intranet box tick Forms Auhtentication.
Click OK.
Forms Authentication should now be enabled.

**Comment by mtg1986** [comment]
I do not have any news here. The customer did not had time yet to try the proposed solutions. Keep you updated on this.

**Comment by corradocavalli** [comment]
closing because too old, in case of news open a new one.
