### ISSUE TITLE
Rename Machine ID

### ISSUE THREAD

**Issue by teguria** [IBVSoftware/CollaBoard-Feedback#254]
Hi,
when it comes to talk to customers Machine ID might seem like a security leak to disclose (which is not). I'd like to request to rename it to "Unique ID"

**Comment by corradocavalli** [comment]
The fact that is unique is meaningless for the user, what about keeping simple and just call it: Install Id or Install Code?

On 4 Jul 2017, at 17:42, alead <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,
when it comes to talk to customers Machine ID might seem like a security leak to disclose (which is not). I'd like to request to rename it to "Unique ID"

**Comment by teguria** [comment]
Unique to me means that that is the ID associated to the specific app I installed. If you call it Install ID or Install Code might be confusing for the customer. Unique ID means that it's the ID specifically for that installation on that specific device (IHMO).

**Comment by gsantopaolo** [comment]
@mtg1986  Machine ID is definitelly not good. Please find a term that can better fit here thanks

**Comment by gsantopaolo** [comment]
@tamarawasser  please add to the CB FDS and close
