### ISSUE TITLE
3D View in integrated BING Maps

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#255]
In previous versions we had the possibility to do a "Map Search", switch to the landscape mode and use a "two-finger-gesture" to get into the 3D view of BING Maps.
This does not work anymore. Nothing urgent or critical, but it was nice to show how we run external apps in CollaBoard. 
Version. 1.3.96.0
05.07.2017
Surface Hub / Surface Pro

**Comment by corradocavalli** [comment]
We didn't change anything in that area, sounds like a behavior change in Creators Update.
We'll investigate, thanks for the feedback.

On 5 Jul 2017, at 07:17, Michael Görög <notifications@github.com<mailto:notifications@github.com>> wrote:


In previous versions we had the possibility to do a "Map Search", switch to the landscape mode and use a "two-finger-gesture" to get into the 3D view of BING Maps.
This does not work anymore. Nothing urgent or critical, but it was nice to show how we run external apps in CollaBoard.
Version. 1.3.96.0
05.07.2017
Surface Hub / Surface Pro

**Comment by corradocavalli** [comment]
Did several tests but it works for me, can you try again and if problem still persists tell us the exact sequence to reproduce it?
Mine is:
1-Searched Zurich
2-Changed map type and zoomed in
3-Used two fingers to see 3D view of buildings.

**Comment by mtg1986** [comment]
Could not reproduce anymore. Closing.
