### ISSUE TITLE
Radial Menu - Shadow when tapping

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#256]
In the add tiles radial menu. When I add a new sticky note then the part of the radial menu where I can add a sticky note get's darker. When I click like twenty times on it, 20 sticky notes are generated (this is really fast), but I do not get the visual feedback in the radial menu. 
May be only a tiny detail, but we are now very fast in creating new sticky notes :)

Tested: 1.3.98.0
21.07.2017 
Surface Hub & Surface Pro 4

**Comment by corradocavalli** [comment]
Did a small optimization, please try with next release.

**Comment by mtg1986** [comment]
I tested it with the newest version. While tile creating is now very fast, I think I do not see a difference then before. Also if I add fast a sticky note, a library, a grid library, audio etc. the shadow on the radial menu is not always there, when I tap on one of the icons. 

Version: 1.3.100
Surface Pro

**Comment by corradocavalli** [comment]
Can you provide a gif to see the effect?


Da: Michael Görög<mailto:notifications@github.com>
Inviato: giovedì 17 agosto 2017 21:41
A: IBVSoftware/CollaBoard-Feedback<mailto:CollaBoard-Feedback@noreply.github.com>
Cc: Corrado Cavalli<mailto:corrado@outlook.com>; Comment<mailto:comment@noreply.github.com>
Oggetto: Re: [IBVSoftware/CollaBoard-Feedback] Radial Menu - Shadow when tapping (#256)


I tested it with the newest version. While tile creating is now very fast, I think I do not see a difference then before. Also if I add fast a sticky note, a library, a grid library, audio etc. the shadow on the radial menu is not always there, when I tap on one of the icons.

Version: 1.3.100
Surface Pro

**Comment by corradocavalli** [comment]
It should be fixed in build 101 
![radial](https://user-images.githubusercontent.com/5617938/29448775-8564d5d0-83f8-11e7-8adf-864df57ed091.gif)

**Comment by mtg1986** [comment]
Tested with 1.3.106 on Surface Hub
When I create two or more sticky notes with a certain speed the shadow appears only on the first tab. Then it does not show again, so I do not see in the radial menu how many times i tapped on the "Sticky Note" Icon for example.

**Comment by corradocavalli** [comment]
@mtg1986 Can you attach a screenshot and highlight the "shadow" you're talking about, I don't understand the issue you're pointing out.
Thanks

**Comment by mtg1986** [comment]
@corradocavalli : Please see here a screenshot where I marked the shadow. It appears when clicking or hovering over the icon. 
![screenshot 1 _li](https://user-images.githubusercontent.com/19570958/30197245-e1b62590-9466-11e7-85db-5345e8bf8041.jpg)

**Comment by corradocavalli** [comment]
Fixed in v107, please @mtg1986 verify and close it if ok.

**Comment by mtg1986** [comment]
Tested with v107 and shadow does now appear on every click or tap. Thanks and closing.
