### ISSUE TITLE
Youtube Video - On different devices

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#258]
1.Search Youtube Video
2.Add video on Surface Hub 
3.The others see that there is a video tile, but it keeps the status "loading". 
4.Ink on the video, save ink
5.Ink is transferred to all the Youtube-Tiles on the other devices, but the video cannot be played on this devices. It still says "Please wait". This status remains and seems not to change anymore.

Version 1.3.98
21.07.2017
Surface Hub, Surface Pro, China Tablet

![image](https://user-images.githubusercontent.com/19570958/28466452-c3fe678e-6e2c-11e7-9cc6-28e957d3d19e.png)

**Comment by corradocavalli** [comment]
Does it happen all times on all devices, we do nothing but play the youtube link, look like, *once again* a poor network connection.

**Comment by mtg1986** [comment]
We could reproduce it using a different network. On the device where you drop the video everything is fine. On the other devices the video says "Please wait" also after a few minutes and nothing seems to happen.

Network Speed: 
![image](https://user-images.githubusercontent.com/19570958/28467043-cbaa3e3e-6e2e-11e7-93be-b2d43ddcedc3.png)

**Comment by corradocavalli** [comment]
What happens when you reload the same project, is the same tile ok?

**Comment by corradocavalli** [comment]
Added a fix, please try with new build and provide us feedback.
