### ISSUE TITLE
Available project list not available

### ISSUE THREAD

**Issue by teguria** [IBVSoftware/CollaBoard-Feedback#259]
HP Spectre
CB: 1.3.98

Everytime I launch CB on my device, I go to New Projects, scroll to Available Projects but the page loads without loading any project template

**Comment by corradocavalli** [comment]
Can you try with another machine and verify if list appears?

**Comment by teguria** [comment]
@corradocavalli it works on all the other machines, it's just my Spectre (don't know why)

**Comment by teguria** [comment]
it works now. Closing
