### ISSUE TITLE
Dragging a file into a wrong position (library)

### ISSUE THREAD

**Issue by teguria** [IBVSoftware/CollaBoard-Feedback#260]
![dragging](https://user-images.githubusercontent.com/19929395/28609113-93ee4888-71e3-11e7-8236-19467dbd21c4.jpg)
HP Spectre 360
CB 1.3.98

Project Code: 2228
Project Key: 5otgf
Project description: test

ibv-collaboard:open?code=2228&key=5otgf

When I move a file (youtube video) ithe borders become blue while the library is far away from that position

**Comment by corradocavalli** [comment]
Tried with the same project, please give us a reproducible scenario otherwise can't do nothing but close the issue.

**Comment by teguria** [comment]
Can't reproduce. Should we test it again next week?
