### ISSUE TITLE
Multiple User Icons after reloading the project

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#261]
1.Work on a project
2.Send Surface Pro to sleep mode
3.Continue working on Surface Pro
4.-->Each time I do that a new user icon appears. Please see screenshot: 

![image](https://user-images.githubusercontent.com/19570958/29021534-2010641e-7b66-11e7-8a08-8467a8328d6d.png)

Tested with: 
Surface Pro 
1.3.94.0 
07.08.2017

Project: 
Project Code: 8509
Project Key: s6lqh

**Comment by corradocavalli** [comment]
Tried same scenario but can't reproduce it, if you have one, please follow up with the exact repro sequence.
Thanks

**Comment by mtg1986** [comment]
Cannot reproduce anymore. Closing
