### ISSUE TITLE
Tile to full screen - header ux redesign

### ISSUE THREAD

**Issue by gsantopaolo** [IBVSoftware/CollaBoard-Feedback#268]
When on full screen header needs to be redesigned to guarantee a seamless ux.
Header should become a floating tile

**Comment by corradocavalli** [comment]
On full screen header bar no longer exist and control is via a floating bar as requested
![image](https://user-images.githubusercontent.com/5617938/29214745-c4f1fb7e-7ea8-11e7-8711-f46c76580679.png)

**Comment by gsantopaolo** [comment]
@corradocavalli  please ping me to discuss about the floating bar design, thanks! :)
