### ISSUE TITLE
Image Tile - Full Screen Different Background Color

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#271]
When we make an Image full screen the background color of the image changes. 

Tested on Surface Hub and other devices. 

Version 1.3.99.0 
Used Image: 
![collaboard_logo-blue](https://user-images.githubusercontent.com/19570958/29266172-0f0fba4c-80e4-11e7-8e9d-af1fef74a274.png)

See image for further explanation: 

![whiteboard_2017-08-14_112713](https://user-images.githubusercontent.com/19570958/29266206-3827d216-80e4-11e7-8162-7adfb4445184.png)

**Comment by corradocavalli** [comment]
Any feedback on this?

**Comment by mtg1986** [comment]
Hi Corrado, if all image viewer are doing this, then I think it is ok if we do it also. Therefore I am closing the issue.
