### ISSUE TITLE
Sticky Note Full Screen - Stick goes not full screen

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#272]
1.Create new sticky note 
2.Make sticky note Full screen 

Then the sticky note moves to the upper left corner and is not full screen. I can move the toolbar outside of the sticky note.

![whiteboard_2017-08-14_114127](https://user-images.githubusercontent.com/19570958/29266600-c01a5f12-80e5-11e7-90c9-b05fa6310617.png)

Tested: 1.3.99
Surface Hub

**Comment by corradocavalli** [comment]
This sounds weird, it is reproducible? It happens on all machines? (pc vs hub)

On 14 Aug 2017, at 11:44, Michael Görög <notifications@github.com<mailto:notifications@github.com>> wrote:


1.Create new sticky note
2.Make sticky note Full screen

Then the sticky note moves to the upper left corner and is not full screen. I can move the toolbar outside of the sticky note.

[whiteboard_2017-08-14_114127]<https://user-images.githubusercontent.com/19570958/29266600-c01a5f12-80e5-11e7-90c9-b05fa6310617.png>

Tested: 1.3.99
Surface Hub

**Comment by mtg1986** [comment]
I am sorry, it was reproducable on the Hub, but after restarting CollaBoard, we are not able to get the same error again.
Closing it, and re-opening, when we are able to reproduce.
