### ISSUE TITLE
Tile Connection Stays when closing project and when opening a new project

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#273]
1.Connect some tiles 
2.Close Project
3.Tile connection is still there
4.Start a new project 
4.Tile connections from the old project are still there, but not the tiles.

Tested: Surface Hub
Version 1.3.99

![whiteboard_2017-08-14_115340](https://user-images.githubusercontent.com/19570958/29267068-6b4f02ce-80e7-11e7-9976-9ccae0f211bb.png)

![whiteboard_2017-08-14_115511](https://user-images.githubusercontent.com/19570958/29267094-860524fe-80e7-11e7-8cb5-b8518c18f312.png)

**Comment by corradocavalli** [comment]
Yes, probably a last minute regression, very easy to fix.

On 14 Aug 2017, at 11:56, Michael Görög <notifications@github.com<mailto:notifications@github.com>> wrote:


1.Connect some tiles
2.Close Project
3.Tile connection is still there
4.Start a new project
4.Tile connections from the old project are still there, but not the tiles.

Tested: Surface Hub
Version 1.3.99

[whiteboard_2017-08-14_115340]<https://user-images.githubusercontent.com/19570958/29267068-6b4f02ce-80e7-11e7-9976-9ccae0f211bb.png>

[whiteboard_2017-08-14_115511]<https://user-images.githubusercontent.com/19570958/29267094-860524fe-80e7-11e7-8cb5-b8518c18f312.png>

**Comment by corradocavalli** [comment]
Fixed in v100.

**Comment by mtg1986** [comment]
Confirm fix
