### ISSUE TITLE
Upload PDF - PANDA

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#275]
1.Create New Project on Surface Hub
2. 3 other devices login to the same project
3.Upload from personal device PDF
4.Try Voice Command: "CollaBoard Add Sticky Note" -->Answer is "Cant do this right now"
5.Create Library on the Hub 
5.-->We get a Panda (only on Hub)
"It seems that there is a problem. We will investiage it...." 

Tested: 
Surface Hub + Personal Devices
Version: 1.3.99.0
14.08.2017
15:55

**Comment by corradocavalli** [comment]
Is ir reproducible? Are you using *wired* connection for all devices?

On 14 Aug 2017, at 15:57, Michael Görög <notifications@github.com<mailto:notifications@github.com>> wrote:


1.Create New Project on Surface Hub
2. 3 other devices login to the same project
3.Upload from personal device PDF
4.Try Voice Command: "CollaBoard Add Sticky Note" -->Answer is "Cant do this right now"
5.Create Library on the Hub
5.-->We get a Panda (only on Hub)
"It seems that there is a problem. We will investiage it...."

Tested:
Surface Hub + Personal Devices
Version: 1.3.99.0
14.08.2017
15:55

**Comment by mtg1986** [comment]
We are using the W-Lan over the Aeoronet. It seems to bee that the voice commands have something to do with the issue as they are not working. After CollaBoard says "I am sorry I can't do this right now" and then adding a library it crashes.

**Comment by corradocavalli** [comment]
Voice commands were are now back to work with build 100, tried several times this scenario but can't reproduce the Panda. Please retry again with new build and provide feedback.

**Comment by mtg1986** [comment]
Voice commands are working with 1.3.100
Tested on Surface Pro
