### ISSUE TITLE
Apply Button in Ink Toolbar

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#277]
Please try to find a better solution than the apply button in the Ink Toolbar. It is nice that we can now select Color and stroke size.

**Comment by corradocavalli** [comment]
Apply button has been remove in v100, and changes are now applied immediately.
As requested by Gian if you use fingers instead of a pen for attributes selection, attributes aren't reset as in v99 but simply not applied, this means that a bit of explanation must be provided to users otherwise it could be seen as a bug where selection isn't working.

**Comment by mtg1986** [comment]
At the moment the ink toolbar does not disappear after I have selected something. Also when I start Inking the toolbar does  not disappear either. I can ink over the toolbar and the ink stays behind the toolbar. 

If I select Color or stroke size with finger the attributes are applied. 

V 1.3.100
Surface Pro

![ink_toolbar_usage](https://user-images.githubusercontent.com/19570958/29430102-67cdaf3e-8393-11e7-81bb-a55aec03619f.gif)

**Comment by corradocavalli** [comment]
Is not a problem to close it on selection but this would revert back to the old annoying behavior where you have to tap twice if you want to change the color and then pen size, is this ok?
Finger selection works on device without multipen support, it doesn’t on Surface Hub.


Da: Michael Görög<mailto:notifications@github.com>
Inviato: giovedì 17 agosto 2017 21:32
A: IBVSoftware/CollaBoard-Feedback<mailto:CollaBoard-Feedback@noreply.github.com>
Cc: Corrado Cavalli<mailto:corrado@outlook.com>; Comment<mailto:comment@noreply.github.com>
Oggetto: Re: [IBVSoftware/CollaBoard-Feedback] Apply Button in Ink Toolbar (#277)


At the moment the ink toolbar does not disappear after I have selected something. Also when I start Inking the toolbar does not disappear either. I can ink over the toolbar and the ink stays behind the toolbar.

If I select Color or stroke size with finger the attributes are applied.

V 1.3.100
Surface Pro

[ink_toolbar_usage]<https://user-images.githubusercontent.com/19570958/29430102-67cdaf3e-8393-11e7-81bb-a55aec03619f.gif>

**Comment by corradocavalli** [comment]
Added close on selection and pen size changed on v101, behavior is now exactly the same as old toolbar.
