### ISSUE TITLE
New Ink Toolbar - Multiuser missing

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#278]
At the moment only one user can use the new ink toolbar. This means we create two sticky notes and on each sticky note one user wants to select a Color and stroke size. At the moment it is not possible that two users are doing this simultaniously. 

While editing tile connection, like changing Color, this can be done by two users at the same time. 

Version. 1.3.99
16.08.2017 
Surface Hub

**Comment by corradocavalli** [comment]
Can you clarify it better? You mean multi users on the same tile can’t interact with tile’s ink toolbar at the same time or else?


Da: Michael Görög<mailto:notifications@github.com>
Inviato: mercoledì 16 agosto 2017 09:22
A: IBVSoftware/CollaBoard-Feedback<mailto:CollaBoard-Feedback@noreply.github.com>
Cc: Subscribed<mailto:subscribed@noreply.github.com>
Oggetto: [IBVSoftware/CollaBoard-Feedback] New Ink Toolbar - Multiuser missing (#278)


At the moment only one user can use the new ink toolbar. This means we create two sticky notes and on each sticky note one user wants to select a Color and stroke size. At the moment it is not possible that two users are doing this simultaniously.

While editing tile connection, like changing Color, this can be done by two users at the same time.

Version. 1.3.99
16.08.2017
Surface Hub

**Comment by mtg1986** [comment]
What I mean is that on two different tiles the ink toolbar can not be used simultaniously.

Hope it will get a bit clearer with this scenario: 

Scenario: 
Person 1: Create a sticky note
Person 2: Upload a picture
Person 1 and 2 wants to choose simultaniously on the same device, Person 1 on the sticky note and Person 2 on the picture, a Color for their pen. 
At the moment the behaviour is like that that only the first how clicks on the ink icon can do it. If Person 1 is choosing the ink (and is not finsihed yet) and Person 2 is clicking on the ink icon, then the ink toolbar for Person 1 disappears (altough he has not finished the selection) and appears for person 2.

**Comment by gsantopaolo** [comment]
@mtg1986  @corradocavalli  is this still an issue or not?

**Comment by corradocavalli** [comment]
The behavior has technically been changed to fit the request, waiting for final ok from @mtg1986.

**Comment by gsantopaolo** [comment]
I saw what @mtg1986 is talking about and definetelly not good.
We need to test and understand if we are doing something wrong or is it a limit of the hardware / operating system / api set

**Comment by corradocavalli** [comment]
@gsantopaolo With initial implementation it was basically not possible to have more than one ink panel open at the same time, this was the issue raised by Michael, and, BTW, this was the behavior we always had with MS InkToolbar and got unnoticed for month.
New implementation removes the limit and every user can interact with the tool panel independently (see image) so I don't understand what exactly is the issue you're mentioning now, can you elaborate please?
![image](https://user-images.githubusercontent.com/5617938/30197020-3a72535e-9465-11e7-94a0-e23507b7fc44.png)
