### ISSUE TITLE
Video Recording - Video is not recorded

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#280]
There seems to be a problem with Video recording. 
Version: 1.3.94.0 
Device: Surface Po 

(I did not tested yet how it is in Version 1.3.99)

1.Record Video
2.Recorded Video is not saved, there appears a tile descirbing that file format is not valid. 
3.If I try to record again then I get a panda. 
For repo have a look at the GIF: 

![record_video](https://user-images.githubusercontent.com/19570958/29407722-9be0177e-8345-11e7-98e8-4af3d61359f0.gif)

**Comment by corradocavalli** [comment]
Can you try with another device? Tried with my machines and I have no problems with recordings.


Da: Michael Görög<mailto:notifications@github.com>
Inviato: giovedì 17 agosto 2017 12:15
A: IBVSoftware/CollaBoard-Feedback<mailto:CollaBoard-Feedback@noreply.github.com>
Cc: Subscribed<mailto:subscribed@noreply.github.com>
Oggetto: [IBVSoftware/CollaBoard-Feedback] Video Recording - Video is not recorded (#280)


There seems to be a problem with Video recording.
Version: 1.3.94.0
Device: Surface Po

(I did not tested yet how it is in Version 1.3.99)

1.Record Video
2.Recorded Video is not saved, there appears a tile descirbing that file format is not valid.
3.If I try to record again then I get a panda.
For repo have a look at the GIF:

[record_video]<https://user-images.githubusercontent.com/19570958/29407722-9be0177e-8345-11e7-98e8-4af3d61359f0.gif>

**Comment by mtg1986** [comment]
We tried with some other machines . Seems to be a Surface Pro related problem. I will do some other tests with the camera. Otherwise we can have a look at it during the testing week.

**Comment by corradocavalli** [comment]
Try to compare camera settings with one on the working machine.

**Comment by gsantopaolo** [comment]
guys, even if this happens on a single device is something that we have to investigate and fix.
thanks
-g

**Comment by corradocavalli** [comment]
During last testing week i tried: Surface Pro, both Hubs, Surface Pro 3 and Pascal notebook, everything was fine, need to find a device where it happen, @mtg1986 can you try to find it?

**Comment by mtg1986** [comment]
@corradocavalli : I happens only on my Surface Pro (the newest one, released this spring). When I click on recording the camera seems to be freezed immediately (taking images works fine). And when ending the recording the Panda appears. So we can easily reproduce next week. 

It seems to be a CollaBoard specific problem as recording a video in OneNote works. 
CollaBoard is allowed to use the camera (regarding data protection settings). 
Anything else I should check?

**Comment by corradocavalli** [comment]
That's enough for now, let's check it next week.
Thanks

On 10 Sep 2017, at 08:55, Michael Görög <notifications@github.com<mailto:notifications@github.com>> wrote:


@corradocavalli<https://github.com/corradocavalli> : I happens only on my Surface Pro (the newest one, released this spring). When I click on recording the camera seems to be freezed immediately (taking images works fine). And when ending the recording the Panda appears. So we can easily reproduce next week.

It seems to be a CollaBoard specific problem as recording a video in OneNote works.
CollaBoard is allowed to use the camera (regarding data protection settings).
Anything else I should check?

**Comment by gsantopaolo** [comment]
@corradocavalli close if fixed please
