### ISSUE TITLE
[Proposal] New Sticky Notes Background Colors

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#281]
What do you think about having some different Colors for the sticky notes background?
We also thought about how to order them. 

![image](https://user-images.githubusercontent.com/19570958/29431260-96141f28-8397-11e7-8993-9ce8b918a864.png)

**Comment by corradocavalli** [comment]
If i well remember someone asked for white also.
Just decide the colors and ordering and provide us the list.
Same for connection colors, the one we have now are just placeholders.


On 17 Aug 2017, at 22:02, Michael Görög <notifications@github.com<mailto:notifications@github.com>> wrote:


What do you think about having some different Colors for the sticky notes background?
We also thought about how to order them.

[image]<https://user-images.githubusercontent.com/19570958/29431260-96141f28-8397-11e7-8993-9ce8b918a864.png>

**Comment by mtg1986** [comment]
Here an overview about the new Colors: 

[Color Codes Collaboard.pdf](https://github.com/IBVSoftware/CollaBoard-Feedback/files/1245508/Color.Codes.Collaboard.pdf)
