### ISSUE TITLE
Drag & Drop Images - Message

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#282]
When I Drag and Drop Images the Message "Closing Project appears". With Video it is not the case.
Project is not closed and I can contiue working
Version: 1.3.100
Surface Pro
![closing_project_message](https://user-images.githubusercontent.com/19570958/29432986-c8ea680c-839d-11e7-91ff-d5e6f0e525d6.gif)

**Comment by corradocavalli** [comment]
Can't reproduce, can you provide a repro sequence?

**Comment by corradocavalli** [comment]
Fixed in v 102
