### ISSUE TITLE
Create Multiple Grid Libraries

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#283]
When I create multiple sticky notes then they are arranged differntly as if I do the same with Grid libraries and libraries. 
With sticky notes I can see very good that I added a new one With grid libraries I do not see it, as the new one is covering the existing one completely 

Version 1.3.100 
Surface Hub and Surface Pro 

![create_multiple_grid_libraries](https://user-images.githubusercontent.com/19570958/29451447-ef9f4462-8402-11e7-9f6d-443e69ee1252.gif)

**Comment by corradocavalli** [comment]
Fixed in v101
