### ISSUE TITLE
Loading Project - Error 

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#284]
1.Load Project (2278, 3kt9s)
2.Not all the time but like 50% of the attemps we get the following panda: 

![image](https://user-images.githubusercontent.com/19570958/29451780-31aa89ec-8404-11e7-8977-6d3ab6015b8a.png)

3.When I click ok, the canvas is only as large as the screen is and I cannot move around.
-->I need to restart CollaBoard
![error_on-loading_project](https://user-images.githubusercontent.com/19570958/29451894-99eb7fa2-8404-11e7-9f82-fa01a7490666.gif)

Version 1.3.100
Tested on Hub and Surface Pro 
-->Behaviour is not always the same.

**Comment by corradocavalli** [comment]
Please send me key and code of the project.
Thanks

On 18 Aug 2017, at 11:01, Michael Görög <notifications@github.com<mailto:notifications@github.com>> wrote:


1.Load Project
2.Not all the time but like 50% of the attemps we get the following panda:

[image]<https://user-images.githubusercontent.com/19570958/29451780-31aa89ec-8404-11e7-8977-6d3ab6015b8a.png>

3.When I click ok, the canvas is only as large as the screen is and I cannot move around.
-->I need to restart CollaBoard
[error_on-loading_project]<https://user-images.githubusercontent.com/19570958/29451894-99eb7fa2-8404-11e7-9f82-fa01a7490666.gif>

**Comment by corradocavalli** [comment]
Sorry, didn't notice it is was already mentioned...

**Comment by corradocavalli** [comment]
Can't reproduce it on my machines, can you try with another machine to check if it related to your computer?

**Comment by mtg1986** [comment]
Tired now again as well, and it did work. 
We encountered the issue on Surface Pro, Surface Hub and Dell Laptop.

**Comment by mtg1986** [comment]
Not reproducable and did not happend again. Closing.
