### ISSUE TITLE
User Icons in Project

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#287]
1.Create new project on Hub (team edition) -->One User Icon - correct
2.Loing to project on Hub (personal edition) --> Two Use Icon - correct 
3.Loing from China Tablet (personal edition) --> Sees only her user icon. 
4.Login from Surface Pro (China Table sees now her user icon and the one from the Surface Pro)
5.Login over ThinkPad Lenove Laptop (sees all users, but the one from Surface Pro is missing the initials in the User Icon).

**Comment by corradocavalli** [comment]
Think this is related to this https://github.com/IBVSoftware/CollaBoard-Feedback/issues/306
