### ISSUE TITLE
Sticky Note Full Screen - Background Color

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#290]
1.Make Sticky Note Full Screen 
2.Change Background Color
3.The menubar is at the bottom of the sticky note. When I want to change background Color, the menu is showed down instead uf up. When choosing ink Color and stroke size the menu pops up into the wrong direction. 

![fullscreenbackgroundcolor](https://user-images.githubusercontent.com/19570958/29898740-d03c4aae-8de7-11e7-8794-9bc38e7dfd6c.gif)

**Comment by corradocavalli** [comment]
On what device the problem appears?
I've fixed (and tested) this issue raised during tests so I need to know if it might device dependent.

On 30 Aug 2017, at 19:01, Michael Görög <notifications@github.com<mailto:notifications@github.com>> wrote:


1.Make Sticky Note Full Screen
2.Change Background Color
3.The menubar is at the bottom of the sticky note. When I want to change background Color, the menu is showed down instead uf up. When choosing ink Color and stroke size the menu pops up into the wrong direction.

[fullscreenbackgroundcolor]<https://user-images.githubusercontent.com/19570958/29898740-d03c4aae-8de7-11e7-8794-9bc38e7dfd6c.gif>

**Comment by corradocavalli** [comment]
Regression fixed in v107. @mtg1986 please verify and close.

**Comment by mtg1986** [comment]
Works now as expected. Closing. 
Tested v107
