### ISSUE TITLE
Bugs to be tested on Sruface Hub 84''

### ISSUE THREAD

**Issue by gsantopaolo** [IBVSoftware/CollaBoard-Feedback#291]
Hi, 
   unfortunately i noticed some bad behaviors on 84' device. 
Please arrange a test on a 84' ASAP 

thank you
-g

**Comment by corradocavalli** [comment]
Can you elaborate more about what kind of bad behaviors you found.
How can we get a 84" device for testing?

On 31 Aug 2017, at 10:04, Gian Paolo Santopaolo <notifications@github.com<mailto:notifications@github.com>> wrote:


Assigned #291<https://github.com/IBVSoftware/CollaBoard-Feedback/issues/291> to @corradocavalli<https://github.com/corradocavalli>.

**Comment by gsantopaolo** [comment]
@mtg1986  why did you closed this? 
This must be tested on a 84' inches as well as lots of other things. Please report to me before closing my bugs thanks

**Comment by mtg1986** [comment]
@gsantopaolo : Sorry this was a mistake. I am trying to organize the room with the 84'' at ALSO or MS CH.

**Comment by gsantopaolo** [comment]
@mtg1986  Thank you!

**Comment by tamarawasser** [comment]
@gsantopaolo what is the issue here? I'm in front of a 84" with v1.4.7

**Comment by tamarawasser** [comment]
@gsantopaolo Gian, does it make sense that I go to ALSO or MS to test these bugs on a Surface Hub 84?
