### ISSUE TITLE
List: Load and existing projects not complete

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#292]
1.Start CollaBoard
2.Click on Load Project 
3. The list does not all the time show all the projects I created or joined. It seems not to load all the data. When doing it several times I get randomly different list. This means that the first project I see has sometimes the number 5000 then I see all up to with number of 7000 and so on. 

04.09.2017
1.3.106 
Desktop PC

**Comment by gsantopaolo** [comment]
this is something that needs to be reproduced on testing week.
Please report to me before closing this

thanks
-g

**Comment by corradocavalli** [comment]
I have refactored the loading sequence in v107. @mtg1986 can you verify if problem is solved? (can't reproduce on my machines)

**Comment by mtg1986** [comment]
Tested with 1.3.110 on Surface Pro and Desktop PC. Is working now, therefore I am closing this bug.
