### ISSUE TITLE
Surface Hub Pens properties not working

### ISSUE THREAD

**Issue by gsantopaolo** [IBVSoftware/CollaBoard-Feedback#293]
when selecting different pen's properties on surface hub these are not stored correctly

**Comment by corradocavalli** [comment]
What do you exactly mean? Is the pen selection that is not applied correctly or selection ink panel doesn't keep pen's properties?

On 4 Sep 2017, at 09:05, Gian Paolo Santopaolo <notifications@github.com<mailto:notifications@github.com>> wrote:


Assigned #293<https://github.com/IBVSoftware/CollaBoard-Feedback/issues/293> to @corradocavalli<https://github.com/corradocavalli>.

**Comment by gsantopaolo** [comment]
1. When selection some ink proprieties from the panel they work the first time user ink with the pen.
2. Then another user ink
3. If the previous user inks again their ink property (selected on step 1) aren't applied

**Comment by corradocavalli** [comment]
We did a lot of test during latest testing week, code looks ok to me,
Added debug log to test it again next week on Surface Hub

**Comment by gsantopaolo** [comment]
I got this behavior the very first time I tried it and also every single other time. 
We have to test again on an hub btw i believe is reproducible

**Comment by corradocavalli** [comment]
Yes, I will fix it next week.

**Comment by corradocavalli** [comment]
Fixed in v109.
