### ISSUE TITLE
CollaBoard Help - Panda

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#296]
-Start a project  
-Go to Help
-Open Help
-Drag and Drop a video
-Touch The video 
-->Then we get a panda "The answer is to reload a project". Click ok to proceed. 

Issue happens only on Hub 
Version: 1.3.106

**Comment by corradocavalli** [comment]
On Hub only? (really weird) can you check with other touch devices?
 It happens with any video?

On 4 Sep 2017, at 09:39, Michael Görög <notifications@github.com<mailto:notifications@github.com>> wrote:


-Start a project
-Go to Help
-Open Help
-Drag and Drop a video
-Touch The video
-->Then we get a panda "The answer is to reload a project". Click ok to proceed.

Issue happens only on Hub
Version: 1.3.106

**Comment by mtg1986** [comment]
It happens only on the Hub. On Surface Pro and on HP Spectre and the other devices it was working.

**Comment by corradocavalli** [comment]
It should be fixed in v107, @mtg1986 please confirm when version will be available
