### ISSUE TITLE
Video Length now 40 sec

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#298]
In previos version we could record 60 Sec of videos. 
Now we can only record 40 seconds. 
Can we change that back?

**Comment by gsantopaolo** [comment]
@tamarawasser can you please test and close or label as bug and adding to a dev? Thx

**Comment by tamarawasser** [comment]
@corradocavalli please can you change to 60 seconds recording?

**Comment by tamarawasser** [comment]
@corradocavalli can you Change to 60 seconds please? It's still 40.

**Comment by corradocavalli** [comment]
We have moved to 40 otherwise video size would exceed 15 MB...
