### ISSUE TITLE
Canvas is only the screen size

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#299]
1.Create a new project
2.Close the Info tile NOT
2.Add an PNG File (infographic)
3.Canvas shrinks to screen size and we cannot navigate around the canvas anymore. The borders are the screen. 
4.When we close the Info tile the canvas is there again. 
![how-to-gamestor_21284426_37719dff21111ed77a7d5b87e5a689d3c91ea600](https://user-images.githubusercontent.com/19570958/30029723-a9a11b4e-918a-11e7-818c-997db9ac8fed.png)

When we create a new project the Minimap first appears when we close the info tile.

**Comment by corradocavalli** [comment]
Please send me via mail the png and the key/code of the project you used for this case.
Thanks

On 4 Sep 2017, at 10:04, Michael Görög <notifications@github.com<mailto:notifications@github.com>> wrote:


1.Create a new project
2.Close the Info tile NOT
2.Add an PNG File (infographic)
3.Canvas shrinks to screen size and we cannot navigate around the canvas anymore. The borders are the screen.
4.When we close the Info tile the canvas is there again.
[how-to-gamestor_21284426_37719dff21111ed77a7d5b87e5a689d3c91ea600]<https://user-images.githubusercontent.com/19570958/30029723-a9a11b4e-918a-11e7-818c-997db9ac8fed.png>

When we create a new project the Minimap first appears when we close the info tile.

**Comment by mtg1986** [comment]
We also tried with other files and the behavior is the same. It only happens when adding files via "Load File". When creating a Sticky Note, this does not happen and the canvas stays zoomable

**Comment by corradocavalli** [comment]
Fixed in v107.

**Comment by mtg1986** [comment]
Tested with v107. Issue is solved.
