### ISSUE TITLE
Info Tile

### ISSUE THREAD

**Issue by gsantopaolo** [IBVSoftware/CollaBoard-Feedback#304]
On the Hub (we have to check if is same o other devices) machine id is shown only when a user has an active license.
Please show the machine id all time as we need this to identify the device in the back end

thanks

**Comment by corradocavalli** [comment]
Checked right now simulating Hub config and Machine Id is always displayed. 
@mtg1986 can you verify this on a real device?

**Comment by mtg1986** [comment]
Tested on Surface Hub. 
-Unregistered
-Closed the app
-Restarted the App 

-When you click on Info, you see first the second silde of the tile, where to enter the key. Then you need to swipe right and Machine ID is displayed. I think this behaviour is ok. Therefore i am closing this issue.
