### ISSUE TITLE
Drop help video on a grid library causes panda and app to reload

### ISSUE THREAD

**Issue by gsantopaolo** [IBVSoftware/CollaBoard-Feedback#305]
Open a project,
On help videos
Drop an help video on the canvas
Create a grid library
Drop the help video on the grid library
You got a panda
App needs to reload

@corradocavalli  non interactive tiles should not interact with interactive tiles, in this case help videos can't be dropped on a container but please check the described rule for all our non interactive tiles when interacting with interactive tiles

**Comment by corradocavalli** [comment]
Fixed in 107, tested also with all non interactive tiles, all were ok.

**Comment by gsantopaolo** [comment]
thx, @mtg1986  please note to test this as well so we can close it
