### ISSUE TITLE
Register license popup showing after added a valid key

### ISSUE THREAD

**Issue by gsantopaolo** [IBVSoftware/CollaBoard-Feedback#307]
After entered a valid license key app is still showing the pop up blocking the ui for xx seconds 
And the pop up is counting contrariwise  without ending!!!!

![image](https://user-images.githubusercontent.com/9937149/30035493-159ec114-91ab-11e7-975b-516115b160fd.png)

![image](https://user-images.githubusercontent.com/9937149/30035496-205fd4c6-91ab-11e7-8cf2-692bcbab9455.png)

**Comment by corradocavalli** [comment]
This happended once in the past, tried tons of times w/o being able to replicate.
Asked tester to provide a scenario but got no answer, if you have a reproducible scenario it would help a lot.

On 4 Sep 2017, at 13:57, Gian Paolo Santopaolo <notifications@github.com<mailto:notifications@github.com>> wrote:


Assigned #307<https://github.com/IBVSoftware/CollaBoard-Feedback/issues/307> to @corradocavalli<https://github.com/corradocavalli>.

**Comment by gsantopaolo** [comment]
@corradocavalli before ne next release on the testing week this need to be reproduced and fixed :)

**Comment by corradocavalli** [comment]
It might be a race condition, added a flag guard but definitively need more testing.

**Comment by gsantopaolo** [comment]
@mtg1986  please note that this is something we need to solve during next testing session
