### ISSUE TITLE
Red error message when writing on PDF w/ multiple pages (v134)

### ISSUE THREAD

**Issue by teguria** [IBVSoftware/CollaBoard-Feedback#31]
I started a project -> created some sticky notes and started drawing
I opened a picture and started drawing on it. I opened a 3-pages PDF file, started drawing on page 2 and page 3. I switched back from page 3 to page 2 and and 1 and then I got the red error message

Date and Time: Friday the 4th 08.39 a.m.
Device: HP Spectre X360
Location: Genoa
OS: Windows 10 Enteprise 1607 (build 14393.351)

**Comment by teguria** [comment]
The error seems to be related only when I use the highlighter but not easy to repro. Also, when I got the red error message, everything was closed (as expected) but I got a welcome screen mixed up with my project I was working on before the crash (in attach)
![welcome screen after red message](https://cloud.githubusercontent.com/assets/19929395/19998509/8039a3fa-a26d-11e6-915f-9003265f2da9.jpg)

**Comment by teguria** [comment]
Unable to repro. Tried with a PDF with 27 pages, inked with different stylus but doesn't happen anymore. For your reference:
Code: 1008
Key: dezec

**Comment by corradocavalli** [comment]
Fixed in v135, please test it again when new version is out and reopen is still there,

**Comment by teguria** [comment]
@corradocavalli please also check the picture I uploaded here. It's another issue so maybe I can open another one for that.
