### ISSUE TITLE
Tiles in Project are not loaded on all devices

### ISSUE THREAD

**Issue by tamarawasser** [IBVSoftware/CollaBoard-Feedback#310]
5th of September - 10:30am
Project: 8963
Key: ueh60

Svenja created the project on the Cube i8-L Tablet
Looks like this: 
![organigramm ibv](https://user-images.githubusercontent.com/25382402/30052477-df404054-9225-11e7-9b20-f1faf6619f21.PNG)
She worked on this Project on the Cube i8-L Tablet for a while, than closed the project and wanted to continue working on the project on her Dell Inspiron 1750. 
Started CollaBoard on Dell Inspiron 1750
Opened Project 
Project looks like this:
![unbenannt](https://user-images.githubusercontent.com/25382402/30052590-385be206-9226-11e7-8e46-f268ce9fbca8.JPG)
When I open the Project on my HP Spectre, it looks like the second picture too. Project is not loading all tiles.

**Comment by corradocavalli** [comment]
Ok, please don't use this project until i got a chance to inspect it.
Thanks.

On 5 Sep 2017, at 04:43, tamarawasser <notifications@github.com<mailto:notifications@github.com>> wrote:


5th of September - 10:30am
Project: 8963
Key: ueh60

Svenja created the project on the Cube i8-L Tablet
Looks like this:
[organigramm ibv]<https://user-images.githubusercontent.com/25382402/30052477-df404054-9225-11e7-9b20-f1faf6619f21.PNG>
She worked on this Project on the Cube i8-L Tablet for a while, than closed the project and wanted to continue working on the project on her Dell Inspiron 1750.
Started CollaBoard on Dell Inspiron 1750
Opened Project
Project looks like this:
[unbenannt]<https://user-images.githubusercontent.com/25382402/30052590-385be206-9226-11e7-8e46-f268ce9fbca8.JPG>
When I open the Project on my HP Spectre, it looks like the second picture too. Project is not loading all tiles.

**Comment by tamarawasser** [comment]
Svenja worked on it in the morning again. It looks a bit different now. But she stopped working on it right now.

**Comment by corradocavalli** [comment]
Can you try opening the same project on a different machine and let me know if it loads correctly or not?
Thanks.

On 5 Sep 2017, at 07:52, tamarawasser <notifications@github.com<mailto:notifications@github.com>> wrote:


Svenja worked on it in the morning again. It looks a bit different now. But she stopped working on it right now.

**Comment by tamarawasser** [comment]
When we open the project now on my device HP Spectre, on Svenjas Dell and on the little Tablet, the project looks the same on each device.

**Comment by corradocavalli** [comment]
I get a totally different project view now w/o any picture. Sorry but can't investigate what's going on if project is totally different
![image](https://user-images.githubusercontent.com/5617938/30163068-d3cfc790-93d7-11e7-96e0-4dcf55269c42.png)

**Comment by tamarawasser** [comment]
I'll try to replicate as soon as possible.

**Comment by corradocavalli** [comment]
9141/sn6u6

**Comment by teguria** [comment]
the new project misses ink on light blue sticky note (Level 3) - Ink is Test 6
