### ISSUE TITLE
Design Update - Sticky note error message when there are no ink layer

### ISSUE THREAD

**Issue by gsantopaolo** [IBVSoftware/CollaBoard-Feedback#311]
This design is very poor and not aligned with other CollaBoard UI !

![image](https://user-images.githubusercontent.com/9937149/30062686-537689da-924c-11e7-89d3-df0280d6ea5a.png)

**Comment by corradocavalli** [comment]
Ok, and what is the 'official' UI for this special case?
Please note that standard error message is not applicable and when this error happens application is in a stale state.



On 5 Sep 2017, at 09:11, Gian Paolo Santopaolo <notifications@github.com<mailto:notifications@github.com>> wrote:


This design is very poor and not aligned with other CollaBoard UI !

[image]<https://user-images.githubusercontent.com/9937149/30062686-537689da-924c-11e7-89d3-df0280d6ea5a.png>

**Comment by gsantopaolo** [comment]
I know. Let's discuss next week this
