### ISSUE TITLE
Panda when loading an existing project

### ISSUE THREAD

**Issue by tamarawasser** [IBVSoftware/CollaBoard-Feedback#312]
5th September 3pm
Open CollaBoard on Dell Inspiron 1750
Put in Split Screen (CollaBoard and Web are open)
Load an existing Project (Project: 8969 / Key: a8dk8)
Click load
Panda appears
![panda](https://user-images.githubusercontent.com/25382402/30062779-abb35f6a-924c-11e7-88b1-38412e48fa61.png)

Click okay on Panda
CollaBoard Start Screen appears 
On the Start Screen CollaBoard loaded Sticky Notes (unfortunately we don't have a Screenshot here)

**Comment by corradocavalli** [comment]
Does it happen all times and also when screen is not splitted?


On 5 Sep 2017, at 09:17, tamarawasser <notifications@github.com<mailto:notifications@github.com>> wrote:


5th September 3pm
Open CollaBoard on Dell Inspiron 1750
Put in Split Screen (CollaBoard and Web are open)
Load an existing Project (Project: 8969 / Key: a8dk8)
Click load
Panda appears
[panda]<https://user-images.githubusercontent.com/25382402/30062779-abb35f6a-924c-11e7-88b1-38412e48fa61.png>

Click okay on Panda
CollaBoard Start Screen appears
On the Start Screen CollaBoard loaded Sticky Notes (unfortunately we don't have a Screenshot here)

**Comment by tamarawasser** [comment]
It happen all the time but just in Split Screen. When there is just CB open on the Screen it works normal.

**Comment by corradocavalli** [comment]
Unfortunately can't reproduce it, please make this machine available for testing next week.

**Comment by corradocavalli** [comment]
It happens with v 106 (from the store) but no longer with v 107, so it seems fixed. Try when new build will be out and close is ok.
Thanks.
