### ISSUE TITLE
Request regarding User List - JD instead of Surface Hub Icon

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#314]
Hi all,
during a Demo yesterday I was asked who JD is. I explained that is not JD from Srcubs and that it stands fro Jon Do. I think it would be better if we can switch back to the Surface Hub Icon instead of JD. 
Let me know what you think. 
Thanks
Michael

**Comment by corradocavalli** [comment]
Where you demoing using Personal or Team mode on Hub? 
In Personal Mode those are the initials of the user logged in (if it is a demo user you can try associating a personal image also) and think is correct to identify what user is acting on a specific Hub.

**Comment by gsantopaolo** [comment]
Michael is talking team mode on a surface hub (not logged in).
In this case JD appears, I also think is better to revert back on surface hub icon in this case.
BTW, as already discussed such changes **MUST** be discussed before being pushed outside

thanks

**Comment by corradocavalli** [comment]
Let me investigate because JD is totally new to me, agree that in Team mode the Surface icon should be displayed.

**Comment by corradocavalli** [comment]
Fixed in v 107, please @mtg1986 verify and close if ok.

**Comment by corradocavalli** [comment]
Checked on Hub: When a user now uses Team Edition mode is now displayed using Surface Hub icon as requested.
