### ISSUE TITLE
Search Box movement

### ISSUE THREAD

**Issue by teguria** [IBVSoftware/CollaBoard-Feedback#315]
v 1.3.106
HP Spectre and Surface Hub

When you want to move the Search Box around, it doesn't move as it should be (it's like a scattered movement instead of a fluid one).

**Comment by corradocavalli** [comment]
When does this happens? Do you have a project open, what if you move it after CB has launched? if so, please provide project name/key.
Tried now and is fluid on my machines.

**Comment by teguria** [comment]
@corradocavalli  It seems it happens when: the project is created. Then you open the Search Box and then it flickers or you cannot even move it unless you touch another tile (then it works again)

**Comment by teguria** [comment]
closing for now
