### ISSUE TITLE
Evaluation email looks poor

### ISSUE THREAD

**Issue by corradocavalli** [IBVSoftware/CollaBoard-Feedback#317]
I have requested an evaluation key and this is the mail I have received:
![image](https://user-images.githubusercontent.com/5617938/30218932-c9bb7e96-94ba-11e7-9895-07a9178d935b.png)

As you see logo is stretched and there's no minimal indication of what is the long sequence of letters/numbers that follows.
May I suggest to add, at least, a "Here's your evaluation key" and two lines of text that tell what to do with that key?

**Comment by gsantopaolo** [comment]
Guys, this is a bug.
May I suggest you again to ask to a professional web designer to do that for us?

**Comment by mtg1986** [comment]
@corradocavalli : On what device did you look at your key? 
The last eval e-mail I got was in march and looked good. 

I would suggest not to send a key to the user (when using other similar apps I never got a key and eval-version or licensing was always done in the background).

![evale-mail](https://user-images.githubusercontent.com/19570958/30246780-de1d99ba-9603-11e7-995a-1cdf27a5c171.PNG)

**Comment by corradocavalli** [comment]
Screenshot comes from my iPhone, but it looks the same also on iPad.

On 10 Sep 2017, at 08:43, Michael Görög <notifications@github.com<mailto:notifications@github.com>> wrote:


@corradocavalli<https://github.com/corradocavalli> : On what device did you look at your key?
The last eval e-mail I got was in march and looked good.

I would suggest not to send a key to the user (when using other similar apps I never got a key and eval-version or licensing was always done in the background).

[evale-mail]<https://user-images.githubusercontent.com/19570958/30246780-de1d99ba-9603-11e7-995a-1cdf27a5c171.PNG>

**Comment by gsantopaolo** [comment]
@corradocavalli @mtg1986  what about this?
