### ISSUE TITLE
Resizing Slash Screen

### ISSUE THREAD

**Issue by teguria** [IBVSoftware/CollaBoard-Feedback#319]
HP, ThinkPad, Asus
v. 1.108
If you resize the splash screen, the icons and text mess up. This has been tested on multiple devices with the same outcome.

**Comment by corradocavalli** [comment]
What do you mean with messed up? can you provide a screenshot?

**Comment by teguria** [comment]
in attach
![untitled](https://user-images.githubusercontent.com/19929395/30361367-ead0d848-9856-11e7-83f2-b77c5838d6a5.png)

**Comment by corradocavalli** [comment]
This screen is going to be totally redesigned, so we won't invest on it at the moment.

On 13 Sep 2017, at 07:49, alead <notifications@github.com<mailto:notifications@github.com>> wrote:


in attach
[untitled]<https://user-images.githubusercontent.com/19929395/30361367-ead0d848-9856-11e7-83f2-b77c5838d6a5.png>
