### ISSUE TITLE
Different colors in edit mode VS viewing mode

### ISSUE THREAD

**Issue by teguria** [IBVSoftware/CollaBoard-Feedback#32]
I noticed something when I was inking. The colors change as long as I change the sticky note to edit and save and then back to the "normal" mode. See screenshots attached (before and after)
![color1](https://cloud.githubusercontent.com/assets/19929395/19998923/c66beeee-a26f-11e6-9d45-f9131a0e68c9.jpg)
![color2](https://cloud.githubusercontent.com/assets/19929395/19998932/cdb31858-a26f-11e6-8b36-33d5edf3e3fd.jpg)

**Comment by corradocavalli** [comment]
The Ink that changes is Highlight or plain Ink, if Highlight, yes, we have a slight difference between Edit vs Normal mode.

**Comment by gsantopaolo** [comment]
Closing because too old
