### ISSUE TITLE
Issue when using voice for the Project Key in German

### ISSUE THREAD

**Issue by teguria** [IBVSoftware/CollaBoard-Feedback#321]
v. 1.3.108
Asus UX390UAK

German version
Tried to use voice command to spell the project key in german. Clicked on the microphone icon several times and that he got this error message (in attach). Non-reproducible
![fehlercode collaboad](https://user-images.githubusercontent.com/19929395/30314090-e6e894e4-979f-11e7-9368-40bf0e63fe6a.png)

**Comment by gsantopaolo** [comment]
@tamarawasser @mtg1986 @teguria guys we do need an hand from your side, maybe you can organize a testing sessions trying to reproduce issues we have with label "more info needed"
