### ISSUE TITLE
2 voice commands at the same time

### ISSUE THREAD

**Issue by teguria** [IBVSoftware/CollaBoard-Feedback#323]
v 1.3.108
multiple devices (no Hub)

2 laptop/people said "CollaBoard - Close Project"
then Laptop A got the message window if you want to close the project
At that time, another teamplayer said "CollaBoard - Info" close to him on Laptop B
- CollaBoard, on Laptop A, crashed and it became blurred (assume it tried to open Info below the same window opened)
![collaboard blurry](https://user-images.githubusercontent.com/19929395/30314559-5d47799c-97a1-11e7-80b7-67bc80ab61be.png)

**Comment by teguria** [comment]
Trying to reproduce

**Comment by gsantopaolo** [comment]
@tamarawasser can you please verify and close or label as bug and adding to a dev? Thanks

**Comment by tamarawasser** [comment]
@corradocavalli let's try next week. Can't test this allone, for sure.
