### ISSUE TITLE
Read-Only: message needed

### ISSUE THREAD

**Issue by teguria** [IBVSoftware/CollaBoard-Feedback#325]
When you are in read-only, all the people in the project can still uploading stuff and work on the same project. Of course the others won't be able to see anything but all the teamplayers would assume that the project is still up and running.
Suggestion: a message pop-up, as long as you upload a tile, to let you know that the project has been set to read-only

**Comment by corradocavalli** [comment]
This was a bug, when a project is in read-only no one  can upload stuff, behavior has fixed in v109.
