### ISSUE TITLE
Read-Only Project

### ISSUE THREAD

**Issue by teguria** [IBVSoftware/CollaBoard-Feedback#327]
For every user, anyone can create stuff.
But the behaviour of all the tiles differs from one to another. For example: you can record a video and you can take a screenshot out of it. You can edit a sticky note but you can't save. You cannot save a map but you can search. Etcerera

**Comment by teguria** [comment]
This is probably related to [https://github.com/IBVSoftware/CollaBoard-Feedback/issues/325](url)

**Comment by gsantopaolo** [comment]
@tamarawasser  please add to the CB FDS and close
