### ISSUE TITLE
Read-only project and content

### ISSUE THREAD

**Issue by teguria** [IBVSoftware/CollaBoard-Feedback#328]
v 108
I set the project to read-only
- people started to put stuff into the project
- then I set it back to normal
- this is what happened (in attach) in 2 laptops

![10](https://user-images.githubusercontent.com/19929395/30315919-b46111c6-97a5-11e7-9125-d30ab5a9a05e.JPG)
![collaboard error](https://user-images.githubusercontent.com/19929395/30315917-b45af106-97a5-11e7-8405-efde3fbb8c05.png)

**Comment by teguria** [comment]
I set it back to normal (non-ready only). I uploaded some tiles and I got an error message (below)
![untitled](https://user-images.githubusercontent.com/19929395/30316106-6e30957c-97a6-11e7-8374-3ce86ea27139.png)

**Comment by corradocavalli** [comment]
@gsantopaolo It happens because when message with MessageType.ProjectUpdated is sent it contains a null ProjectKey field (projectCode is ok) and this causes all subsequents lookup to fail.

**Comment by corradocavalli** [comment]
Fixed on v 109.
