### ISSUE TITLE
[137] when you launch CollaBoard, the menu bar stay on top

### ISSUE THREAD

**Issue by teguria** [IBVSoftware/CollaBoard-Feedback#33]
Don't know if this is what you wanted to have or not, just wanted to report this

OS Build: 14393.447
Hp Spectre X360

**Comment by corradocavalli** [comment]
Can you send me a screenshot?

On 23 Nov 2016, at 23:31, alead <notifications@github.com<mailto:notifications@github.com>> wrote:


Don't know if this is what you wanted to have or not, just wanted to report this

OS Build: 14393.447
Hp Spectre X360

-

**Comment by teguria** [comment]
![screen](https://cloud.githubusercontent.com/assets/19929395/20593109/60c7c348-b231-11e6-8906-da7df476c2d9.jpg)

**Comment by corradocavalli** [comment]
It's by design, on tablet mode it disappears automatically.
