### ISSUE TITLE
2 issues when creating a project

### ISSUE THREAD

**Issue by teguria** [IBVSoftware/CollaBoard-Feedback#330]
v 108
HP Spectre
11.25
- Create a new project on HP
- Use the QR code on the Hub to load it
- Back to HP, reduce everything to the taskbar (clicked on the far right of it)
- Drag a PDF from the deskop, paste into CollaBoard
- 2 issues happened: the PDF was loading for all the other machines. I couldn't see the PDF on mine
The "new project" window behaviour was weird: I tried to move it with touch and it was behaving inconsistenly. Tried 3 times, Unable to reproduce

**Comment by corradocavalli** [comment]
Probable duplicated of issue #335.
