### ISSUE TITLE
Feature Request: Your Library is full

### ISSUE THREAD

**Issue by tamarawasser** [IBVSoftware/CollaBoard-Feedback#331]
When I have a Grid Library who's full of Tiles and I try to pull another Tile into this Grid Library, the Tile lies on the Grid Library. It would nice to receive a message here, something like: This Grid Library is full, what about creating a new one?

**Comment by teguria** [comment]
adding the label

**Comment by gsantopaolo** [comment]
@tamarawasser  please add to the CB FDS and close
