### ISSUE TITLE
Uploading a picture while closing a project

### ISSUE THREAD

**Issue by teguria** [IBVSoftware/CollaBoard-Feedback#333]
v. 108
HP Spectre (T.)

- T. wanted to close the project but she still had a PDF uploading
- She closed the project and got the following error message
![picture upload](https://user-images.githubusercontent.com/19929395/30319251-ac76271c-97af-11e7-8b30-7909a4a171fb.JPG)

**Comment by corradocavalli** [comment]
Fixed in v109, please test it.
