### ISSUE TITLE
Dragging a sticky showed a black square

### ISSUE THREAD

**Issue by teguria** [IBVSoftware/CollaBoard-Feedback#334]
v 108
HP Spectre only

- I dragged a sticky note from a library into the canvas
- I got the following black empty square over the edit button
- After a short while it disappeared
![untitled](https://user-images.githubusercontent.com/19929395/30319792-1af58632-97b1-11e7-96d1-0b4d6e5f9401.png)

**Comment by gsantopaolo** [comment]
@tamarawasser @mtg1986 @teguria guys we do need an hand from your side, maybe you can organize a testing sessions trying to reproduce issues we have with label "more info needed"
