### ISSUE TITLE
Dragging from desktop into CollaBoard

### ISSUE THREAD

**Issue by teguria** [IBVSoftware/CollaBoard-Feedback#335]
v 108
HP Spectre

- Project already opened
- Click on the far right part of the taskbar to minimize everything
- Select a PDF
- Drag that PDF from desktop into CollaBoard
- CB starts to sync project while uploading the PDF
- The PDF is not uploaded on my machine but it's uploaded (not entirely) on other machines
- Tried a second time and got the PDF white-blank

Reason seems to be the syncing as long as you maximize CB while dragging something into CB

**Comment by corradocavalli** [comment]
Fixed in v109, please @teguria verify it (since you know what is the exact sequence) and close it if ok.
