### ISSUE TITLE
Demo version and licensing

### ISSUE THREAD

**Issue by teguria** [IBVSoftware/CollaBoard-Feedback#336]
v 108
Lenovo Thinkpad

- Lenovo is in demo mode
- After a while, the Demo Version Popup came up
- Now, P. user can, by using the mousewheel, change the window from screen1, screen2, screen3 without using the Buttons or fill in stuff.
- The sequence 
![demoversion3](https://user-images.githubusercontent.com/19929395/30320700-b94c1dbc-97b3-11e7-9966-6020e3f9b8e4.PNG)
![demoversion1](https://user-images.githubusercontent.com/19929395/30320702-b953f0be-97b3-11e7-8280-66ca06eb2f6e.PNG)
![demoversion2](https://user-images.githubusercontent.com/19929395/30320699-b94b332a-97b3-11e7-8123-b547bf6d837d.PNG)

- He sees the sequence that should only be displayed by using the buttons
- At screen3 if he presses Close he can skip the 30 secs wait time from the DemoVersion Popup.
- The last part said "thanks for registering" but he's not and he even tried to do that

You can replicate it on another machine in demo mode
You can also register but you can still scroll with the mousewheel through the entire process

**Comment by corradocavalli** [comment]
Fixed in v109.
