### ISSUE TITLE
Video quality on Help

### ISSUE THREAD

**Issue by teguria** [IBVSoftware/CollaBoard-Feedback#337]
v 1.308
All devices

It seems that the Video Quality in CollaBoard is not adaptive and it looks worse than on YouTube. 
I think you can see the difference clearly on the attached images. It seems the first one is too sharpen.
![videocomparison](https://user-images.githubusercontent.com/19929395/30324908-fd8eb43a-97c2-11e7-8968-8d0ac606cfe3.png)

**Comment by gsantopaolo** [comment]
@tamarawasser  please add to the CB FDS and close
