### ISSUE TITLE
Project confirmation message window behaves differently

### ISSUE THREAD

**Issue by teguria** [IBVSoftware/CollaBoard-Feedback#338]
v 1.308

Steps to reproduce:
- Open CB
- Create a new project
- You get the confirmation message that the project has been created
- Then you can move the window as you can see in the video

[CollaBoard 12_09_2017 14_17_37.zip](https://github.com/IBVSoftware/CollaBoard-Feedback/files/1295891/CollaBoard.12_09_2017.14_17_37.zip)

**Comment by corradocavalli** [comment]
Fixed in v109
