### ISSUE TITLE
Search box doesn't pop up

### ISSUE THREAD

**Issue by teguria** [IBVSoftware/CollaBoard-Feedback#339]
v 1.3.108
All devices (not the Hub)

Project Code: 9130
Project Key: a7rbc
Project description: CollaBo

- We were working on a library (for a different bug)
- Then we wanted to test the Search functionality
- We used voice command by saying a similar word to CollaBoard and we got confirmation messages from different laptops
- Then we tried to open the Search box
- This didn't work on 3 devices (out of 5)

We will try to replicate

**Comment by teguria** [comment]
So it seems the Search box appears but it appears on another part of the canvas. Normally, it should fade into the place where you used the radial menu

**Comment by corradocavalli** [comment]
It might depend on issue #384 can you please test again with build 109? Thanks

**Comment by gsantopaolo** [comment]
@tamarawasser @mtg1986 @teguria guys we do need an hand from your side, maybe you can organize a testing sessions trying to reproduce issues we have with label "more info needed"
