### ISSUE TITLE
Problem with specific Project

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#34]
Hello,
we have an issue with project  1852

The following steps lead to the error:
1.Load Project
2.Click on Edit in one of the Sticky Notes
3.Error
When opening another project (without closing the App, Inking on sticky notes is not possible anymore and the pen can only be used to move the sticky notes around). When restarting CollaBoard inking works fine again. 

Time: 09:15 – 09:20
Location: Bonstetten 
Device: Cube i7 
OS: Windows 10 Home (Build 14393)

Thx

Michael

**Comment by corradocavalli** [comment]
Fixed
