### ISSUE TITLE
Project message confirmation creation missing

### ISSUE THREAD

**Issue by teguria** [IBVSoftware/CollaBoard-Feedback#340]
v 1.3.108
Surface Pro 3

When you create a new project, M. didn't get the confirmation window containing all the information about the newly created project.
This happened only twice, we tried to reproduce but we couldn't

**Comment by gsantopaolo** [comment]
@tamarawasser @mtg1986 @teguria guys we do need an hand from your side, maybe you can organize a testing sessions trying to reproduce issues we have with label "more info needed"

**Comment by tamarawasser** [comment]
Project information appear when I create a new project on HP Spectre, SfBook and SfHub. 
@teguria did you maybe opened an existing project or did Michale joined one you created? Project information appear just, when you create a new project, not when you load an existing one.
