### ISSUE TITLE
Layout Cycle detected. Layout could not complete. 

### ISSUE THREAD

**Issue by tamarawasser** [IBVSoftware/CollaBoard-Feedback#341]
12th of September 2017
HP Spectre 
Project: 9158
Key: gxltz

- create a new project
- open Search
- search for Collaboard (Video)
- add the Video on the Canvas
- click on play
- open camera
- start recording

when recording time of the camera is over, this message appears
![unbenannt](https://user-images.githubusercontent.com/25382402/30330823-6ad6e7f2-97d6-11e7-99df-8225cd2d3bf8.JPG)

CollaBoard is not reacting anymore. I have to close.

**Comment by gsantopaolo** [comment]
@tamarawasser @mtg1986 @teguria guys we do need an hand from your side, maybe you can organize a testing sessions trying to reproduce issues we have with label "more info needed"

**Comment by tamarawasser** [comment]
Tried it more than once on SfBook and SfHub and it works without any problems. 
On HP Spectre: 
Open Search and Search for CB Video
Move the video on the Canvas and play it
Open Camera and start recording Video
Video recording always stops before time for recording is over (around 1 second before) and then I can't do anything in CB. Like everything is blocked. The only possibility to close CB is to click on the cross in the corner up right.

**Comment by gsantopaolo** [comment]
@corradocavalli can you please look at this?

**Comment by tamarawasser** [comment]
#390
