### ISSUE TITLE
Tile full screen - 2 people working on it at the same time

### ISSUE THREAD

**Issue by teguria** [IBVSoftware/CollaBoard-Feedback#343]
v. 1.3.108
ThinkPad, HP Spectre and Asus
16.22
Reproducible bug

Open a sticky note
Have 2 people working on it. Person A clicks on the border of the sticky note, Person B tries to make it full screen. The outcome is the one in the attached picture (sticky note with no borders, menu belongs to the full screen mode but it's not). Only Person A (the one who tries to make it full screen) gets this behaviour.
![untitled](https://user-images.githubusercontent.com/19929395/30331034-02ee4076-97d7-11e7-86b8-d48cd42fa5e1.png)

**Comment by gsantopaolo** [comment]
@tamarawasser can you please very and close or mark as bug?
