### ISSUE TITLE
Tile full screen made the whole content disappeared

### ISSUE THREAD

**Issue by teguria** [IBVSoftware/CollaBoard-Feedback#344]
v 106
Surface Hub 84

- I was testing the borders
- I was editing a sticky note then
- Changed the color and the size
- Saved
- Then made it full screen
- Everything disappeared (including the mini-map)

Trying to reproduce

**Comment by gsantopaolo** [comment]
@tamarawasser @mtg1986 @teguria guys we do need an hand from your side, maybe you can organize a testing sessions trying to reproduce issues we have with label "more info needed"
