### ISSUE TITLE
Out-of-Sync device

### ISSUE THREAD

**Issue by teguria** [IBVSoftware/CollaBoard-Feedback#345]
v 106
Surface Hub 84
Device goes out of sync when connection is slow (all the other devices are in sync, including the ones who are on a different network)

**Comment by corradocavalli** [comment]
We discovered the cause of general out of sync issues, unfortunately is out of our radar and we're now trying to understand how we can fix it.

**Comment by gsantopaolo** [comment]
Closing, too old
