### ISSUE TITLE
Connecting tile toolbar on SfHub 84

### ISSUE THREAD

**Issue by teguria** [IBVSoftware/CollaBoard-Feedback#349]
v 1.3.106
84 Hub

Project Code: 9189
Project Key: 5m60y
Project description: Test

- Have 2 people on the Hub
- One tap and hold on a connecting tile, the other do the same on another connecting tile almost at the same time
- Depending on where you are positioned in the canvas, you get the menu somehow broken (in attach)
![tile](https://user-images.githubusercontent.com/19929395/30371927-633d541c-987c-11e7-9871-9f77e23a5248.jpg)

**Comment by corradocavalli** [comment]
Fixed in v109

**Comment by tamarawasser** [comment]
@corradocavalli  it doesn't happen on the Sf Hub 55". Is it necessary to test on 84" too? should I leave this issue open?
