### ISSUE TITLE
Sticky Note in edit mode

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#35]
When I create a sticky I not, I would like to have it directly in edit mode with default Color.

**Comment by corradocavalli** [comment]
In edit mode you can't easily move it, are you sure? isn't it created with default (yellow) color now?

On 30 Dec 2016, at 12:01, Michael Görög <notifications@github.com<mailto:notifications@github.com>> wrote:


When I create a sticky I not, I would like to have it directly in edit mode with default Color.

**Comment by corradocavalli** [comment]
FYI/ ICYMI: you can quickly enter edit mode by right clicking the tile or tapping the tile with the pen.

On 30 Dec 2016, at 12:01, Michael G?r?g <notifications@github.com<mailto:notifications@github.com>> wrote:


When I create a sticky I not, I would like to have it directly in edit mode with default Color.

-

**Comment by gsantopaolo** [comment]
Closing because too old
