### ISSUE TITLE
Arrow broken while moving it from one side to another of a tile

### ISSUE THREAD

**Issue by teguria** [IBVSoftware/CollaBoard-Feedback#351]
v 106
Hub 84 (and all the other devices)

- Create 2 tiles
- Connect them with the connecting tile
- Move the arrow the other way around (from left to right for example)
- you get a broken arrow (in attach)
![arrow broken](https://user-images.githubusercontent.com/19929395/30372520-6a8a6a46-987e-11e7-89af-50b607d4d18c.jpg)

**Comment by corradocavalli** [comment]
This is issue is by design at the moment: The actual implementation doesn't handle all tile positioning like the one in your scenario.

**Comment by gsantopaolo** [comment]
yep, by design at the moment... closing
