### ISSUE TITLE
Verify license happens very late

### ISSUE THREAD

**Issue by gsantopaolo** [IBVSoftware/CollaBoard-Feedback#355]
Added a break point to verifylicense proxy call
Started collabaord, loaded a project after a while i got the verify license method invoked.... this seems wrong...  @corradocavalli  can you explain?

**Comment by corradocavalli** [comment]
You were probably using a build that has IgnoreExpiredLicense #define enabled, tried now and verify license is invoked once project is loaded.
FYI: License check is never disabled, no matter what the status of define is, in release builds.

**Comment by gsantopaolo** [comment]
@corradocavalli close if fixed please
