### ISSUE TITLE
Strange behaviour - 84 - Tile unable to go upper

### ISSUE THREAD

**Issue by teguria** [IBVSoftware/CollaBoard-Feedback#356]
Surface Hub 84
v. 106

Code: 9257
Key: odyk2

I was trying CB on a 84 Inch.
No pinch to zoom. 
I created a new project
Selected "Business Model Canvas" from the templates"
Then I noticed this strange behaviour like I was unable to go further on top of the canvas
When pinched to zoom, I was able to

I'll see if I can reproduce here on the 84 inches
(see link to video)

Link to video: https://1drv.ms/v/s!AokjDqTnRRs824Q3-dZhbq8Hly_Ydw

**Comment by gsantopaolo** [comment]
I got the same on an 84'...

**Comment by teguria** [comment]
I tried this morning to do the same thing, twice, but the problem is that I couldn't reproduce...

**Comment by gsantopaolo** [comment]
@tamarawasser @mtg1986 @teguria guys we do need an hand from your side, maybe you can organize a testing sessions trying to reproduce issues we have with label "more info needed"
