### ISSUE TITLE
Opened a Project Template - Hub 84

### ISSUE THREAD

**Issue by teguria** [IBVSoftware/CollaBoard-Feedback#357]
v 110
Licensed version
Opened a project Template (Business Model Canvas)
Working with connecting tiles
Got a Panda
![wp_20170919_08_45_38_pro](https://user-images.githubusercontent.com/19929395/30582103-6c5decda-9d1a-11e7-866f-874ea45319c4.jpg)

**Comment by gsantopaolo** [comment]
@tamarawasser @mtg1986 @teguria guys we do need an hand from your side, maybe you can organize a testing sessions trying to reproduce issues we have with label "more info needed"

**Comment by tamarawasser** [comment]
#359
