### ISSUE TITLE
Created a new project template - 84

### ISSUE THREAD

**Issue by teguria** [IBVSoftware/CollaBoard-Feedback#358]
v 110
Created a new project template (Business Model Canvas) on the 84 Hub
As soon as I opened it, the arrow that was previously created from an older project was still there (in attach)
![wp_20170919_08_47_11_pro](https://user-images.githubusercontent.com/19929395/30582169-a78552b2-9d1a-11e7-9f5f-b748556e803a.jpg)
![Uploading WP_20170919_08_46_16_Pro.jpg…]()

**Comment by gsantopaolo** [comment]
@tamarawasser @mtg1986 @teguria guys we do need an hand from your side, maybe you can organize a testing sessions trying to reproduce issues we have with label "more info needed"
