### ISSUE TITLE
Connecting Tiles on 84 Hub - Panda

### ISSUE THREAD

**Issue by teguria** [IBVSoftware/CollaBoard-Feedback#359]
v 110
Created a new project template (Biz Model Canvas)
Started to play around with connecting tiles, including sticky notes and videos
At some point I got a Panda (in attach)
![wp_20170919_08_52_46_pro](https://user-images.githubusercontent.com/19929395/30582292-160b0150-9d1b-11e7-9433-9aa39693af48.jpg)
![wp_20170919_08_52_46_pro](https://user-images.githubusercontent.com/19929395/30582392-6bf31620-9d1b-11e7-8236-53fb08783d50.jpg)

**Comment by gsantopaolo** [comment]
@tamarawasser @mtg1986 @teguria guys we do need an hand from your side, maybe you can organize a testing sessions trying to reproduce issues we have with label "more info needed"

**Comment by corradocavalli** [comment]
@tamarawasser It should be fixed in v 2.0.9, not related to 84" you can test in on 55 or any other device.
