### ISSUE TITLE
App Crash when opening project on Surface Hub

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#36]
On an 84'' Surface Hub the App crashed. 
Time: 17.12 Morning 

Steps: 
1.Create project on a Surface Book 
2.Close project on the Surface Book 
3.Open project on the Surface Hub
4.App suddenly ends  (no error message) 

Code: 2838
Key: 2nm1d

Version 1.2.6

**Comment by gsantopaolo** [comment]
That's nice. I can open it but I get a ghost tile! /cc @corradocavalli

**Comment by gsantopaolo** [comment]
solved on 1.2.9.0
