### ISSUE TITLE
Panda on Hub 55'' (not reproducable)

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#362]
We got a Panda on an 55'' Hub. Last action was tapping in the radial menu. 

Time: 11:50, Date 20.09.2017
Project Code: 9322
Project Key: tvyra
Project description:  New Drink

Device ID: 3c6bc92f-295c-0116-88d7-da0757e09fef

**Comment by gsantopaolo** [comment]
to investigate
