### ISSUE TITLE
Two Project Admins in one Project 

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#363]
We Need to Test this and try to reproduce.

![multiadmins](https://user-images.githubusercontent.com/19570958/30642364-da8dbd34-9e0a-11e7-8c7c-7642c5b4616e.PNG)

**Comment by gsantopaolo** [comment]
@corradocavalli  Prject key and code 2800
7o6kk  dev environment
We have to check if project has an admin or not

**Comment by gsantopaolo** [comment]
2 hubs connected, on tele presence no one is admin
but if we go to info we can change project ownership
issue is that both hubs has same rights

**Comment by gsantopaolo** [comment]
on the hubs there is no edit delte project

**Comment by gsantopaolo** [comment]
we have to reproduce with a different prject as this was used and ownership changed

**Comment by gsantopaolo** [comment]
@tamarawasser can you please try to reproduce?

**Comment by gsantopaolo** [comment]
@corradocavalli @tamarawasser what's the status of this bug?

**Comment by corradocavalli** [comment]
Think it has to be re-tested and closed if ok, is months old.

**Comment by mtg1986** [comment]
Tested with 2.0.41 and we do not have the star icon for project admin/owner anymore. Therefore this bug makes no sense and we can close it.
