### ISSUE TITLE
When on a project activate airplane mode and deactivate

### ISSUE THREAD

**Issue by gsantopaolo** [IBVSoftware/CollaBoard-Feedback#366]
to investigate if the process, When on a project activate airplane mode and deactivate, has something wrong

![img_27092017_130352_0](https://user-images.githubusercontent.com/9937149/30910887-d7978ad4-a386-11e7-92d5-4662dc08219a.png)

**Comment by gsantopaolo** [comment]
@corradocavalli  can we close this?

**Comment by corradocavalli** [comment]
yes, it has been fixed.
