### ISSUE TITLE
Delete Ink - After loading a project

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#368]
When I delete ink after loading a project, everything is deleted and not only one stroke. Please have a look at the Gif. It should explain.
If this is happening an  all ink is erased with one click, an undo option would be great.
![delete ink](https://user-images.githubusercontent.com/19570958/31073492-615f67a8-a76c-11e7-8edd-41adcc88239b.gif)
 it.

**Comment by mtg1986** [comment]
Bug is still here. 
Tested with 1.3.110

**Comment by gsantopaolo** [comment]
This is a bug not nice.
To reproduce:
cretea a project
Create a sticky note
ink on it with pen"123" 
delete "2!
ink again 2
save sticky
close project
reopen it
edit stiky
try to delete
"123" goes agay in one shot they are not any more 3 strokes bute they become one stroke

**Comment by corradocavalli** [comment]
Fixed in v1.4

**Comment by mtg1986** [comment]
Bug is solved, therefore closing.
