### ISSUE TITLE
Border on 84'' Inch Surface Hub

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#369]
1.Create project on Surface pro and fill canvas with content
2.Open Project on Surface Hub 84'' 
3.There is a huge boarder and I cannot work on the whole screen. 

->Have a look at the image. You see in the minimap that tiles are on the boarder, while on the canvas on the hub they are not. 
![issueon84device](https://user-images.githubusercontent.com/19570958/31122928-236cf35c-a83e-11e7-8122-a0587b194456.jpg)

**Comment by corradocavalli** [comment]
What happen if you resize the canvas?

On 3 Oct 2017, at 13:24, Michael Görög <notifications@github.com<mailto:notifications@github.com>> wrote:


1.Create project on Surface pro and fill canvas with content
2.Open Project on Surface Hub 84''
3.There is a huge boarder and I cannot work on the whole screen.

->Have a look at the image. You see in the minimap that tiles are on the boarder, while on the canvas on the hub they are not.
[issueon84device]<https://user-images.githubusercontent.com/19570958/31122928-236cf35c-a83e-11e7-8122-a0587b194456.jpg>

**Comment by mtg1986** [comment]
Nothing, the border is still there. The canvas seems to be to small for the screen.

**Comment by gsantopaolo** [comment]
Yes, I saw and reported it, then you went testing and you didn't got, now @mtg1986  got again.
We need to figure out how to get an 84 for more time and test

**Comment by teguria** [comment]
@mtg1986 maybe we can ask Also to get the 84 (or go there for another round of testing, with the latest version)

**Comment by mtg1986** [comment]
It will not be possible to get the 84'' Device from ALSO they are lending it (2000CHF/Month). So they will not do for free. Only possibility is to ask if we can go there again and try to better plan testing we do there.

**Comment by tamarawasser** [comment]
@gsantopaolo can we create a separate label to mark all the bugs we have to test on a 84" SfHub?

**Comment by corradocavalli** [comment]
Done

**Comment by tamarawasser** [comment]
works very good with v1.4.7
