### ISSUE TITLE
Photo out of the canvas

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#37]
1.Taking a photo
2.Throwing it with a lot of power away, photo moves out of the canvas and can not be touched anymore. 
Version 1.2.6
Project Key and Code and Time unknown

**Comment by gsantopaolo** [comment]
Thanks, we know where the issue is, we need the time to fix it. we will inform when this will be fixed

**Comment by gsantopaolo** [comment]
thanks closing because we already have #39
