### ISSUE TITLE
Got a Panda - Not Reproducable

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#370]
Select Multiple Colors in the ink radial
Project:
-2718
-vxmbo
device: HP Spectre 
Time: 15:41
Version: 1.1.3.116

**Comment by gsantopaolo** [comment]
@corradocavalli  to reproduce open radial, go to color selection tap acolor with pen write something fast, tap another color, write something fast .. and so on... try to check if a bug appears

**Comment by corradocavalli** [comment]
Tried several times, no way to reproduce it on v 1.4.7

**Comment by gsantopaolo** [comment]
Closin, too old
