### ISSUE TITLE
Counter of Demo Version - Counters backwards (with Panda)

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#373]
-Logged out 
-Log-In as personal user with MS Account 
-Home Screen of CB
-Load Project
-Join  a project (2721)
-The project did not load and then there was the blocker. 
-Then we wait until 0, then it goes back to -7
-Wait again until 0 -->Panda appears

Version: 1.1.3.116

![demo version](https://user-images.githubusercontent.com/19570958/31500077-ce33cafc-af66-11e7-94d8-3de56168b359.JPG)

**Comment by gsantopaolo** [comment]
@corradocavalli is this fixed or not?

**Comment by mtg1986** [comment]
Counter is working. 
Tested in 1.4 
1.3.110
