### ISSUE TITLE
Ink gets invisible when inking with two pens at the same time

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#374]
Reproducable, but seems to happen randomly 

-When inking with two pens at the same time on the canvas, sometimes Ink gets invisible, but does not dissappear

I sent you a Link with a video.

**Comment by gsantopaolo** [comment]
@mtg1986  can you post video's link here?

**Comment by mtg1986** [comment]
https://1drv.ms/v/s!AlVRFc0_V4ZLurZm6xBG7O4oaw2TZQ

**Comment by mtg1986** [comment]
Tested on 1.4
Not reproducable anymore
