### ISSUE TITLE
Inking on the same spot causes Pandas

### ISSUE THREAD

**Issue by teguria** [IBVSoftware/CollaBoard-Feedback#375]
116
pattern found, no need to have code and key

- Have at least 2 people on the same project (with their devices, no Hubs)
- Person A select its colour and pen type
- Person B select its color and pen type
- Person A and B ink on the same exact spot
- At some point, they both get a Panda "There's seem to be a problem..."

**Comment by corradocavalli** [comment]
@teguria Can you please try again with 1.4.7 and let us know if bug still present?

**Comment by tamarawasser** [comment]
Inking on the same spot is possible. Did it more than once now on different devices and never had a panda. 

Other problem here: Realtime Ink is missing on HP Spectre

HP Spectre
Surface Pro
06.11.2017 / 17:12

Project Code: 2991
Project Key: qcy7m

choose red pen for Surface Pro
choose green pen for HP Spectre
start inking on the same time in the marked spot (black area in the video)
stop inking
green ink from HP Spectre appears on Surface Pro
red ink from Surface Pro doesn't appear on HP Spectre

[ink is missing.pptx](https://github.com/IBVSoftware/CollaBoard-Feedback/files/1446929/ink.is.missing.pptx)
