### ISSUE TITLE
Demo version window on the Hub

### ISSUE THREAD

**Issue by teguria** [IBVSoftware/CollaBoard-Feedback#376]
v .116
SfHub

When you get the demo version on the Hub, you get the 5 seconds time to wait and then it should disappear.
But it happened, on the Hub, that I got the demo version waiting time and then it appeared again for another 5 seconds.
Another time, the waiting time was 5 seconds, then I got the message for 5 seconds and then the same message again for 5 seconds (so a total of 3 times)

**Comment by gsantopaolo** [comment]
User are reporting this bug on different devices.
@corradocavalli  can we talk about this?

**Comment by corradocavalli** [comment]
I cannot reproduce on any of my machine and I tried also on Hub we have on Dev floor without success, added and additional security flag to prevent multiple instantiations but w/o a repro case I don't know how to fix it.

**Comment by gsantopaolo** [comment]
@tamarawasser @mtg1986 @teguria  guys we do need an hand from your side, maybe you can organize a testing sessions trying to reproduce issues we have with label "more info needed"
