### ISSUE TITLE
Access Denied error message

### ISSUE THREAD

**Issue by teguria** [IBVSoftware/CollaBoard-Feedback#377]
v 1.118
Surface Book
Code: 2760
Key: uzqqu

I used the snipping tool to copy an image, CB was in backgroung
As long as I got back to CB, I got the error message (in attach)
![2017-10-23](https://user-images.githubusercontent.com/19929395/31893020-b5a11452-b80a-11e7-8f1a-19eee8a202f7.png)

**Comment by teguria** [comment]
can confirm this happens all the time as long as I try to access the clipboard

**Comment by gsantopaolo** [comment]
@corradocavalli  is it fixed ot just a workaround?

**Comment by corradocavalli** [comment]
I refactored the code to make it work also on that machine, not clear if problem is the machine or FCU installed.
@teguria can you check it with new version?

**Comment by tamarawasser** [comment]
@teguria  for your information: it's working on HP Spectre

**Comment by teguria** [comment]
@tamarawasser can you please try to replicate on the Surface Book as well? I think it shouldn't anymore but just wanted to be sure.
