### ISSUE TITLE
When trying to ink on the same spot

### ISSUE THREAD

**Issue by teguria** [IBVSoftware/CollaBoard-Feedback#379]
v 118
Surface Book and Surface Hub

3 people inking at the same time (2 on the Hub and 1 on the Book), at some point we all got the same error message (in attach)
![untitled](https://user-images.githubusercontent.com/19929395/31893914-23e77df0-b80d-11e7-954b-984c98be816c.png)

**Comment by gsantopaolo** [comment]
@corradocavalli  it seems a recursive error... can we test it?

**Comment by corradocavalli** [comment]
It should be fixed in V 1.40
