### ISSUE TITLE
Error after sleep modus 

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#38]
1.Creating a project 
2.Device goes in sleep mode
3.Login to Windows 
4.Error Message on CollaBoard "Sorry, an unexprecte..... restart the application"

Time: 19.01.2016  18:58
Project Code: 2954 
Key: 3bwto

Version: 1.2.7.0
Device: Surface Pro 4

**Comment by corradocavalli** [comment]
Can't reproduce it with same project, do you have a reproducible sequence?

**Comment by gsantopaolo** [comment]
this is now fixed
