### ISSUE TITLE
Background Templates stretched

### ISSUE THREAD

**Issue by teguria** [IBVSoftware/CollaBoard-Feedback#380]
v 119
Surface Book and Lenovo ThinkPad E550

Open a project with a background image (template)
Then the template in the background looks stretched

**Comment by teguria** [comment]
![image](https://user-images.githubusercontent.com/19929395/31990907-b5925058-b976-11e7-994d-2fb9aa85f2e7.png)

**Comment by corradocavalli** [comment]
@teguria @mtg1986 Can you send me via mail the original image used in the above example? Thanks

**Comment by corradocavalli** [comment]
Fixed in v 1.40
