### ISSUE TITLE
Deleting didn't delete the arrow

### ISSUE THREAD

**Issue by teguria** [IBVSoftware/CollaBoard-Feedback#381]
v 119
Surface Book together with 3 more devices
code: 2761
key: i50yc

A lot of people inked on the canvas
They also added some sticky notes and they connected them
Then I used my pen to start deleting inking
At some point I realized there was an arrow (connecting tile dots) that was still there even though I cleaned that part as well (in attach)
![untitled2](https://user-images.githubusercontent.com/19929395/31895032-6a876006-b810-11e7-95eb-948fb04e5cbb.png)

**Comment by corradocavalli** [comment]
Please provide a scenario to reproduce it.

**Comment by gsantopaolo** [comment]
@tamarawasser @teguria @mtg1986  can you try to see if you can recreate a reproducible scenario? maybe monday?
