### ISSUE TITLE
Camera doesn't record videos anymore

### ISSUE THREAD

**Issue by teguria** [IBVSoftware/CollaBoard-Feedback#385]
v 220
Surface Book, HP Spectre (but not on the chinese one)

Launch Camera, try to record a video (no matter if it's the back or the front camera)
The outcome is that the camera doesn't record the video as it says it's in use by other applications

**Comment by teguria** [comment]
Right after that, I pinched to zoom, and I got the following error message:
![untitled4](https://user-images.githubusercontent.com/19929395/31897734-8c518232-b817-11e7-812b-4c494b8dc86d.png)

**Comment by gsantopaolo** [comment]
@corradocavalli  is this fixed? can we talk about this?

**Comment by gsantopaolo** [comment]
@tamarawasser can you please verify?

**Comment by tamarawasser** [comment]
#390
