### ISSUE TITLE
2 people inking on canvas at the same time

### ISSUE THREAD

**Issue by teguria** [IBVSoftware/CollaBoard-Feedback#386]
v 220
Project Code: 2773
Project Key: 01gcb
Project description: test oct 2

HP Spectre and Chinese device
2 people inking on the canvas, with different pen/style/color, most probably at the same time.
They both got this error message:
![wp_20171023_17_35_07_pro](https://user-images.githubusercontent.com/19929395/31898288-1650b0f6-b819-11e7-9022-bb9d62c8268e.jpg)

**Comment by gsantopaolo** [comment]
users reports ink at the same time in the same place causes this issue and it happens lots of times

**Comment by corradocavalli** [comment]
It should be fixed with version 1.40
