### ISSUE TITLE
Read-only project and possibility to ink

### ISSUE THREAD

**Issue by teguria** [IBVSoftware/CollaBoard-Feedback#387]
v 119
3 devices

Admin puts the project as read only
other people can still ink while nobody can see what they are inking.
I think you shouldn't be able to ink when it's read only + it should get a message saying that the project is read only

**Comment by gsantopaolo** [comment]
Admin set project read only, second user is still able to ink on the canvas.
Ink colors not synced 
It is possible to paste an item!

**Comment by gsantopaolo** [comment]
User connected to the project didn't got the message project was set to readonly

**Comment by corradocavalli** [comment]
@gsantopaolo @kasuken  Looks like the message is not broadcasted anymore, client doesn't receive it.

**Comment by corradocavalli** [comment]
Added infrastructure to disable ink on background when project is read-only, waiting for fix of missing message

**Comment by gsantopaolo** [comment]
@kasuken  did you fixed?

**Comment by corradocavalli** [comment]
Fixed in v 1.40
