### ISSUE TITLE
Recording audio caused an issue

### ISSUE THREAD

**Issue by teguria** [IBVSoftware/CollaBoard-Feedback#389]
v 120
Surface Book

Started recording session through QAT
Stopped it, re-launched it
Got this message below:
![untitled6](https://user-images.githubusercontent.com/19929395/31900316-467aeba2-b81e-11e7-9fa6-6d4709065662.png)

**Comment by teguria** [comment]
![image](https://user-images.githubusercontent.com/19929395/31989219-f414c694-b971-11e7-871f-dbace8a01b0a.png)

**Comment by corradocavalli** [comment]
How long have you been recording? this is a warning not an error...

**Comment by gsantopaolo** [comment]
@corradocavalli we don't have to allow recordings (audio and video) exceeding the maximum file size allowed...
