### ISSUE TITLE
Unaccesible Tile

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#39]
1.Take a picture
2.Throw picture with lot of power against canvas boards.
3.After doing this like 20 times, picture is out of canvas.

![wp_ss_20170121_0003 002](https://cloud.githubusercontent.com/assets/19570958/22194870/1e74bc92-e145-11e6-9db8-768436457685.png)

Version 1.2.7.0
Device: Surface Pro 4
Time: 21.1.2017 

Project Code: 3008
Project Key: di4fc

**Comment by gsantopaolo** [comment]
I'm closing this because, as you know we do not support anything else that Surface Hub
