### ISSUE TITLE
Issue after launching camera

### ISSUE THREAD

**Issue by teguria** [IBVSoftware/CollaBoard-Feedback#390]
v 220
Surface Book
I launched the camera, started recording the video. Video doesnt work. I closed the window and, after 1 second, I got the following message
![untitled](https://user-images.githubusercontent.com/19929395/31931639-1dd2aace-b8a4-11e7-98e5-46dccfb5f850.png)

**Comment by gsantopaolo** [comment]
@corradocavalli  is it that fixed? If there is a workaround please discuss

**Comment by gsantopaolo** [comment]
discussed changed to waiting confirmation

**Comment by tamarawasser** [comment]
HP Spectre
Launched the Camera
Record Video
Video is recording until the end (1 Minute) than this message appears
![video](https://user-images.githubusercontent.com/25382402/32089102-4964d1a8-bae8-11e7-9554-afc36474d1ab.JPG)

**Comment by corradocavalli** [comment]
Confirmed as HP Spectre only issue, potponed to investigate status.

**Comment by tamarawasser** [comment]
@corradocavalli this just happen on the HP Spectre. On Surface Book, Surface Pros and Surface Hub Camera is working well and without any issues.

**Comment by tamarawasser** [comment]
repeat the Scenario to record Video on HP Spectre twice. 
Project 12879
Key: 0aj4o

Result one: recording run until 0.8 seconds are left. then it stops and nothing works anymore. Means I'm not able to Close the Video tile and I'm not able to Chose one of the other Features from the QAT, also not able to open radial menu. Have to Close CB completely. 

Result two: Video recorded until the end. Tile with Viedo open, but Video is just 1 second Long but it recorded 40 seconds. 

Just happen on HP Spectre. It works all well on SfHub and SfPro.

**Comment by teguria** [comment]
Works on new HP Spectre, v 2.0.8.1. Needs to be added to the list for the old Spectre

**Comment by teguria** [comment]
issue solved on both Spectre Old and Spectre new. @tamarawasser does it still happen on yours?

**Comment by corradocavalli** [comment]
Too old, closing, reopen if necessary
