### ISSUE TITLE
Non-recognized inking type on different devices

### ISSUE THREAD

**Issue by teguria** [IBVSoftware/CollaBoard-Feedback#391]
v 120
2 Surface Hubs

Code: 2774
Key: x0h14

Started inking on 2 Hubs
On Hub 1 I started inking with different pen types (pen, pencil, etc.)
On Hub 2 the inking type was just one which was only the pen

**Comment by gsantopaolo** [comment]
On one hub user is using a pencil, on the second hub, connected on the same project ink was reported as pen and not as pencil.

**Comment by teguria** [comment]
It happened also with Surface Book and HP Spectre on the same project. User A was inking with pen, User B saw the inking as pencil

**Comment by corradocavalli** [comment]
I think this was already reported yesterday and it has been fixed this morning.

Inviato da Posta<https://go.microsoft.com/fwlink/?LinkId=550986> per Windows 10

Da: Gian Paolo Santopaolo<mailto:notifications@github.com>
Inviato: mercoledì 25 ottobre 2017 10:45
A: IBVSoftware/CollaBoard-Feedback<mailto:CollaBoard-Feedback@noreply.github.com>
Cc: Corrado Cavalli<mailto:corrado@outlook.com>; Assign<mailto:assign@noreply.github.com>
Oggetto: Re: [IBVSoftware/CollaBoard-Feedback] Non-recognized inking type on different devices (#391)


On one hub user is using a pencil, on the second hub, connected on the same project ink was reported as pen and not as pencil.
