### ISSUE TITLE
Inking at the same time on the same spot

### ISSUE THREAD

**Issue by teguria** [IBVSoftware/CollaBoard-Feedback#393]
v 120
4 people: 2 Hubs, 1 HP Spectre, 1 Surface Book

2 people inking at the same time on the same spot
HP Spectre was using the pen
At some point, HP Spectre received the error message below
![untitled2](https://user-images.githubusercontent.com/19929395/31934633-ee935250-b8ac-11e7-84ee-818188b56485.png)

**Comment by corradocavalli** [comment]
It should be fixed in v1.40 can you verify it?
Thanks.
