### ISSUE TITLE
IBV bottom logo not visible anymore

### ISSUE THREAD

**Issue by teguria** [IBVSoftware/CollaBoard-Feedback#394]
v 220
IBV background logo on the bottom right is tot visible on Surface Book and Surface Pro. Party visible on HP Spectre (less than a half of it)

**Comment by gsantopaolo** [comment]
this depends because the ink canvas is hiding the layer where the IBV logo is.
@corradocavalli  can we do anything for this?

**Comment by corradocavalli** [comment]
Yes, fixed in v 1.40
