### ISSUE TITLE
Loaded Tile appear nearly behind the Mini Map

### ISSUE THREAD

**Issue by tamarawasser** [IBVSoftware/CollaBoard-Feedback#395]
25.10.2017 | 11.00
HP Spectre

When I add a Tile, the Tile is loaded nearly behind the Mini Map. It would be nice to have it more in the middle of the Canvas. 
![tile behind the mini map](https://user-images.githubusercontent.com/25382402/31989886-e1e4dfac-b973-11e7-90f2-561be4d50921.JPG)

**Comment by gsantopaolo** [comment]
Tested also on the Surface Hub.
It seems that by creating a tile from the QAT it is created exactly at the QAT's buttom right side.
It would be nice it it can be created just near the icon user tapped so different position based on button tapped.
And also it would be nice if the app can decided by itself if to create on the right or left of the QAT depending on QAT position

**Comment by corradocavalli** [comment]
Bottom right corner is the default behavior to stay aligned with radial menu, we can however change that.

Inviato da Posta<https://go.microsoft.com/fwlink/?LinkId=550986> per Windows 10

Da: Gian Paolo Santopaolo<mailto:notifications@github.com>
Inviato: mercoledì 25 ottobre 2017 11:07
A: IBVSoftware/CollaBoard-Feedback<mailto:CollaBoard-Feedback@noreply.github.com>
Cc: Subscribed<mailto:subscribed@noreply.github.com>
Oggetto: Re: [IBVSoftware/CollaBoard-Feedback] Loaded Tile appear nearly behind the Mini Map (#395)


Tested also on the Surface Hub.
It seems that by creating a tile from the QAT it is created exactly at the QAT's buttom right side.
It would be nice it it can be created just near the icon user tapped so different position based on button tapped.
And also it would be nice if the app can decided by itself if to create on the right or left of the QAT depending on QAT position

**Comment by gsantopaolo** [comment]
yep, as described in my previous comment..
