### ISSUE TITLE
Strange Object on Canvas after create Sticky Note

### ISSUE THREAD

**Issue by tamarawasser** [IBVSoftware/CollaBoard-Feedback#396]
Surface Hub
25.10.2017 | 11:06

Create a new Project
Create Sticky Note
Sticky Note is created and another strange object is created on the Canvas (right side up)
![strange object on the canvas](https://user-images.githubusercontent.com/25382402/31990183-a4b67f7c-b974-11e7-85a7-104975fddc6a.png)

**Comment by gsantopaolo** [comment]
it happens on the surface hub, I as there and saw it...

**Comment by tamarawasser** [comment]
It also happen when I upload a picture
![strange object on the canvas_2](https://user-images.githubusercontent.com/25382402/31990396-4897b1f6-b975-11e7-86d4-82def6c3d0c1.png)

**Comment by corradocavalli** [comment]
It is a test rectangle that I’m using fro debugging, removed on  v1.4 available now on dev/vNext branch.
Please close this issue.
Thx


Da: tamarawasser<mailto:notifications@github.com>
Inviato: mercoledì 25 ottobre 2017 11:07
A: IBVSoftware/CollaBoard-Feedback<mailto:CollaBoard-Feedback@noreply.github.com>
Cc: Subscribed<mailto:subscribed@noreply.github.com>
Oggetto: [IBVSoftware/CollaBoard-Feedback] Strange Object on Canvas after create Sticky Note (#396)


Surface Hub
25.10.2017 | 11:06

Create a new Project
Create Sticky Note
Sticky Note is created and another strange object is created on the Canvas (right side up)
[strange object on the canvas]<https://user-images.githubusercontent.com/25382402/31990183-a4b67f7c-b974-11e7-85a7-104975fddc6a.png>
