### ISSUE TITLE
Ink on the right side of the canvas

### ISSUE THREAD

**Issue by gsantopaolo** [IBVSoftware/CollaBoard-Feedback#398]
known bug just for fields

**Comment by corradocavalli** [comment]
Fixed in v1.4.5

**Comment by tamarawasser** [comment]
[Presentation1.pptx](https://github.com/IBVSoftware/CollaBoard-Feedback/files/1433945/Presentation1.pptx)

**Comment by corradocavalli** [comment]
@tamarawasser Should be fixed in v 1.4.7
