### ISSUE TITLE
Click into Mini Map Area generate error message

### ISSUE THREAD

**Issue by tamarawasser** [IBVSoftware/CollaBoard-Feedback#401]
27.10.2017
07:40
HP Spectre

Load an existing project
Project Code: 2816
Project Key: syyct

create a sticky note 
sticky note appear into the mini map area
click on the mini map area and this message appears
![click on mini map](https://user-images.githubusercontent.com/25382402/32089487-9ed4d30c-baea-11e7-8fd2-1c5afc9b1029.JPG)

**Comment by corradocavalli** [comment]
@tamarawasser Good catch.
Fixed in v 1..4.1

p.s: Please add the Bug label to this kind of reports.
