### ISSUE TITLE
By Lasso selected part stays on Canvas after closing full screen

### ISSUE THREAD

**Issue by tamarawasser** [IBVSoftware/CollaBoard-Feedback#404]
HP Spectre
31.10.2017 / 16:41

Sticky Note with Ink is in Full Screen
Select a Part by using the Lasso

![full screen](https://user-images.githubusercontent.com/25382402/32233384-8a03ba9c-be5a-11e7-9f47-645ef50df7e9.JPG)

Close Full Screen Sticky Note
Selected Part is visible on the Canvas

![full screen2](https://user-images.githubusercontent.com/25382402/32233427-a26e4638-be5a-11e7-94ee-95f6e5ae0cae.JPG)

**Comment by corradocavalli** [comment]
@tamarawasser Fixed in v1.4.4
