### ISSUE TITLE
Error Message on Dell Inspiron 1750

### ISSUE THREAD

**Issue by tamarawasser** [IBVSoftware/CollaBoard-Feedback#405]
Dell Inspiron 1750
31.10.2017 / 16:49

Open CollaBoard on Dell
Create a new project
This message appears

![bug](https://user-images.githubusercontent.com/25382402/32233766-6e9ad9ba-be5b-11e7-992b-d4365faab294.jpg)

**Comment by corradocavalli** [comment]
@tamarawasser  can you please try if this is solved with v 1.4.5? thx.

**Comment by tamarawasser** [comment]
@corradocavalli 
tested with v1.4.5. happen again, same message appears

**Comment by tamarawasser** [comment]
#442
