### ISSUE TITLE
Error on Surface Hub while inking on full screened Sticky Note

### ISSUE THREAD

**Issue by tamarawasser** [IBVSoftware/CollaBoard-Feedback#409]
Surface Hub
01.11.17 / 10:06

Create a new project
create a sticky note
make sticky note full screen
select first pen and color black
start inking - Ink is yellow
click with pen on color again to choose black
this message appears

![hub](https://user-images.githubusercontent.com/25382402/32267694-6fa9d86a-beec-11e7-8807-d12eb11bfe51.jpg)

tried it again, doesn't happen anymore.

**Comment by corradocavalli** [comment]
@tamarawasser can you try the same sequence from scratch, need a repro sequence

**Comment by corradocavalli** [comment]
@tamarawasser I made sure if it happens again it won't crash but it default to blue pen, not good but w/o a repro case that's the only temporary solution available. It would be nice if you could understand how to make selected color and ink color out of sync.

**Comment by corradocavalli** [comment]
@tamarawasser Can you try to reproduce it with 1.4.8? thx.

**Comment by tamarawasser** [comment]
@corradocavalli I tried to reproduce. It's not possible, it doesn't happen anymore. Create Sticky Note, make it full screen, choose black. ink in black, all the time. Seems like it's working.

**Comment by corradocavalli** [comment]
@tamarawasser ok, closing then.
