### ISSUE TITLE
By Lasso selected part disapear on SfHub

### ISSUE THREAD

**Issue by tamarawasser** [IBVSoftware/CollaBoard-Feedback#410]
Surface Hub
Surface Book
HP Spectre
01.11.2017 / 11:07

Project Code: 2906
Project Key: xpq5i

Create a new project on Surface Book
Open this project on SfHub and HP Spectre
On all devices, Canvas is zoomed out that I can see the whole canvas on each device
Start inking on background on the Surface Hub, on Surface Book and HP Spectre, everything works. 

Use the Lasso to choose a inked part (yellow one) on the SfHub
on the SfHub: move the choosed part with the pen from the left site of the canvas to the right side. 
On SfHub it looks like this: 
![sfh](https://user-images.githubusercontent.com/25382402/32270335-d2865ce8-bef5-11e7-92df-865b5b349917.jpg)
On HP Spectre and on Surface Book it looks like this: 
![hps](https://user-images.githubusercontent.com/25382402/32270345-e272da50-bef5-11e7-9a55-58ffe78c69d7.JPG)

On the SfHub: delete the yellow ink, ink again on background in yellow, choose this yellow ink with the lasso and zoom in the whole Canvas on the SfHub. Mini Map is positioned in the corner on the top left side. I start moving the yellow ink from the corner up on the left side to the corner down on the right side. Realtime on Surface Book and HP Spectre is working, I can see how the yellow ink is moving. 

At one part of the Canvas of the SfHub, the yellow ink disapears but I can still see it on the HP Spectre and on the Surface Book. 
[Presentation1.pptx](https://github.com/IBVSoftware/CollaBoard-Feedback/files/1433798/Presentation1.pptx)

**Comment by tamarawasser** [comment]
Now I closed the project on the HP Spectre and this panda appears
![panda](https://user-images.githubusercontent.com/25382402/32270738-680be700-bef7-11e7-9440-842e658e55d4.JPG)
then the SignalR appears
![signalr](https://user-images.githubusercontent.com/25382402/32270743-7055dd8a-bef7-11e7-934e-a25117606b05.JPG)
This happen just on the HP Spectre. I was able to close the project on the SfHub and on the Surface Book

**Comment by corradocavalli** [comment]
@tamarawasser it is a consequence of issue #398, marked as waiting confirmation to be checked when #398 will be definitively gone.

**Comment by tamarawasser** [comment]
I close this because it's a consequence of #398. Working on that..
