### ISSUE TITLE
Color changes while choosing the size of the pen

### ISSUE THREAD

**Issue by tamarawasser** [IBVSoftware/CollaBoard-Feedback#411]
Surface Hub
01.11.17 / 11:33

Create a new project
Create a Sticky Note
Make Sticky Note Full Screen
Choose a pen
Choose color red
While choosing the size of the pen, color changes from red to blue but when I start ink on the Sticky Note, color is red again.
[Presentation1.pptx](https://github.com/IBVSoftware/CollaBoard-Feedback/files/1433838/Presentation1.pptx)

**Comment by corradocavalli** [comment]
@tamarawasser Does it happen all times?

**Comment by tamarawasser** [comment]
@corradocavalli just happen on the SfHub, but yes, all the time
