### ISSUE TITLE
Lot of automaticaly created Sticky Notes

### ISSUE THREAD

**Issue by tamarawasser** [IBVSoftware/CollaBoard-Feedback#412]
Surface Hub
Surface Book
HP Spectre
01.11.2017 / 11:41

In the same project with all devices. 
On the SfHub I was working on a full screened Sticky Note. 
On the HP Spectre (I did nothing on this device) the SignalR appears and there are a lot of new Sticky Notes in the corner created by the SfHub, but I didn't create them. 

![signalr_hps](https://user-images.githubusercontent.com/25382402/32271380-e175177c-bef9-11e7-9943-fc49d284b03f.JPG)

On the Surface Book I don't have a SignalR Message but all these Sticky Notes too:

![sticky notes sb](https://user-images.githubusercontent.com/25382402/32271404-025a69b0-befa-11e7-8225-a3043e2eeae1.PNG)

I close the Full Screened Sticky Note on the SfHub and it looks like this:

![sticky notes sfh png](https://user-images.githubusercontent.com/25382402/32271419-10c16148-befa-11e7-954d-ddc1db2eb42c.jpg)

**Comment by corradocavalli** [comment]
@ema @gsantopaolo we need to find a definitive solution for this...

**Comment by tamarawasser** [comment]
@corradocavalli 

Create a new project
Create a sticky note
Make sticky note full screen
Choose pen and color
Ink
Save
Close full screen

There is just one Sticky Note, everything fine. 

And then: 
Create a new project
Create a sticky note
Make sticky note full screen
Choose pen and color AND SIZE OF THE PEN
Ink
Save
Close full screen

There are a lot of Sticky Notes. Seems like they are automatically created.

**Comment by corradocavalli** [comment]
@tamarawasser Fixed in v 1.4.12
