### ISSUE TITLE
Different Ordner on different Devices

### ISSUE THREAD

**Issue by tamarawasser** [IBVSoftware/CollaBoard-Feedback#413]
Surface Hub
Surface Book
HP Spectre

Create a new project
Join the project with all devices
Upload a .jpg, a .png, a video and a PDF on the SfHub

Order on the SfHub:
![order sfh](https://user-images.githubusercontent.com/25382402/32271773-b32be254-befb-11e7-82bd-95f07352d99f.JPG)

Order on the Surface Book and the HP Spectre:
![order hps](https://user-images.githubusercontent.com/25382402/32271760-a499058c-befb-11e7-9e64-9f38739890d0.JPG)

**Comment by tamarawasser** [comment]
After Synchronizing the project on the HP Spectre and on Surface Book
![capture](https://user-images.githubusercontent.com/25382402/32271852-1797aa16-befc-11e7-9d40-33f68a1b69e9.JPG)

**Comment by corradocavalli** [comment]
@kasuken Sound like some messages are missing, need to investigate...

**Comment by tamarawasser** [comment]
#434
