### ISSUE TITLE
Title from Library not visible

### ISSUE THREAD

**Issue by tamarawasser** [IBVSoftware/CollaBoard-Feedback#414]
Surface Hub
HP Spectre
01.11.17 / 12:45

Create a library on the SfHub
Name the library by using ink
Library on SfHub is named but not on the HP Spectre
When I sync CB project on Spectre, Library is named too

**Comment by tamarawasser** [comment]
This just happen, when I name the Library on the SfHub. When I name it on the HP Spectre, the ink is on directly visible on the Surface Book

**Comment by corradocavalli** [comment]
@tamarawasser (should be) Fixed in v 1.4.6

**Comment by tamarawasser** [comment]
not fixed in 1.4.6. 
Create a Library on SfHub and named it by using ink
Library was not named on Surface Book, when I sync. the project on Surface Book, it's named

**Comment by corradocavalli** [comment]
@tamarawasser Can you try, when possible,, with 1.4.7? tried again and looks fixed to me... thx
