### ISSUE TITLE
Edite Mode when Sticky Note in Full Screen

### ISSUE THREAD

**Issue by tamarawasser** [IBVSoftware/CollaBoard-Feedback#415]
I create a Sticky Note on the SfHub
The Sticky Note is in edit mode automatically
Make the Sticky Note Full Screen
Choose Pen, Color and Size
Start inking
Save the Sticky Note and stay in Full Screen

When the Sticky Note is saved and not in Edit Mode anymore, the Icon where I can choose the pens shouldn't be clickable. Because when I click on the Icon to choose pen, color and size again, I'm able to choose all these things, but I'm not able to ink on the Sticky Note. 
I'm not sure if the user will register that he has to go to edit mode first.

**Comment by corradocavalli** [comment]
@tamarawasser That's expected behavior, it was indeed a bug, fixed on v 1.4.6
