### ISSUE TITLE
bad picture quality on HP Spectre

### ISSUE THREAD

**Issue by tamarawasser** [IBVSoftware/CollaBoard-Feedback#416]
Cube i8-L
Surface Book
HP Spectre

Project Code: 2916
Project Key: qyp39

Upload a .jpg pictures on the HP Spectre
Picture Quality on Cube i8-L and Surface Book
![pic_od](https://user-images.githubusercontent.com/25382402/32277300-444fa23c-bf12-11e7-996c-2a78b12bef8f.JPG)

Picture Quality on HP Spectre
![pic_hps](https://user-images.githubusercontent.com/25382402/32277309-518777ea-bf12-11e7-9e5b-33a3cb0928a6.JPG)

Picture Quality on the HP Spectre is always bad, also when I upload a .png or when I upload the picture on the Cube i8-L or the Surface Book.

**Comment by corradocavalli** [comment]
@tamarawasser Should be fixed in v 1.4.8
