### ISSUE TITLE
two people use the lasso generate an issue

### ISSUE THREAD

**Issue by tamarawasser** [IBVSoftware/CollaBoard-Feedback#417]
Surface Hub
01.11.17 / 21:40

Project Key: 10865
Project Code: h5hbw

two people work on the Surface Hub
both choosed the Lasso 
start to select a part with the lasso together
[Presentation1.pptx](https://github.com/IBVSoftware/CollaBoard-Feedback/files/1435641/Presentation1.pptx)

**Comment by corradocavalli** [comment]
@tamarawasser That's by design at the moment, we don't support multiple lassos, added a check that should prevent that bad looking effect on v1.4.8

**Comment by gsantopaolo** [comment]
@tamarawasser can you please verify and close or label as bug please?
