### ISSUE TITLE
two different welcome screens on SfHub 84"

### ISSUE THREAD

**Issue by tamarawasser** [IBVSoftware/CollaBoard-Feedback#419]
SfHub 84"
02.11.2017 / 11:56

Launch CollaBoard
Start Screen with "Welcome to evaluation version..." appears
Than Screen with "Welcome to CollaBoard..." appears

[Presentation1.pptx](https://github.com/IBVSoftware/CollaBoard-Feedback/files/1437452/Presentation1.pptx)

**Comment by corradocavalli** [comment]
@tamarawasser That's by design, you see "evaluation" for the time involved in checking the license, as soon it is validate the text align. Normally is instantaneous but if connection is low the interval might be longer than usual.
