### ISSUE TITLE
Grid Library Title ä/ö/ü 

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#42]
1.Create Grid Library
2.Enter as title ääööüü
3.Close Project
4.Open Project

-->Grid Library Titel is now: ???????

![grafik](https://cloud.githubusercontent.com/assets/19570958/22362964/1541465c-e467-11e6-8a55-c614d7c222f8.png)

Project Code: 3205
Project Key: a5qxr
ibv-collaboard:open?code=3205&key=a5qxr

Time: 27.01.2017 08:02
Surface Pro 4

**Comment by gsantopaolo** [comment]
Hi,
   this is solved on Collaboard 1.2.9.0.
You can test on any collaboard higher than 1.2.9.0 and verify.
Feel free to reopen if it won't be fixed
