### ISSUE TITLE
position of camera tile changes when clicking on switch camera

### ISSUE THREAD

**Issue by tamarawasser** [IBVSoftware/CollaBoard-Feedback#420]
SfHub 84"
02.11.2017 / 12:06

Launch Camera
Camera Tile appear in the corner down left
Move the Camera Tile into the middle of the Canvas
click on the Switch Camera Icon
Camera Tile moved automatically back to the corner down left

[Presentation1.pptx](https://github.com/IBVSoftware/CollaBoard-Feedback/files/1437470/Presentation1.pptx)

**Comment by corradocavalli** [comment]
@tamarawasser fixed in v 1.4.8

**Comment by tamarawasser** [comment]
it's fixed for cube, surface pro, hp specte, sfhub 55"
we have to test on the sfhub 84" than close the issue
