### ISSUE TITLE
Zoom out Canvas while using maps

### ISSUE THREAD

**Issue by tamarawasser** [IBVSoftware/CollaBoard-Feedback#424]
SfHub
06.11.2017 / 16:41

Open a new project
Open Search
Search for Zurich and click on Maps

When I click one time on the camera icon, a pictures out of maps apears
When I click fast (like double click) on the camera icon, Canvas zoom out

[Canvas zoom in.pptx](https://github.com/IBVSoftware/CollaBoard-Feedback/files/1446805/Canvas.zoom.in.pptx)

**Comment by corradocavalli** [comment]
@tamarawasser Fixed in v 1.4.11
