### ISSUE TITLE
Search Tile is not movable

### ISSUE THREAD

**Issue by tamarawasser** [IBVSoftware/CollaBoard-Feedback#425]
SfHub
07.11.2017 / 14:28

Create a new project
open Search
try to move search tile - it's just movable a bit

[p1.pptx](https://github.com/IBVSoftware/CollaBoard-Feedback/files/1450141/p1.pptx)

[p2.pptx](https://github.com/IBVSoftware/CollaBoard-Feedback/files/1450143/p2.pptx)

**Comment by corradocavalli** [comment]
@tamarawasser Fixed in v1.4.14
