### ISSUE TITLE
Delete Library makes Tiles deleted too

### ISSUE THREAD

**Issue by tamarawasser** [IBVSoftware/CollaBoard-Feedback#426]
SfHub
07.11.2017 / 15:06

Create a new project
Create a Grid Library 
Upload some pictures

Move one pictures after the other over the Grid Library like you want to put it into it - when the request appears don't click on the confirmation button, just leave the picture there and go ahead with moving the other pictures over the library

Now all tiles are over the library and the request is open to confirm to put the tile into the library

Delete the Library

Now confirm each Tile to move into the Library - Tiles become deleted

[Presentation1.pptx](https://github.com/IBVSoftware/CollaBoard-Feedback/files/1450287/Presentation1.pptx)

**Comment by corradocavalli** [comment]
@tamarawasser  Fixed in  v1.4.14
