### ISSUE TITLE
Close Tile Full Screen

### ISSUE THREAD

**Issue by tamarawasser** [IBVSoftware/CollaBoard-Feedback#428]
When I open a pictures on my device, I'm used to close it by click on the cross in the corner up right. That's why I often do that in CollaBoard when I want to close tile full screen. Of course than I close CollaBoard and not the tile full screen. Maybe we can implement a request like "are you sure you want to close CollaBoard?"

**Comment by corradocavalli** [comment]
@tamarawasser I've investigate quickly and it looks not so naive to implement as initially expected. 
We will certainly take in consideration.
