### ISSUE TITLE
Copy/Past highlighted text

### ISSUE THREAD

**Issue by tamarawasser** [IBVSoftware/CollaBoard-Feedback#429]
A customer asked me the following: 

He's working on a PDF in CollaBoard. There is some text in the PDF he highlighted. Now he takes the lasso, copy this highlighted part and want to paste it into another tile or on the canvas. But at the moment there is just the highlight copied, not the text.
Would be nice if he would be able to copy the whole part, means text and highlight.

**Comment by gsantopaolo** [comment]
@tamarawasser  please add to the CB FDS and close
