### ISSUE TITLE
Client disconnects from the project

### ISSUE THREAD

**Issue by teguria** [IBVSoftware/CollaBoard-Feedback#43]
Surface Pro 4 working with Surface Hub
Time: 8.12 Date: 27/01/2017

Working on project, opened several tiles, PDF files, Grid Libraries, Library.
The project keeps on working on the HUB, the client got the red error message (but I can still see the tiles moving behind the error message

Project: 3205
Key: a5qxr

v 1.2.7.0

**Comment by gsantopaolo** [comment]
unfortunately this does not tell us a lot until it is not reproducible.
does this happens everytime? can we check if we can reproduce it when we will meet?

**Comment by gsantopaolo** [comment]
@teguria we need a pattern to reproduce ti

**Comment by teguria** [comment]
It was @mtg1986 Surface that had this issue, the other 2 laptops worked fine. Again, another feature we need to test with multiple users logged in on the same project at the same time.

**Comment by gsantopaolo** [comment]
@teguria  yes, you must perform lots of test with multiple devices on the same project.
Is it still reproducible or can we close?

**Comment by agorog** [comment]
1.3.12.0 or earlier fixed
