### ISSUE TITLE
While zoom out Canvas and moving tiles, background text appears

### ISSUE THREAD

**Issue by tamarawasser** [IBVSoftware/CollaBoard-Feedback#430]
SfHub
Cube
HP Spectre
08.11.2017 / 10:36

open a new project
zoom in the canvas 
move the info tile around
"welcome" text on the canvas appears

[Presentation1.pptx](https://github.com/IBVSoftware/CollaBoard-Feedback/files/1453286/Presentation1.pptx)

**Comment by corradocavalli** [comment]
@tamarawasser The "project is empty..." text is now back. It will appear when project has no tiles nor ink, as soon as user starts inking or after adding a tile it will fade out.

**Comment by tamarawasser** [comment]
@corradocavalli right, text disapear when I add a tile, but when project is empty and I open Info or Settings it looks now like this

![123](https://user-images.githubusercontent.com/25382402/32551709-b1e139a8-c491-11e7-946b-656e7f1f48bd.jpg)

**Comment by tamarawasser** [comment]
@corradocavalli 
create a new project - text on welcome screen is visible
open search - text is over search tile
search for zurich - text still over search tile
map from zurich opens - text is over the map now

![startscreen text](https://user-images.githubusercontent.com/25382402/32596815-e6fe6162-c534-11e7-9b8b-27caf0ca988f.JPG)

**Comment by corradocavalli** [comment]
@tamarawasser The text has been removed in newer versions, closing.
