### ISSUE TITLE
Tile Rotation not allowed - Tile rotated

### ISSUE THREAD

**Issue by tamarawasser** [IBVSoftware/CollaBoard-Feedback#431]
SfHub
10.11.2017 / 09:08

Settings: tile rotation is not allowed
create a new project
load some tiles
take a picture with the camera
picture is rotating - other tiles not
after a while (didn't found out when yet) photo is not rotating anymore

![tile rotation](https://user-images.githubusercontent.com/25382402/32648656-28268b70-c5f7-11e7-919b-9c8a9eeb86d2.jpg)

**Comment by corradocavalli** [comment]
@tamarawasser unfortunately can't reproduce it, open it again when (and if it reappears)
