### ISSUE TITLE
Collaboard Crashes when registering a license

### ISSUE THREAD

**Issue by gsantopaolo** [IBVSoftware/CollaBoard-Feedback#432]
From an unregistered collaborad version go to info -- > license and add a valid registration key.
Application crashes
![image](https://user-images.githubusercontent.com/9937149/32782759-bef30e5c-c949-11e7-94a9-59f6944908c4.png)
![image](https://user-images.githubusercontent.com/9937149/32782778-cf76d8ee-c949-11e7-866d-76b59aecaef6.png)

**Comment by corradocavalli** [comment]
@gsantopaolo / @tamarawasser  I have successfully registered using the license you provided via Skype.
Are there other  surrounding aspects to consider for bug investigation (DEV vs PROD, else...) ?

![image](https://user-images.githubusercontent.com/5617938/32785680-66a4af22-c952-11e7-8650-3923bc05c501.png)

**Comment by corradocavalli** [comment]
@tamarawasser Fixed in v 1.4.21

**Comment by corradocavalli** [comment]
@tamarawasser fixed in v1 1.4.21

**Comment by tamarawasser** [comment]
It's working in Dev. Environment for AllDevices and TeamFamily. Will check in Live-Environment when new version is published.
