### ISSUE TITLE
right order after upload - wrong order after moving tile

### ISSUE THREAD

**Issue by tamarawasser** [IBVSoftware/CollaBoard-Feedback#434]
SfHub
HP Spectre
16.11.2017 / 14:16

Create a new project on SfHub
Join Project with HP Spectre

On SfHub: 
load PDF Doc. in Project

On HP Spectre: 
load 10 Excel-Files in Project

Order of the tiles looks the same on Hub and on HP Spectre
![01](https://user-images.githubusercontent.com/25382402/32893219-f610d3a2-cad8-11e7-97dd-8b6c2fe3fbbf.JPG)

On HP Spectre:
move the PDF to another part of the canvas

Order of the tiles looks now different. 
HP Spectre:
![02hps](https://user-images.githubusercontent.com/25382402/32893284-2f4bcb40-cad9-11e7-8f1b-13bf9748be7a.JPG)

SfHub
![03sfh](https://user-images.githubusercontent.com/25382402/32893298-381d1332-cad9-11e7-9ec9-dbbfa00c3cad.jpg)

**Comment by tamarawasser** [comment]
@corradocavalli when I upload different files, word, excel, pdf, at the same time, the order on SfHub is completely different than on the HP Spectre. 
[Presentation2.pptx](https://github.com/IBVSoftware/CollaBoard-Feedback/files/1478674/Presentation2.pptx)

**Comment by corradocavalli** [comment]
@tamarawasser As discussed together tiles aren't duplicated, it is a visual effects due to tiles being stacked.

**Comment by tamarawasser** [comment]
@corradocavalli what we discussed was about the upload of the tiles. They appear twice while uploading but when upload is done, they are in the project once. This issue is closed. 
But here the problem is the order of the tiles after moving a tile.

**Comment by tamarawasser** [comment]
tried again with a SfHub, HP Spectre and SfBook. After moving the PDF File on the HP Spectre, the order of the Excelfiles on the SfHub and the SfBook is different than on the HP Spectre

**Comment by gsantopaolo** [comment]
@corradocavalli  this needs to be verified and fixed please

**Comment by mtg1986** [comment]
We could reproduce the first part of this Bug. 

1.Upload PDF on Hub
2.Upload many Excel files on Surface Pro 
3.Move PDF
-->There is a very small dislocation happening on one of the excel tiles. 

Tested with 2.0.41 

@corradocavalli : As the dislocation is very marginal users may not even spot it. How should we proceed, is this something that might cause problems?

**Comment by gsantopaolo** [comment]
so we can close also this
