### ISSUE TITLE
Not able to open an office doc on the Surface Hub

### ISSUE THREAD

**Issue by tamarawasser** [IBVSoftware/CollaBoard-Feedback#436]
SfHub
HP Spectre

Project Code: 3203
Project Key: i2qhl

![capture](https://user-images.githubusercontent.com/25382402/32896367-24fa1156-cae3-11e7-8d93-1776292ad50d.JPG)

All the tiles with a red circle can be opened on the HP Spectre but not on the Surface Hub. The content of each excel is the same, the content of each word is the same, the content of each power point is the same.

**Comment by corradocavalli** [comment]
@tamarawasser At the moment the projects behaves correctly, is there any additional step we can try to reproduce it?
