### ISSUE TITLE
Feature Request: CollaBoard Key and Code

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#438]
CollaBoard Key has only small letters. When I want to add a key on Surface Hub, the first letter is by default always capital (when I type over the keyboard) . Therefore the request would be to have always a capital letter in the first position of the key (if it is a letter and not a number).

Small thing, but would improve usability a bit.

**Comment by corradocavalli** [comment]
@mtg1986 Since build 2.0.3 key will be automatically converted to lowercase as you type.
