### ISSUE TITLE
Tiles don't show on clients after project opened on the Hub

### ISSUE THREAD

**Issue by teguria** [IBVSoftware/CollaBoard-Feedback#44]
8.16
Clients: Surface Pro 4, HP Spectre and Surface Pro 4

2 new clients join the project (while the project is still opened on the Hub). The issue is that the 2 clients don't see the same things which are a PDF and a Sticky Note.
![whiteboard](https://cloud.githubusercontent.com/assets/19929395/22363250/50131fec-e469-11e6-8705-61ef57ba6aa9.png)
![client](https://cloud.githubusercontent.com/assets/19929395/22363261/6caa4b6c-e469-11e6-8525-fee8bedd940a.png)

Project: 3205
Key: a5qxr

**Comment by gsantopaolo** [comment]
@teguria we need a pattern to reproduce it

**Comment by teguria** [comment]
Another one that needs to be re-tested with multiple laptops logged in on the same project at the same time

**Comment by gsantopaolo** [comment]
we need a feedback please

**Comment by teguria** [comment]
will test it tomorrow with more than one client

**Comment by gsantopaolo** [comment]
@teguria  15 days delay... :)
