### ISSUE TITLE
Panda on SfHub while uploading project and working in Word

### ISSUE THREAD

**Issue by tamarawasser** [IBVSoftware/CollaBoard-Feedback#441]
SfHub
23.11.2017 / 11:05

Project Code: 11204
Project Key: ea3eg

Open CB on SfHub
Use Team Device
Load Project
While project is loading open File Explorer
Open Word File with License Key
Copy License Key
Go back to CB
CB crashed 
![panda hub](https://user-images.githubusercontent.com/25382402/33167608-5727881a-d03e-11e7-8fb6-49e1b8a606bc.jpg)

Tried to reproduce. Doesn't happen anymore.

**Comment by tamarawasser** [comment]
@corradocavalli  This bug just happen in this project. I tried it several times with any other project and also with creating new projects. This message never appears.

**Comment by gsantopaolo** [comment]
@corradocavalli can you please check that particular project?
