### ISSUE TITLE
Cube i8-L crashes when download CollaBoard from Store

### ISSUE THREAD

**Issue by tamarawasser** [IBVSoftware/CollaBoard-Feedback#442]
Cube i8-L
23.11.2017 / 12:07

Download CollaBoard from Store
Open CollaBoard
CollaBoard crashes

![cube](https://user-images.githubusercontent.com/25382402/33170007-fb84f426-d046-11e7-9c6c-d12aeaf1685d.jpg)

**Comment by tamarawasser** [comment]
Happen also on Marina's Surface Pro 3

**Comment by tamarawasser** [comment]
Also happened with Manuels ASUSTeK COMPUTER inc. UX390UAK
![screenshot bug](https://user-images.githubusercontent.com/25382402/33266900-a0d3a340-d377-11e7-936a-8c6cc3ae4cbf.png)

**Comment by gsantopaolo** [comment]
@tamarawasser can you please verify that @corradocavalli cards of this while in Zurich? Thanks

**Comment by tamarawasser** [comment]
@corradocavalli and me will test this next week here in Bon
