### ISSUE TITLE
Collaboration was not working

### ISSUE THREAD

**Issue by tamarawasser** [IBVSoftware/CollaBoard-Feedback#444]
Same project open (10986 / hq8ed) on two SfHubs and a SfBook
- one Hub is the customer / one Hub IBV and Michi's SfBook

User Icon from customer is not visible on SfHub from IBV and SfBook from Michi
Customer is working in the project on his SfHub. Michi is not able to see the changes on the SfBook and SfHub. 
When Michi loads the project new, adjustments from the customer are not visible

We'll try to replicate on Tuesday @Microsoft in Wallisellen while being connected through Skype for Business.

**Comment by tamarawasser** [comment]
Tried to reproduce
SfHub / SfBook / HP Spectre
27.11.2017 / 15:54
Project Code: 11267
Project Key: ivkv3

There are various tiles in the project. On all devices the same order and the same content. 
Start record audio on HP Spectre
While audio is recording I started inking on Sticky Notes on SfBook - Ink is not visible on SfHub and HP Spectre
Moved Sticky Notes on SfBook - not visible on HP Spectre and SfHub
After record audio is finished I sync projects on all devices - on SfBook I got a Panda and was forced to load the project again. 
All projects on all devices looks different: 

HP Spectre
![hp spectre](https://user-images.githubusercontent.com/25382402/33272798-8ff93dbe-d38b-11e7-9c30-7c722e4ff3b2.JPG)

SfHub
![sfhub](https://user-images.githubusercontent.com/25382402/33272827-b14f78fc-d38b-11e7-89bf-024a5e263671.jpg)

SfBook
![sfbook](https://user-images.githubusercontent.com/25382402/33272849-c642b09e-d38b-11e7-9ae6-ab392b6ac8fc.JPG)

**Comment by tamarawasser** [comment]
Other scenario with two SfPro, SfHub and HP Spectre
29.11.2017 / 10:25
Project Code: 11354
Project Key: 9txqu

Create new Project on SfHub
Join project with the other devices (HP Spectre and two Sf Pro)
Upload 5 Sticky Notes on the HP Spechtre
Upload 5 PDF on one SfPro
Upload 4 Excel-Files on SfHub - edit one excel file - save and close - connect Excel files
Upload 4 Word-Files on SfHub - edit one Word file - save and close - connect Word files
Ink on Canvas on the SfHub
Create Grid Library on SfPro
upload 5 Sticky Notes on SfPro, change color and move them into the Grid Library
On the other SfPro two sticky notes are outside of the library and not colored: 
![001](https://user-images.githubusercontent.com/25382402/33367941-7aed31d0-d4f0-11e7-8603-249e57908e7b.JPG)

on the other devices it looks like this: 
![all other devices](https://user-images.githubusercontent.com/25382402/33367958-88296bac-d4f0-11e7-8b46-617e47636e88.JPG)

on the SfPro with the two sticky notes outside of the library: go to settings and sync project. Panda while sync. 
![panda](https://user-images.githubusercontent.com/25382402/33368018-b11671d6-d4f0-11e7-8bea-f43a81edc5cb.JPG)

click "ok" on panda message. Launch CollaBoard again, open project, Stickys are not in the right color in the library

**Comment by tamarawasser** [comment]
@corradocavalli @gsantopaolo looks like this happen just when moving or working on stuff while project is sync. Did the follow:
HP Spectre, SfHub and SfBook
Project Code: 11362
Project Key: 1t93e
Open project on SfHub
Upload some tiles on each device - all tiles in same order on all devices
![001_before sync](https://user-images.githubusercontent.com/25382402/33372895-dbd5aab8-d4ff-11e7-9afc-08c68d108702.JPG)

SfBook - open settings and start sync
While sync on SfBook, start moving tiles from the canvas to the library - happen in realtime on the SfHub
After SfBook is done with sync project looks different than on HP Spectre and SfHub regarding order of the tiles.

SfHub and HP Spectre
![002_hp spectre](https://user-images.githubusercontent.com/25382402/33372966-2763cb5e-d500-11e7-8e36-4e0d9b0bbeb4.JPG)

SfPro
![003_sfbook_after sync](https://user-images.githubusercontent.com/25382402/33372970-2eeaaf0a-d500-11e7-9ba1-0fb059f1ee7f.PNG)

Question: when a CollaBoard Project is open on a device, the project sync automatically, right? What when the project is in sync automatically and somebody else is working in the project but on another device, does this problem happen then too? I mean the person with the device who was sync won't see the changes the person with the other device did while sync, right?

**Comment by gsantopaolo** [comment]
@corradocavalli I think there is a way to fix that, ask me to talk to you about server asking a user participating project to send his tile order to others...

**Comment by gsantopaolo** [comment]
closing because this is too old!!!
