### ISSUE TITLE
new start screen bug when demo

### ISSUE THREAD

**Issue by gsantopaolo** [IBVSoftware/CollaBoard-Feedback#446]
got this bug 
![image](https://user-images.githubusercontent.com/9937149/33278715-b5fdab60-d39c-11e7-8bc6-db23d9954b57.png)
when let collaboard on start screen for a period of time

**Comment by corradocavalli** [comment]
@tamarawasser  @gsantopaolo should be fixed in v 2.0.8

**Comment by gsantopaolo** [comment]
@tamarawasser to test it licensing popup timer needs to be rised without error ask @corradocavalli  how much time to wait on start screen
