### ISSUE TITLE
Can't load PDF files

### ISSUE THREAD

**Issue by teguria** [IBVSoftware/CollaBoard-Feedback#447]
v. 2.0.8.0
HP Spectre

Started with a template
Tried to load a PDF file (14 KB) -> I got the message "maximum size of 15 MB)
Tried with different PDF files, same outcome

**Comment by corradocavalli** [comment]
@teguria please send me that pdf file via mail, thx.

**Comment by teguria** [comment]
@corradocavalli it's all of them. I tried with 10 different ones

**Comment by tamarawasser** [comment]
#484
