### ISSUE TITLE
Test if mail are sent

### ISSUE THREAD

**Issue by gsantopaolo** [IBVSoftware/CollaBoard-Feedback#448]
@tamarawasser  please verify if when a new user applies for a evaluation request if he got the email with the license key or not.
If not add a bug

**Comment by tamarawasser** [comment]
@gsantopaolo @teguria @mtg1986 
Guys, we already talked about this in a Marketing and Sales Meeting. At the moment there is no email sent to the new eval user. We have to define the content of this email. The user doesn't need any eval license key, so we won't send this huge key by email.

**Comment by gsantopaolo** [comment]
@mtg1986 need to talk about email to be sent via you provider

**Comment by mtg1986** [comment]
@gsantopaolo 
Try to update the E-Mailtemplate from sendgrid to make it GDPR compliant. Somehow I cant update the email template. I get error messages from sendgrid. 
How much effort would it be to do it over Mailchimp?

**Comment by mtg1986** [comment]
We discussed this in the management meeting. Fixing the mails we send out is on the to-do list.

**Comment by gsantopaolo** [comment]
so this can be closed
