### ISSUE TITLE
New start screen: Login by using QR Code on SfHub not possible

### ISSUE THREAD

**Issue by tamarawasser** [IBVSoftware/CollaBoard-Feedback#449]
new version 2.0.9
SfHub
30.11.2017 / 13:50
Project Code: 3270
Project Key: fhi4a

created a project on HP Spectre
take a picture of the QR Code
launch CB on SfHub
chose "load project"
tried to load project with QR code - looks like QR Code is readed but project doesn't open.

@corradocavalli

**Comment by corradocavalli** [comment]
QR Code login has been rewritten and look like working fine.
Closing since it also refers to old version of start screen
