### ISSUE TITLE
Clients show different tiles but not all of them

### ISSUE THREAD

**Issue by teguria** [IBVSoftware/CollaBoard-Feedback#45]
Date: 27.01/2017
Time: 08.23
Hub, Surface Pro 4, Surface Pro 4, HP Spectre

Hub shows more tiles than the clients. Also, clients show different tiles (one client shows a PDF and not a sticky, another one shows the sticky but not the PDF
Code: 3206
Key: 36cqk
![hp spectre](https://cloud.githubusercontent.com/assets/19929395/22363341/1b2832ee-e46a-11e6-88bc-cde7d3ad6b75.png)
![surface pro 4](https://cloud.githubusercontent.com/assets/19929395/22363363/35b28768-e46a-11e6-86fe-94bb3e02d65b.PNG)
![whiteboard](https://cloud.githubusercontent.com/assets/19929395/22363377/4eefffc6-e46a-11e6-8ef0-7bd01e6735fb.png)

**Comment by gsantopaolo** [comment]
Hi we need a pattern to reproduce it, otherwise is nearly impossible to understand the problem

**Comment by gsantopaolo** [comment]
@teguria can you give us a pattern to reproduce that issue?

**Comment by teguria** [comment]
I think we need to test it when we have several users logged in in the same project. We need to test it multiple times to see if there is a pattern

**Comment by gsantopaolo** [comment]
8 days are passed, please we need to know the status of this
