### ISSUE TITLE
New start screen - Reset project Key not to be modal pop up

### ISSUE THREAD

**Issue by gsantopaolo** [IBVSoftware/CollaBoard-Feedback#451]
it has not to be a modal pop up for the whole canvas but only for the item in witch it is contained
![image](https://user-images.githubusercontent.com/9937149/33489586-9ad4fd78-d6b4-11e7-82b3-b3ae2ac7f8ec.png)

same for response message
![image](https://user-images.githubusercontent.com/9937149/33489592-a0f62056-d6b4-11e7-8c81-09a14f05be08.png)

**Comment by gsantopaolo** [comment]
@corradocavalli did you adjusted this, if yes please close

**Comment by gsantopaolo** [comment]
@corradocavalli  is this something we can fix fast or not? if not label it as enactment and save for later development

**Comment by corradocavalli** [comment]
Fixed in 2.0.14

**Comment by mtg1986** [comment]
Tested with 2.0.24. I think it is ok, therefore closing the bug.
