### ISSUE TITLE
New start screen: adjust project description not possible

### ISSUE THREAD

**Issue by tamarawasser** [IBVSoftware/CollaBoard-Feedback#453]
go to load project
click on edit
change project description
click on okay
error message appears

![capture](https://user-images.githubusercontent.com/25382402/33552696-2f1c0d8a-d8f6-11e7-84b6-9e38585b5af7.JPG)

**Comment by tamarawasser** [comment]
@corradocavalli edit project is possible when I'm logged in with my MS Account or Facebook. When I try with twitter it doesn't work. means that I receive the "oops, something went wrong... message". Login by using google is not possible anyway (check issue 457)

**Comment by tamarawasser** [comment]
@corradocavalli sorry, something wrong here. I'm logged in with my MS Account now and wanted to adjust a project description and received the message again. "Oops, something went wrong....."

**Comment by corradocavalli** [comment]
Tested with different accounts, everything works fine, closing.
