### ISSUE TITLE
New start screen: screen on SfPro and HP Spectre looks different

### ISSUE THREAD

**Issue by tamarawasser** [IBVSoftware/CollaBoard-Feedback#455]
Launch CB on HP Spectre
![hps](https://user-images.githubusercontent.com/25382402/33560007-dc7e0c86-d90e-11e7-967b-9de5047e33bd.JPG)

Launch CB on Surface Pro
![sfp](https://user-images.githubusercontent.com/25382402/33560022-e4c6dc42-d90e-11e7-9912-85a029df1618.JPG)

**Comment by gsantopaolo** [comment]
Too old
