### ISSUE TITLE
New start screen: back to login when use "Enter"

### ISSUE THREAD

**Issue by tamarawasser** [IBVSoftware/CollaBoard-Feedback#459]
Login with MS Account
Enter email address
choose work- or school account
Enter password
![001](https://user-images.githubusercontent.com/25382402/33563974-a4a6a7b8-d919-11e7-9b17-baddd22bcedd.JPG)

when I click on okay, I'm logged in in CB
![002](https://user-images.githubusercontent.com/25382402/33563990-b2f1bdf8-d919-11e7-96fd-51269bcdc3d6.JPG)

when I confirm by click on enter, I'm back to login again
![003](https://user-images.githubusercontent.com/25382402/33564014-c3ed3452-d919-11e7-9cef-13d59e06f1d0.JPG)

**Comment by corradocavalli** [comment]
Fixed.
