### ISSUE TITLE
PDF behaviour not correct

### ISSUE THREAD

**Issue by teguria** [IBVSoftware/CollaBoard-Feedback#46]
When the tile header disappears on a PDF (whether it's horizontal or vertical), as long as the header disapperars a black header appears in the PDF at the bottom of it. Tested with several PDFs.

Also, when the header disappears from the PDF, the content somehow zooms in

Project Code: 3208
Project Key: f7rx2

Tested at 8.29, 27/01/2017 on Surface Hub
![screenshot](https://cloud.githubusercontent.com/assets/19929395/22363483/f48169a2-e46a-11e6-8f64-9ed3bf247ee0.PNG)

**Comment by mtg1986** [comment]
In 1.2.8.0 same behaviour

**Comment by gsantopaolo** [comment]
fixed thanks
