### ISSUE TITLE
CB says I'm not connected to the Internet with VPN

### ISSUE THREAD

**Issue by teguria** [IBVSoftware/CollaBoard-Feedback#460]
v: 2.0.8.0
HP Spectre

I launched CB while VPN activated
CB said I'm not connected to the Internet but I am (everything works)

I logged out from VPN and everything works
(reproducible bug)

**Comment by corradocavalli** [comment]
I had a similar problem but in reverse, i was able to use Collaboard only when connected via VPN otherwise i was having the "missing internet" connection issue.
At the end it was a wrong configuration of my machine causing KeepAlive to fail.
Tested now with IBV VPN and everything works fine, can you try again please?

**Comment by tamarawasser** [comment]
@teguria Please check if it's fixed. I can't connect to VPN when I'm in house.

**Comment by gsantopaolo** [comment]
@teguria  can you check this out?

**Comment by teguria** [comment]
Just checked with a new device but same VPN (ours) and connected through the phone. I'm still getting the same message about internet connection. It would be great to test this with another VPN to see if the issue is within our VPN.

**Comment by teguria** [comment]
Tested with the new version, same issue happening

**Comment by mtg1986** [comment]
Tested with 2.0.14 issue still there.

**Comment by mtg1986** [comment]
Tested with 2.0.20 Behaviour is like that: 
1.Open CollaBoard 
2.Connect to VPN
3.When in the strat screen, not the messsage about the internet connection comes, but another message that something is wrong. 

![image](https://user-images.githubusercontent.com/19570958/39955123-52eab62a-55ca-11e8-80e9-964d59dae076.png)

**Comment by mtg1986** [comment]
Tested this again with 2.0.41 and using VPN connecting and CollaBoard and there is no issue. 
Tested it on Surface Pro with Windows VPN.
Therefore I close this bug.
