### ISSUE TITLE
Tile locked when exiting a project

### ISSUE THREAD

**Issue by teguria** [IBVSoftware/CollaBoard-Feedback#461]
v 2.0.8.0

When someone exits the project, I think it would make sense to unlock all the locked tiles automatically

**Comment by gsantopaolo** [comment]
It should be already like that. @corradocavalli can you check please?
Problem is if collaboard crashes but this is something planned for being developed...

**Comment by corradocavalli** [comment]
Tested now: User is warned about unsaved tiles, if he still confirms exit, tiles are unlocked and unsaved content lost.
Closing.
