### ISSUE TITLE
Sync Issues on Prowise Screen 

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#462]
With two devices there is some trouble regarding the sync in real-time. 
As this comes from a partner we do not have much more information than just the Machine-ID. May be this helps already to figure out where the problem could be.

![image](https://user-images.githubusercontent.com/19570958/34950608-e69bc804-fa13-11e7-8e6a-49c346d0111e.png)

![image](https://user-images.githubusercontent.com/19570958/34950616-ef35cbe0-fa13-11e7-8031-7f3cbc17f8aa.png)

Project: 
12186
ptw6d

**Comment by corradocavalli** [comment]
If you edit a tile on Prowise screen do you see it locked on other machines?
Is the problem related only to real time inking? Other operations like moving tiles, inking on a tile or adding/deleting tiles are syncronized on other machines as well?

On 18 Jan 2018, at 08:44, Michael Görög <notifications@github.com<mailto:notifications@github.com>> wrote:


I tested this again and here is an issue that we cannot show real-time collaboration between two screens.

Setting is like that:

1.CollaBoard is opened on three devices (two prowise screens and one Surface Pro)
2.If I ink on the Surface Pro I see the changes in real-time on all devices.
3.If I ink ProWise Screen Nr.1 I do see the changes on the Surface Pro, but not on the other ProWise Screen.

What can we do to figure out what the problem could be?

**Comment by corradocavalli** [comment]
Prowise device not longer here in Bonstetten
