### ISSUE TITLE
Lost inked text on Canvas

### ISSUE THREAD

**Issue by tamarawasser** [IBVSoftware/CollaBoard-Feedback#463]
Surface Pro 

Project Code: 12240 / Project Key: bht4s
Project description: Marketing Meeting 15.01.2018

I created this Project at around 2.45pm. Project was open and I went to a Marketing Meeting. Just me was in this Project, nobody else had key and Code. 
I worked in the Project while the Meeting until around 4.30pm. 
I just inked on the Canvas. I didn't upload any tiles. 
While I went back from the Meeting to my Office, CB closed itself. 
When I reopen the Project most of the text was not here anymore. Around a quarter is full with text but I filled the whole Canvas with text. So 3 quarter of my text is missing.

**Comment by tamarawasser** [comment]
@corradocavalli think I was able to reproduce this: 
open a new Project on my Surface Pro
Project Code: 12873
Project Key: 1jemf
Start ink on the background
disconnect from WLAN
continued inking
connect with WLAN again
close CollaBoard
open CollaBoard (connected with WLAN again)
All the ink I inked while not connected to the WLAN is not visible anymore. 

I think exactely this happened in my case from the 15th of January. I was in Michi's office and Michi's office is connected to another Hotspot than my office, because I'm too far away from the Hotspot Michi's office is connected to. So I think that on my way from Michi's to my Office my deviced changed Hotspot and  I was not connected for a while and this was the time my last ink get lost. Possible?

**Comment by tamarawasser** [comment]
I created this Project at IBV yesterday in the afternoon on my Surface Pro:
Project Code: 12942
Project Key: a73i5
When I stoped working in the Project, it looked like this: 
![yesterday](https://user-images.githubusercontent.com/25382402/36135623-b0bed480-108c-11e8-9cca-6eb48af11892.JPG)

This morning Login to the Project from home. Except "Maria", all the other names on the sticky notes are missing:
![missed ink](https://user-images.githubusercontent.com/25382402/36135638-cc5268a6-108c-11e8-8801-76ffdf77149b.JPG)

**Comment by corradocavalli** [comment]
I tried with same project and looks good here,can you please try to synchronize the project?

**Comment by tamarawasser** [comment]
Yes, I recreated the Project because I needed it. I tried to sync before recreating, but it doesn't work. 
I'm doing a test. I'm in the Office now and I created a Test Project with ink on canvas and on sticky notes. When I'm back home I will open the Project and will check if all ink is still there. I'll let you know.

**Comment by tamarawasser** [comment]
Loged in to the test Project from home. Looks good. I go ahead trying to replicate.

**Comment by gsantopaolo** [comment]
@tamarawasser  any news?

**Comment by corradocavalli** [comment]
Closed since duplicated of #524
