### ISSUE TITLE
Opening Project on virutal machine on Mac Book

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#464]
We get some error messages when we try to create or join a project on this special machine. 

CollaBoard can be started, the project can be loaded but then there is an error message. Behin the error message the content of the project is shown but we are forced to close CollaBoard. It seems to be an intiallizing error.

<img width="388" alt="error1" src="https://user-images.githubusercontent.com/19570958/35036909-2091409e-fb76-11e7-852e-29a15ce873ac.png">
<img width="882" alt="error2" src="https://user-images.githubusercontent.com/19570958/35036910-20d0be4a-fb76-11e7-85e5-48e539d4aed6.png">

**Comment by gsantopaolo** [comment]
@corradocavalli this is something we have to test. Make sure when you'll be here gianluca has to be there as well...

**Comment by gsantopaolo** [comment]
@corradocavalli  you can ask @kasuken help on this...

**Comment by corradocavalli** [comment]
We'll fix this when we'll move InkSurface to infinite size, DPI trick seems not to work VM.
