### ISSUE TITLE
Start Screen - Icon Stays

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#468]
After log-in nd scrolling down the icon stays in front. 
Tested on Surface Pro

![icon-stays](https://user-images.githubusercontent.com/19570958/35328057-77e5911c-00fb-11e8-9a10-2c4fa3ab4403.PNG)

**Comment by mtg1986** [comment]
![iconafterlogin](https://user-images.githubusercontent.com/19570958/35328107-9a7ed7ba-00fb-11e8-925f-2ab3eca11488.gif)

**Comment by corradocavalli** [comment]
Already fixed in next release.

**Comment by mtg1986** [comment]
Tested on Surface Hub, works now fine.
