### ISSUE TITLE
Text doesn't appear on a sticky note already opened

### ISSUE THREAD

**Issue by teguria** [IBVSoftware/CollaBoard-Feedback#47]
Hub with 3 clients connected (2 Surface Pro 4 and HP Spectre)
Date: 27/01/2017
Time: 8.37

Key: 3210
Code: xj6p6

Project opened on the Hub, created few tiles (sticky notes, pictures, PDFs, video recording) from all the clients. Typed something on a sticky from HP Spectre and saved it, re-opened from a Surface Pro 4, kept on typing -> saved -> last changes made didn't show up

**Comment by gsantopaolo** [comment]
that's not clear, can you elaborate and better describe how to reproduce it?

**Comment by gsantopaolo** [comment]
@teguria we need a pattern to reproduce ti

**Comment by gsantopaolo** [comment]
@teguria  we are waiting for your pattern...

**Comment by gsantopaolo** [comment]
?

**Comment by teguria** [comment]
hard to reproduce, we will do it again when we collaborate with multiple projects. Pls close it at the moment
