### ISSUE TITLE
Start Screen - Team Device Mode - Button Color

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#472]
When I launch CollaBoard in Team Device Mode all the all Buttons to open a project are greyd out.  The one to open a project with QR code has a blue border, but this is not clear for someone who is a new user for CollaBoard. May be we need to think about another Color instead of grey, if a button is active... 

![image](https://user-images.githubusercontent.com/19570958/35332727-4af3a4ee-010c-11e8-8734-1d66302dc031.png)

**Comment by corradocavalli** [comment]
Fixed in next release
