### ISSUE TITLE
Start Screen - Issue when not full screen mode

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#473]
If I have multiple Apps open on a Surface Hub, the start screen does not adjust optimal when changing the windows size in which CollaBoard is used. For exmaple the QR Code scanner dissapears when making CB very small. 

 

![image](https://user-images.githubusercontent.com/19570958/35332845-d86e5fda-010c-11e8-8a4a-ce79044b5376.png)
![image](https://user-images.githubusercontent.com/19570958/35332857-e4b3c92e-010c-11e8-9de2-549b3d5cd687.png)

**Comment by corradocavalli** [comment]
On new release QrCode will appear below Key and Code fields on narrow windows
![image](https://user-images.githubusercontent.com/5617938/35340634-ee4dc5f4-0123-11e8-8340-1a2b4904afdb.png)
