### ISSUE TITLE
Start Screen - Load Project with QR Code

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#474]
1.Load Project with QR Code
2.Close Project
3.Camera to load QR Code is not available anymore

Tested on Surface Hub, Team Device Mode

If I click on New project and go back to load project with QR code the camera works again. It just does not work after closing a project loaded with QR code or by typing in key and code.

![image](https://user-images.githubusercontent.com/19570958/35333113-cf5d6c0a-010d-11e8-97fc-81412a376631.png)

**Comment by corradocavalli** [comment]
Fixed in next release,please verify it.

**Comment by mtg1986** [comment]
Yes it is fixed. Tested on Hub and Surface Pro with 2.0.10
