### ISSUE TITLE
Start Screen - Create from Sample / template - Terminology & Button

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#475]
To create a project from a sample, I taped first always on the thumbnail to create it and not on the button "Load". 

Question is do we need this button? And if yes does it have the right text? 

We say "Create a project" then "From Sample" and then a button where it says load. But I want to create one not to load. Is a conceptual questions about what is easier for the user..

![image](https://user-images.githubusercontent.com/19570958/35333244-4ee07d5a-010e-11e8-8b9f-09e35619681f.png)

**Comment by corradocavalli** [comment]
Terminology unified and now project can be created /opened even tapping on the image.
