### ISSUE TITLE
Button vs. Icon Team Edition

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#476]
In the Start Screen I have a different Icon in the button for the team edition compared to when I am in a project. 

For me it would make more sense to have on the Start Screen the Surface Hub icon in the button. Then we also do not need to explain what team mode is. It is just then the Hub mode. As long as the Hub is the only device with Windows Team edition, I think this would be ok.

![image](https://user-images.githubusercontent.com/19570958/35333464-273bbfa2-010f-11e8-8b72-ef213eeca980.png)

**Comment by corradocavalli** [comment]
Agreed,
I need a XAML version of that icon, already asked Florian to provide it, long time ago, can you push it?

**Comment by mtg1986** [comment]
Perfect. Can you send him an E-Mail cc me and ask, if he can do this until tomorrow lunchtime?

**Comment by gsantopaolo** [comment]
Agree, @corradocavalli have you sent the request for the icon to florian?

**Comment by corradocavalli** [comment]
Yes, @mtg1986 did it few days ago.

**Comment by corradocavalli** [comment]
![image](https://user-images.githubusercontent.com/5617938/35744769-770b8e0c-0841-11e8-95da-6d3670eb86d8.png)

Since got no news I've temporarily replaced the icon with a png of a surface hub.

**Comment by tamarawasser** [comment]
@mtg1986  Michi, we start working with SCS now and they run CollaBoard on all their Prowise Devices. Should we really use the SfHub Icon here?

**Comment by mtg1986** [comment]
Yes we should use the Surface Hub Icon, this makes sense, as Prowise is not running the same version as on Surface Hub.
