### ISSUE TITLE
Start Screen - Machine ID

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#477]
On Hub in Team Edition and also in personal mode I do not see the Machine ID: 

![image](https://user-images.githubusercontent.com/19570958/35333620-b0eec424-010f-11e8-924c-98927a58e5f3.png)

**Comment by corradocavalli** [comment]
Is Collaboard full screen? left area is scrollable, can you see it if you scroll up?

**Comment by mtg1986** [comment]
I did not understand that it is scrollable. This is not clear for the user. Yes it was in Full Screen and if I scroll down I can see the Machine ID. 
Here the questions is, if we can make this more intuitive for the user?

**Comment by corradocavalli** [comment]
In full screen it should be visible, at least on hub that has the same resolution as the machine I'm using now
we can let scrollbar appear in case

**Comment by gsantopaolo** [comment]
@corradocavalli if you read the fds carefully it's clearly written that on non team family start screen should be full screen...

**Comment by corradocavalli** [comment]
@gsantopaolo is exactly like described in FDS.

**Comment by gsantopaolo** [comment]
@corradocavalli last time i saw it (2 days ago) on non team device the start screen wasn't full screen, did you canged it since then?

**Comment by gsantopaolo** [comment]
@corradocavalli  I've just downloaded latest bits and this is the result:

![image](https://user-images.githubusercontent.com/9937149/35624066-28f7dd2e-068e-11e8-96af-f506f90d3120.png)

![image](https://user-images.githubusercontent.com/9937149/35623963-bdf8ac88-068d-11e8-837f-f3e15ce32761.png)

**Comment by gsantopaolo** [comment]
@corradocavalli  my bad, i can confirm, it's full screen...

**Comment by corradocavalli** [comment]
You were having internal flag used to simulate Hub set ;-)
