### ISSUE TITLE
Start Screen - Log-Out Button and Text

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#479]
I am asking if we need this long text on the left side of the Log-Out Button? 
Everywhere we have icon and then the text below the icon. Please see in the picture a suggestion how it could be better and more consistent. 

![image](https://user-images.githubusercontent.com/19570958/35334227-ef8dceee-0111-11e8-913c-d02a980de6f8.png)

**Comment by corradocavalli** [comment]
Michi, 
AFAIK these design was agreed with you together with @gsantopaolo , I lost the count of how many times I've refactored this view.
How is it possible that we're still discussing about this after weeks of development?
Not saying that they're wrong, just that they should be carefully planned at right time.

**Comment by gsantopaolo** [comment]
@corradocavalli you are right tis happens because we are leaking a designer and me and @mtg1986 had to do this out of our field of expertise, then bugs games out of the design! Sorry for that.
I'll discuss this with @mtg1986 and we will came back to you...
Thanks

**Comment by corradocavalli** [comment]
Added text to Logout, Settings and License buttons.
