### ISSUE TITLE
Sticky Note doesn't show all the inking

### ISSUE THREAD

**Issue by teguria** [IBVSoftware/CollaBoard-Feedback#48]
Hub and Surface Pro on the same project

Create a new sticky note
Start inking (ink a lot)
Save it
Then enlarge the sticky note
You don't see all the inking but just part of it

If you start inking again and then save it, then all the inking shows up again.

Code: 3211
Key: k5vq0

**Comment by mtg1986** [comment]
Same Issue on 1.2.8.0

**Comment by gsantopaolo** [comment]
closing because this is better described on #58 that is the same bug
