### ISSUE TITLE
Upload files cause the 15 MB error message

### ISSUE THREAD

**Issue by teguria** [IBVSoftware/CollaBoard-Feedback#484]
v 2.108
HP Spectre

Everytime I try to upload a PDF or a jpg, I always get the error message "One or more files exceeded the maximum allowed size of 15 Mb". I tried loading older projects, create new projects from a template and create new projects and it always happens.
Gian suggested @corradocavalli to debug this machine when you'll be back in the office

**Comment by corradocavalli** [comment]
does it happen on that machine only?

**Comment by gsantopaolo** [comment]
@corradocavalli yes, we need to debug his machine because I suspect it happens only in particular circumstances. Remember bug with audio files happening only on my pc?

**Comment by tamarawasser** [comment]
Uploading files on my HP Spectre works without any issues

**Comment by gsantopaolo** [comment]
@teguria  can you confirm all that bugs happening only on your spectre are gone or not?

**Comment by teguria** [comment]
I can confirm these issues are happening only on my old Spectre. On my new one, issue not present

**Comment by gsantopaolo** [comment]
So @tamarawasser  next time do not close issue before being 100% sure please.
Thanks you

**Comment by gsantopaolo** [comment]
@teguria @corradocavalli we need to work on that once in zurich together. Did you already agree on a timeframe for doing that?

**Comment by teguria** [comment]
Yes, it's gonna be next week (between Monday and Tuesday). Then I will leave the laptop to the devs for further testing

**Comment by teguria** [comment]
I updated CB on this laptop and it says the version is obsolete. Now I'm reinstalling.

**Comment by teguria** [comment]
I still get the same issue with the new version but also the touch of this device doesn't work anymore so I guess I have some problems with it. I see if I can do a restore point check

**Comment by teguria** [comment]
No other way than resetting this laptop. It was too compromised by all the betas and installations. I'll let you know once it works again

**Comment by teguria** [comment]
problem solved on this laptop. No action needed
