### ISSUE TITLE
Login Buttons can be accessed on Start Screen

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#486]
1.Log-In on Surface Hub as Team
2.Tap on the location where the Google Login Button was on the Login-Screen before. The login-window opens. It seems that I can click on the Bottons that were displayed on the screen before.

Please see the zipped video for better explanaiton

[20180125_202451.zip](https://github.com/IBVSoftware/CollaBoard-Feedback/files/1665428/20180125_202451.zip)

**Comment by corradocavalli** [comment]
Fixed in next release,please check it again.

**Comment by mtg1986** [comment]
Yes it is fixed. Thanks.
