### ISSUE TITLE
CollaBoard crash

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#487]
I manged to crash collaboard by clicking around in the Start Screen. Try now to find repo-sequence.

Time 21:03 25/01/2018 

Second Crash: 21:05

Device: Machine ID: 54a3a2a6-e17e-7168-9ff8-e5d4d1f2fe43

**Comment by mtg1986** [comment]
Third crash with the new start screen. It seems sometimes it takes time to load the thumbnails of the projects and then it crashes...
15:13, Surface Hub, Version 2.0.11

**Comment by mtg1986** [comment]
I am not able to find a repo sequence, but I can demonstrate how it happens (by just randomly clicking all the different buttons...) How should we proceed to figure out why the start screen can crash?

**Comment by corradocavalli** [comment]
Should be fixed in build 2.0.12
