### ISSUE TITLE
Evaluation Version Text appearance

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#488]
1.Start CollaBoard
2.Use Team Mode 
3.Then you see for a very short period the text "Welcome to the evaluation version of CollaBoard". Then it disapperas and just says Hello. 

[CollaBoardEvalVersion.zip](https://github.com/IBVSoftware/CollaBoard-Feedback/files/1673426/CollaBoardEvalVersion.zip)

**Comment by corradocavalli** [comment]
Closing since we no longer have that start screen.
