### ISSUE TITLE
Enter wrong credentials - Text is overlapping

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#489]
When I enter wrong credentials to access a project the red message is overlapping with the black text and not readable. 

![image](https://user-images.githubusercontent.com/19570958/35513954-f8559a9c-0504-11e8-8abe-7c436e99c597.png)

**Comment by mtg1986** [comment]
After log-out and log-in again the red text stays altough I did not entered any new credentials. I can still click in the text-field for "Project-Code" but the text-field for "Project Key" is not accessible anymore. I can try to tab or click into it but nothing happens. 

Tested: Surface Hub
Version: 2.0.11

**Comment by corradocavalli** [comment]
Can you please explain how you entered "Hello" as project code? It is supposed to accept only numeric values.

**Comment by mtg1986** [comment]
I used voice commands ;)

**Comment by corradocavalli** [comment]
Good catch, fixed in next release.
