### ISSUE TITLE
Project on Phone

### ISSUE THREAD

**Issue by teguria** [IBVSoftware/CollaBoard-Feedback#49]
Tested on 3 Lumia 950 XL
Time: 8.53 Date 27/01/2017

Opened the same project 
Code: 3211
Key: k5vq0

When you turn the phone horizontally, the project crashes on all the phones
![wp_ss_20170127_0001](https://cloud.githubusercontent.com/assets/19929395/22363978/761936cc-e46e-11e6-839e-dc0180230c3d.png)

**Comment by gsantopaolo** [comment]
Phone compatibility is only for us internally, we do not support phone officially.
We support: Desktop., tablet and Team Family - Surface hub
