### ISSUE TITLE
Design: Project Code

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#490]
Project description and the button are on the same level, while code is not. Is there a specific reason for that? I think having everything on the same level would look nicer.

![image](https://user-images.githubusercontent.com/19570958/35514281-f78dc00c-0505-11e8-8c78-a2d96fe55eec.png)

**Comment by corradocavalli** [comment]
Michi,
Isn't evident that Title,project info and buttons are horizontally centered? 
Here's a sample
![image](https://user-images.githubusercontent.com/5617938/35514899-fc03c01c-0507-11e8-83dd-20458d3a0ce2.png)
Other kind of alignment would leave too much "dead space" around.

**Comment by mtg1986** [comment]
All clear, I see it now that it is horizontally centred. When having two very short project descriptions, like in the picture I added, it was not clear at the first glance.

**Comment by mtg1986** [comment]
So I think we can close this one...
