### ISSUE TITLE
Device ID should be renamed

### ISSUE THREAD

**Issue by teguria** [IBVSoftware/CollaBoard-Feedback#491]
I experienced with some customers that, when I request the device ID for the activation (although I always explain how to get it), they provide me the real device ID of that Surface Hub.
Can you please rename it to something more clear like "app ID" ?
Thanks

**Comment by gsantopaolo** [comment]
@mtg1986 @teguria wi well do.
Please provide us the correct term. I believe you are referring to MachineId

**Comment by corradocavalli** [comment]
In agreement with @gsantopaolo Machine ID is now exposed to user as "Application Id"
