### ISSUE TITLE
Surface dial on screen with cb radial menu 

### ISSUE THREAD

**Issue by gsantopaolo** [IBVSoftware/CollaBoard-Feedback#492]
Radial does not render well, needs to be tested

**Comment by corradocavalli** [comment]
There was some issues after all the changes we did when we moved stuff out of radial into toolbar.

**Comment by tamarawasser** [comment]
Not clear what I have to test here. Please let me know

**Comment by corradocavalli** [comment]
There was some issues with Surface Dial, just check if you can use the radial menu with Surface Dial.

Da: Tamara Wasser<mailto:notifications@github.com>
Inviato: venerdì 9 febbraio 2018 13:47
A: IBVSoftware/CollaBoard-Feedback<mailto:CollaBoard-Feedback@noreply.github.com>
Cc: Corrado Cavalli<mailto:corrado@outlook.com>; Assign<mailto:assign@noreply.github.com>
Oggetto: Re: [IBVSoftware/CollaBoard-Feedback] Surface dial on screen with cb radial menu (#492)


Not clear what I have to test here. Please let me know

**Comment by gsantopaolo** [comment]
@tamarawasser  any news about that?

**Comment by mtg1986** [comment]
Tested again on a Surface Pro with 2.0.28 works ok. Close the bug.
