### ISSUE TITLE
Export on Surface Hub (Feature Request: Share by E-Mail)

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#494]
Exporting a Tile on Surface Hub allows us at the moment only to save it locally. 
I am not sure if it is planned, but I think user will ask for share by E-Mail possibility of exported tile. 
Also something could be like share with the Whiteboard where to export direclty into the whiteboard.

**Comment by gsantopaolo** [comment]
This will be part of a new functionality that will be developed later on.
Please referto the chapter "sharing contracts" on our fds and if you have any suggestion feel free to ping me
