### ISSUE TITLE
Filename Exported Tile (Feature Request: More sophisticated name for exported tiles)

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#495]
At the moment the name of the File is just export.filetype. 

Idea: Adding name of tiletpye and project description. 

Example:
StickNote_MarketingProject2018

**Comment by gsantopaolo** [comment]
Agree but naming ahold be set up on configuration

**Comment by corradocavalli** [comment]
Can you elaborate more on "naming ahold be set up on configuration"

**Comment by gsantopaolo** [comment]
misspelling. ahold = should. It should be a a method in like public string GenerateExportedFileName(tiletype) and it returns the formatted name (config internally has the project id

**Comment by corradocavalli** [comment]
Done in next release.
