### ISSUE TITLE
Export Video: : Video File Not Found. 

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#496]
When I export a video, the filetype says: Video File Not Found.
Tested on Surface Pro 
Version: 2.0.2.12
30.01.2018 

![image](https://user-images.githubusercontent.com/19570958/35589157-2cb0dd0c-0603-11e8-969b-2ca82e790f61.png)

**Comment by corradocavalli** [comment]
Fixed
