### ISSUE TITLE
Help Video - Issue with Full Screen Mode

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#497]
When entering a Help Video in Fullscreen, sometimes the bottom bar disappears and won’t be there until you finished the video. You are stuck in the fullscreen mode. It is not possible to do anything in CollaBoard until the video has ended. Only solution is to close the app...

Tested on Surface Hub and Surface Pro. Need to show you this in person if not clear. 

Version: 2.0.12
30.01.2018

**Comment by corradocavalli** [comment]
Fixed
