### ISSUE TITLE
Load peoject with QR Code

### ISSUE THREAD

**Issue by gsantopaolo** [IBVSoftware/CollaBoard-Feedback#498]
When I try to load a project with the QRcode there is no way to switch camera and my default camera is the wrong one for this task.
It would be great to have a switch camera button

**Comment by corradocavalli** [comment]
I have investigated and unfortunately looks like that ZXing component doesn't offer an option to select the camera to use for scanning. It defaults to default one.

**Comment by tamarawasser** [comment]
Loading Project with QR Code is working very well on SfHub, SfPro and HP Spectre. Can I close this issue?
