### ISSUE TITLE
Search using Ink to textbox

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#499]
When you ink on the search bar, you can’t write under the line (screenshot). This works on every other input tile except for search. May be behaviour should be unified.

![image](https://user-images.githubusercontent.com/19570958/35766313-3509d6ea-08d6-11e8-988a-ea5eab75a605.png)

**Comment by corradocavalli** [comment]
Fixed in build 2.0.13
