### ISSUE TITLE
CollaBoard crashed while uploading pictures

### ISSUE THREAD

**Issue by tamarawasser** [IBVSoftware/CollaBoard-Feedback#50]
Date: 26th of January 2017
Time: 5 o’clock p.m.
Device: Surface Pro 4
Version: 1.2.7.0

Steps: 
creat a new project
upload pictures (40 pictures / 220’000 kb)
CollaBoard crashed during uploading the 40th pictures
Desktop became black and the arrow from the mouse blinked
couldn’t open CollaBoard again
opened the task manager to close CollaBoard
opened CollaBoard again and it was working error-free

**Comment by corradocavalli** [comment]
Hi Tamara,
Can you try creating a new project and uploading the same set of picture to see if it happens all the times? If so, please keep that set of pictures so that we can use for debug the issue.
Thanks

**Comment by tamarawasser** [comment]
Ciao Corrado

Okay, I will do that and let you know what happened.

Kind regards
Tamara

[IBV]<http://www.ibv.eu/>
Tamara Wasser | Marketing Coordinator
P +41-79-2590866

**Comment by gsantopaolo** [comment]
tested with 892 items and 175 mb... everything went well.. .until you provide a pattern to reproduce it I will close this...
