### ISSUE TITLE
Strange Behavior: New Start Screen

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#500]
Got the following Start Screen: 

![image](https://user-images.githubusercontent.com/19570958/35797537-509b182a-0a60-11e8-822e-03c99a6e75dd.png)

**Comment by corradocavalli** [comment]
Michi,
Can you please elaborate more? what does "Got the following Start Screen" means? 
When/How/What did you install?

**Comment by mtg1986** [comment]
We installed on Shalis old Surface. May be there was a testing version installed before, but now we got version 2.0.9.0 with this very strange Office 365 icons....

**Comment by gsantopaolo** [comment]
@corradocavalli  how is possible this to happen?

**Comment by corradocavalli** [comment]
That is an very old beta version, probably side loaded.
I've checked and the actual version available to beta users is 2.0.12, I'd suggest to reset that machine.

**Comment by tamarawasser** [comment]
Tested with version 2.0.13.0 on HP Specte, Surface Pro and Surface Hub. All good on all devices.
