### ISSUE TITLE
Order of icons QAT

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#503]
As Library and Grid Library are similar tiles, wouldn’t it make sense to have them not separated? Also audio recording and camera have some similarities.

![image](https://user-images.githubusercontent.com/19570958/36172591-a64a2368-1106-11e8-9446-c04d1ee65e2c.png)

**Comment by corradocavalli** [comment]
Make sense, I moved them closer.
