### ISSUE TITLE
Tile Rotation not allowed - Tile rotate

### ISSUE THREAD

**Issue by tamarawasser** [IBVSoftware/CollaBoard-Feedback#505]
Surface Pro
Version 2.0.13

Create a new Project
Go to Settings (tile Rotation is not allowed)
Create a Sticky Note - Sticky note is rotatable
Go to Settings - allow tile Rotation
Create a Sticky Note - Sticky note is rotatable
Go to Settings - disallow tile Rotation
Sticky Note is not rotatable anymore

Open search
search for Zurich (Image)
drag and drop Picture to canvas - Picture is rotatable
go to Settings - allow tile Rotation - disallow tile Rotation
Picture is not rotatable anymore

**Comment by corradocavalli** [comment]
I tried several times bug cannot reproduce it on my PCs.
Can you try on a different machine?

**Comment by mtg1986** [comment]
Closing this bug as it is a duplicate from #521
