### ISSUE TITLE
Small delay

### ISSUE THREAD

**Issue by teguria** [IBVSoftware/CollaBoard-Feedback#507]
HP NEW Spectre
v 2.0.13
I noticed a very tiny delay when I touch and I pinch to zoom. Same happens when I link once, in the same tile, and then I ink again on the same tile. I'm not sure if this is something related to my display (or my internet connection) but I wanted to let you know

**Comment by gsantopaolo** [comment]
@teguria does it happens only or your device or or  any other as well?

**Comment by teguria** [comment]
old spectre handed over to @corradocavalli this morning
