### ISSUE TITLE
Copy application ID

### ISSUE THREAD

**Issue by teguria** [IBVSoftware/CollaBoard-Feedback#508]
HP Spectre NEW
v 2.0.13

It would be great to be able to copy/paste the Application ID text straight from the dashboard (in attach) so to make it easier to activate it remotely for customers/partners.
![image](https://user-images.githubusercontent.com/19929395/36603468-1ecbea2c-18bb-11e8-8ece-1eb293b4e24c.png)

**Comment by gsantopaolo** [comment]
@corradocavalli  can you do it please?

**Comment by corradocavalli** [comment]
Added in 2.0.24, double click the application id to copy it to the clipboard.

**Comment by mtg1986** [comment]
Tested with 2.0.24. Technically it works. As there is not feedback for the users when he double click on the App ID the user does not know if it is copied or not. I think we need to inform the user when the App ID is copied.

**Comment by corradocavalli** [comment]
Please provide a complete scenario of how you would this to be implemented, if i well remember this should have been a "quick and dirty" trick for partners to read the application id, and so we would have guided them to the "double click" trick.

**Comment by corradocavalli** [comment]
Ok, closing, reopen if necessary.
