### ISSUE TITLE
Projects list not refreshed after deleting Project (low prio)

### ISSUE THREAD

**Issue by agorog** [IBVSoftware/CollaBoard-Feedback#509]
Version 2.0.13
1. Load a project from list "Projects you created"
2. Delete project
3. List "Projects you created" the deleted project is still displayed, when loading Message box "It seems that the Server does not like your Project code" will be displayed.

**Comment by corradocavalli** [comment]
Fixed in 2.0.14

**Comment by gsantopaolo** [comment]
This is really ridiculous! I need to ask @agorog what testers are testing !!!!

**Comment by mtg1986** [comment]
Tested in 2.0.15 and it is fixed.
