### ISSUE TITLE
[ERROR] Authentication with Facebook

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#51]
When trying to authenticate with FB, there is an Error Message: 

"App ist nicht eingerichtet: This app is still in development mode, and you don't have access to it. Switch to a registered test user or ask an app admin for permissions."

Surface Pro 4
Time: 14:07 27.01.2017

![grafik](https://cloud.githubusercontent.com/assets/19570958/22371851/eba30e88-e499-11e6-9958-f5715bb2ed10.png)

**Comment by gsantopaolo** [comment]
Facebook us to provide a valid id to prove we are to not phisher. We did it all it is now under facebook approval

**Comment by corradocavalli** [comment]
We're waiting for facebook to authorize our login to developer portal.

**Comment by corradocavalli** [comment]
Facebook authentication is back, please try again.
