### ISSUE TITLE
Sample Project - Connecting Tiles

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#510]
1.Connect tiles in a sample project
2.Create project from sample.
-->Connection are not there in the new project created from the sample 
(The same goes for template projects)

**Comment by gsantopaolo** [comment]
@kasuken we have to fix this tomorrow when i'll be in bonstetten

@mtg1986 @agorog It is ridiculous that the testing team didn't found this, to be hones i'm really unhappy about testing this time.
I believe we have to discuss how to enhance testing phase so that this doesnt happen any more

**Comment by gsantopaolo** [comment]
@kasuken it should be fixed. Sync your collaborad services repo, deploy on dev and ask @mtg1986  to test on dev environment. If fixed deploy in prod, please
thanls
/g

**Comment by mtg1986** [comment]
@corradocavalli : Can you give me key and code from the test template and sample projects?

**Comment by kasuken** [comment]
@gsantopaolo Hi Gian, I deployed the new version on dev environment, but it doesn't works yet.
We tested on the hub at the third floor.

**Comment by corradocavalli** [comment]
@mtg1986 I don't have that information, ask @gsantopaolo or @kasuken

**Comment by mtg1986** [comment]
Closing this bug as this works now. Tested with 2.0.41
