### ISSUE TITLE
Login Issue - Google (Facebook?)

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#512]
We got a bad feedback in the reviews of one guy that was not able to login with Facebook and Google and uninstalled CB because of that. 
We need to find somehow a solution and be able to quantify the failed login attempts and to help users if they face this issue. 

Tested it now on my Desktop PC:

**Login with Google:** Google Login pop up appears. Type in E-Mail and PW. For a short time a turning wheel appears and then nothing happens. 

**Login with Facebook**: Worked
**Login with Twitter**: Worked

**Comment by gsantopaolo** [comment]
@mtg1986  please understand:
1. The app wasn't tested good this time because our testers aren't doing a good job this time
2. Please ask the test team to login the app with different Facebook user and Google user If you can reproduce came to us we wil be more than happy to help.
3. you can look at telemetry and check if you find the issue, if you find it we will be have to give a look but do not expect resolution without a reproducing user

**Comment by mtg1986** [comment]
I created two new google accounts to reproduce this and with both accounts I experienced the same behaviour. 

To not publish here the credentials, I created a document in Microsoft Teams that contains all the accounts we will use to test login process in CollaBoard in the future. 

https://ibvinfo.sharepoint.com/sites/CollaBoardTesting/_layouts/15/WopiFrame2.aspx?action=edit&sourcedoc={52A780A0-BA4D-4E12-9388-7257648A3CC2}

**Comment by gsantopaolo** [comment]
@mtg1986 do yo have any issue with the newly created account if you try to login on CB?

**Comment by mtg1986** [comment]
@gsantopaolo : Yes, I cant' login with the new google accounts. Behaviour is like that: 
Google Login pop up appears. Type in E-Mail and PW. For a short time a turning wheel appears and then nothing happens.

**Comment by gsantopaolo** [comment]
@mtg1986 perfect! please share user and credential with @corradocavalli

**Comment by corradocavalli** [comment]
Fixed in 2.0.14

**Comment by mtg1986** [comment]
Tested Google and Facebook Login on
SFHub and Surface Pro. 
There was no issue anymore with login, therefore closing the bug.
