### ISSUE TITLE
User Icon - JD

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#513]
1.Login with IBV Microsoft Account
2.Create new project
3.User Icon shows JD instead of MG

![image](https://user-images.githubusercontent.com/19570958/36643622-8c90eea6-1a4e-11e8-9ced-170b03458903.png)

**Comment by corradocavalli** [comment]
Initials are created by concatenating first letter of user's firstname and lastname, are you sure that name is not "john doe"? :-)

**Comment by mtg1986** [comment]
I was logged in with Michael.gorog@ibv.ch. You see this in the License information. I tried to reproduce the it, but I am not able to. 
Should we close the issue?

**Comment by corradocavalli** [comment]
Closing since not reproducible, reopen it in case it raises again.
