### ISSUE TITLE
Project un-synced and System.Object

### ISSUE THREAD

**Issue by teguria** [IBVSoftware/CollaBoard-Feedback#515]
HP Spectre new and Spectre OLD
same version
I was doing some tests on both devices, same project. The old one is on wi-fi and is also syncing a lot of OneDrive files in the background.
The project was not in sync anymore and, once I close the project on OLD Spectre, I got this error message, in attach, and clicking any option was not working
Project Code: 13245
Project Key: s8dy2
Project description: Test new version

ibv-collaboard:open?code=13245&key=s8dy2
<img width="960" alt="2018-02-26 1" src="https://user-images.githubusercontent.com/19929395/36692434-536f7a62-1b38-11e8-84d1-29416bdd2fbe.png">

**Comment by corradocavalli** [comment]
I honestly don't know what to do on this w/o a repro sequence, I tried opening the project mentioned and is ok to me.

**Comment by teguria** [comment]
The project works but I somehow need to repro the sequence.

**Comment by mtg1986** [comment]
Closing as too old and I never experienced this bug.
