### ISSUE TITLE
Ink changes on it self 

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#516]
1.Create some sticky notes
2.Select black Color and fountain pen
3.Ink on Sticky Note 1 --> Black color and fountain
4.Ink on Sticky Note 2 --> Black color and fountain
5.Ink on Sticky Note 2 --> Blue color and fountain

6.Create new Sticky Note and ink on it -->Black color, thin line and normal pen
![ink_changes](https://user-images.githubusercontent.com/19570958/36693881-decfdba2-1b3c-11e8-9bba-64308a7421e0.gif)

Tested on Surface Pro
Version: 2.0.13
26.02.2018

**Comment by corradocavalli** [comment]
It should be fixed on 2.0.14

**Comment by mtg1986** [comment]
Tested with 2.0.14 and could not reproduce the issue. 
Therefore closing it.
