### ISSUE TITLE
Scrolling projects doesn't go smoothly

### ISSUE THREAD

**Issue by teguria** [IBVSoftware/CollaBoard-Feedback#519]
On my laptop, from the dashboard, scrolling down the projects doesn't work smoothly. See video attached.
[CollaBoard 27_02_2018 19_28_09.zip](https://github.com/IBVSoftware/CollaBoard-Feedback/files/1764206/CollaBoard.27_02_2018.19_28_09.zip)

**Comment by corradocavalli** [comment]
Fixed in 2.0.14

**Comment by mtg1986** [comment]
Tested with 2.0.14 and it worked very smooth. 
Tested on SFHub and Surface Pro
