### ISSUE TITLE
request license error

### ISSUE THREAD

**Issue by tamarawasser** [IBVSoftware/CollaBoard-Feedback#52]
Date: 27th of January
Time: 14:16
Device: Surface Pro 4
Version: 1.2.8.0

Steps (we're not in a Project now!!):
- Login by using Google Account: sarahhugo1990@gmail.com / PW: JKunser55/
- open radial menu 
- choos "info"
- klick on "Evaluation license"
- fill in form
- klich on "request license"
- error (see attached Picture)

-> same Problem with twitter

ATTENTION: when we're in a Project, the request license works
![image](https://cloud.githubusercontent.com/assets/25382402/22372299/37460d3e-e49c-11e6-9d48-1546a56c3e5d.png)

**Comment by gsantopaolo** [comment]
localization problem, you can request only one evaluation license per user so this is ok. you was not seeing the error because there was a problem with localization, now solved
