### ISSUE TITLE
Lost Ink

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#520]
1.Create Project on Surface Hub
2.Join Project with Surface Pro
3.Worked on Surface Hub Project 
4.Ink is not synchronized from Hub to Surface Pro 
5.Took a photo with Surface Pro and this was syncrhonized. 

Could not reproduce it anymore. 

Project is:
Project Code: 13406
Project Key: ulqp9

Version 2.0.13

**Comment by corradocavalli** [comment]
Closing since duplicate of #524
