### ISSUE TITLE
Connecting Tiles: Connection line not fully visible

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#523]
1.Take two tiles from different size
2.Pin the smaller one over the larger one and connect both to a third tile
3.Part of the connection line from the smaller one to the third tile is hidden from the larger tile

![image](https://user-images.githubusercontent.com/19570958/36939609-00ac0ea8-1f34-11e8-86ae-88c73453750a.png)

**Comment by gsantopaolo** [comment]
@mtg1986 this is definitely a bug. @corradocavalli shall estimate time for this to be fixed.
@corradocavalli  if this is a biggie please let's talk before begging working on this

**Comment by corradocavalli** [comment]
I tested with 2.0.24 and it works as expected, lines are now above tiles.
Can you provide a repro case to investigate?
Unfortunately this means "all" tiles including System Tiles are below lines and personally i don'tl ike it that much.
![image](https://user-images.githubusercontent.com/5617938/40498853-779716ca-5f80-11e8-861b-4a51240fa7d0.png)

**Comment by mtg1986** [comment]
Tested with 2.0.41 and we were not able to reproduce this anymore. Therefore I am closing the bug.
