### ISSUE TITLE
Block border around close button on info tile

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#525]
1.Open a new project after using collaboard for approx. 20 minutes. 
2.The Info tile now suddenly shows a black border on the close button. 

![image](https://user-images.githubusercontent.com/19570958/36977083-428c0a74-2080-11e8-93cf-f2d77568a4d8.png)

**Comment by corradocavalli** [comment]
Fixed in v 2.0.20

**Comment by mtg1986** [comment]
Tested with 2.0.21 on Surface Hub. Could not reproduce it. Therefore closing the bug.
