### ISSUE TITLE
Collaboard hangs when connection is lost while connected via VPN

### ISSUE THREAD

**Issue by corradocavalli** [IBVSoftware/CollaBoard-Feedback#526]
-Connect to IBV VPN
-Launch Collaboard
-Turn Off WiFi
-The invocation of hubConnection.Stop() in notificationHubService line 193 makes Collaboard hung endlessly.

**Comment by gsantopaolo** [comment]
@corradocavalli  does it happen without step1 ?

**Comment by corradocavalli** [comment]
No, without VPN everything works fine.

**Comment by gsantopaolo** [comment]
nooo need to to throw up!!!!

**Comment by mtg1986** [comment]
Tested this again with 2.0.41
When we do the scenario we get the following message: 

![image](https://user-images.githubusercontent.com/19570958/43003627-5fce3120-8c2d-11e8-85be-66cab9e03269.png)

@corradocavalli : I think this is ok. Can we close this bug?

**Comment by corradocavalli** [comment]
Yes.
