### ISSUE TITLE
Login Issue

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#529]
We have again login issues, now with a fresh created MS Account. 
The pop up apprears, I enter the login credentials, then it asks me if it is allowed to access all the data, I click on ok, then the turning wheel appears, disappears and nothing happens. 

Accountdetails: Send by E-Mail to Gian and Corrado 

Version: 2.0.15
Tested on Surface Pro and Desktop PC

**Comment by corradocavalli** [comment]
Fixed in 2.0.16
The problem is that provided account misses basic info like Firstname and Lastname, as temporary workaround add those information to the account and it should work.

**Comment by mtg1986** [comment]
Tested with 2.0.19. Works now, therefore closing.
