### ISSUE TITLE
Registration E-Mail not received

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#53]
1.Authenticate with google account
2.Create new project
3.Go to Info
4.Get Evaluation Licence
5.Fill out Evalaluation License Form (this worked)
6.I did not received the registration E-Mail on Gmail

Time: approx. 14:30
Device: Surface Pro 4
Version: 1.2.8.0

**Comment by gsantopaolo** [comment]
it is now working, please try with 1.2.9.0
