### ISSUE TITLE
Login with Twitter - Cannot register in Twitter

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#530]
When trying to use Twitter to login to CollaBoard the Button "Bei Twitter registrieren" is not clickable. All the other buttons are working. 

![image](https://user-images.githubusercontent.com/19570958/37336163-d6f059dc-26b0-11e8-9e6a-2794b0ba5727.png)

**Comment by corradocavalli** [comment]
That view is handled by Twitter infrastructure we have no access and can't control it.
It won't fix.

**Comment by mtg1986** [comment]
Tested with 2.0.41 on the Surface Hub

The login worked, so therefor closing the bug.
