### ISSUE TITLE
Switch Windows Accounts - Issue with CollaBoard and Ink on unsaved Sticky Notes

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#531]
Discovered today this issue. Do not know how often someone is doing this case, but I wanted to mention it.

1.Create Project, add sticky notes, ink on sticky notes, do not save them 
2.Switch Account on Surface Pro (without signing out)
3.Switch Account back (to the one where CB is running)
4.CollaBoard gives an Error Message: It is not about you it is about us. Try to reconnect.
5.Project closes automatically and CB shows the start screen.
6.Open Project again, ink on Sticky Note which was not saved is lost. 
7.Due to the automatically closing of Colloboard no thumbnail picture was created. 

Cant we make sure that if CollaBoard closes the project all unsaved tiles are saved or other are there other solutions to prevent the data loss?

**Comment by gsantopaolo** [comment]
4.CollaBoard gives an Error Message: It is not about you it is about us. Try to reconnect. 
this is a bug and needs to be fixed

6.Open Project again, ink on Sticky Note which was not saved is lost.
this should be fixed because of #557

**Comment by corradocavalli** [comment]
Tried with my devices, behavior i see is that when you return back to previous account CollaBoard remanins in the same status as it was before switching the account.
No closing, no errors.

**Comment by mtg1986** [comment]
2.0.42 tested on Surface Pro

everything worked, closing the bug
