### ISSUE TITLE
Sample Project - Zoom Level

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#532]
1.Work on the original project that is used for a sample
2.Zoom out of the project and close it
3.Create a new project from this sample
4.Zoom level is on the minimum and the user sees only the upper right corner of the project. 

It would be great if the zoom level of the original sample project is also taken for the projects created from the sample

**Comment by gsantopaolo** [comment]
should be fixed both dev and production.
please test and let me know

**Comment by mtg1986** [comment]
Tested it with the mindmap sample. Now when you start a project from the sample it is the same zoom level as from the original project. 

Version: 2.0.15 
Desktop-PC
