### ISSUE TITLE
Sticky Note with Ink and Text

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#533]
1.Create a sticky note
2.Ink on the sticky note
3.Go to text editor in sticky note and add some text
4.Switch back to ink on sticky note
5.Close project
6.Open project.
-->Sticky note shows always text and not ink, altough when project was closed ink was displayed.

**Comment by corradocavalli** [comment]
The status (ink vs text) is persisted when the tile is saved, at the moment we don't have the required infrastructure to persist it when tile content change in real time.

**Comment by gsantopaolo** [comment]
real entrenchment is that we must have text and ink on the same layer.
@mtg1986 please ask me to add this to the FDS if still not in

**Comment by mtg1986** [comment]
Closing this as the enhancement is in the FDS on page 13.
