### ISSUE TITLE
Mini-Map not visible with white background

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#534]
When the background Color of the canvas is white, the minimap is not visible. It is there, but almost impossible to see. 

![image](https://user-images.githubusercontent.com/19570958/37452082-d7ea992c-2833-11e8-909e-313a1696cd84.png)

**Comment by mtg1986** [comment]
Tried it on Surface Hub with 2.0.21. It is a bit better, but for a user still difficult to discover. What did you changed?

**Comment by mtg1986** [comment]
Is it possible to change the color of the mini map depending on the background color you're working with? Like if there's a white background change the mini map color to dark grey, if the background is black, make a white/light grey mini map?

**Comment by corradocavalli** [comment]
Sure, talk with Gian and make it as enhancement, one thing: please provide color combinations, let's not waste time in endless tentatives.

**Comment by mtg1986** [comment]
@corradocavalli : We tested this again and I think we can live with the solutuion right now, it is better visible than before. If we want to do the other enhancement with the Colors we can do this in the re-design phase of CollaBoard. Therefore I close this bug for now.
