### ISSUE TITLE
Creating Project from template does not copy Zoomfactor from template 

### ISSUE THREAD

**Issue by agorog** [IBVSoftware/CollaBoard-Feedback#535]
Version 2.0.15.0 
Mayby similar to #532 

When creating a project from a template the new project is always zoomed in, it does not take the zoomfactor from the template. Test with Mind Map Template. Canvas seems to be empty for the user after new project is opened, user has to zoom out to see the tiles.

**Comment by corradocavalli** [comment]
@kasuken @gsantopaolo Is this issue fixed?

**Comment by gsantopaolo** [comment]
yes, but i believe only on dev. Ask testers to test both dev and prod..

**Comment by corradocavalli** [comment]
It ha probably already merged into prod, close it please.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
