### ISSUE TITLE
CollaBoard Window movement - Multiple Screen Setting

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#536]
Setting: 
-2 Screens 
-1 Surface Pro
-Surface Docing Station 

Repo Scenario: 
Load a project.
1.Move CollaBoard Windows from Surface Pro screen to one of the connected screens 
2.Move the CollaBoard Windows to the Surface Pro Screen 

-->The project closes automatically and does not reload

When doing the same movement (from screen to screen) with the Start Screen (when not in a project) the bug does not appear. 

Version: 2.0.15

**Comment by corradocavalli** [comment]
Cannot create CanvasImageSource sized 17500 x 10500; MaximumBitmapSizeInPixels for this device is 16384

Will be fixed when we'll implement infinite canvas on InkSurface
