### ISSUE TITLE
Ink with the finger - Text

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#537]
When I tap on the icon "Ink with finger" and Finger inking is on, I see this variable in the text: 

![image](https://user-images.githubusercontent.com/19570958/37815481-5039e66c-2e6f-11e8-96c2-c5e7a66d14ea.png)

Surface Hub 
2.0.16

**Comment by corradocavalli** [comment]
Fixed in 2.0.17
