### ISSUE TITLE
Ink with the finger (on the canvas)

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#538]
When I activate finger inking on the Surface Hub I cannot ink with the finger on the canvas.
Also inking with the pens on the canvas does not work anymore on the Surface Hub.

1.Start a new project
2.Try to ink on the canvas with the pen 
3.Nothing happens

Inking on tiles like sticky notes does work.

2.0.16

**Comment by corradocavalli** [comment]
Does it happens on Surface Hub only?

On 23 Mar 2018, at 07:59, Michael Görög <notifications@github.com<mailto:notifications@github.com>> wrote:


When I activate finger inking on the Surface Hub I cannot ink with the finger on the canvas.
Also inking with the pens on the canvas does not work anymore on the Surface Hub.

1.Start a new project
2.Try to ink on the canvas with the pen
3.Nothing happens

Inking on tiles like sticky notes does work.

**Comment by mtg1986** [comment]
Tried to reproduce again, not possible. Therefore closing.
