### ISSUE TITLE
open an esisting project error

### ISSUE THREAD

**Issue by tamarawasser** [IBVSoftware/CollaBoard-Feedback#54]
Date: 27th of January
Time: 14:35
Device: Surface Pro 4
Version: 1.2.8.0

Steps:
- load an existing Project
- login with key 3133 and code oi8hz
- error 
![image](https://cloud.githubusercontent.com/assets/25382402/22372613/fe18606e-e49d-11e6-9871-ede9acb1a4af.png)

**Comment by gsantopaolo** [comment]
now fixed. You are trying to access a project you crated in production (with a collaborad version not for tester) on dev enviroment. Dev environment is the env. where collaboard for tester are pointing. then the error was missing on localization and you was getting this
