### ISSUE TITLE
Radial Menue beahvoiur - Animation missing?

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#543]
When I switch now from one level to another in  the radial menu it is much faster but the animation we had bevor is not visible anymore. 

In the document it says: 
The radial menu is behaving to slow, like changing from one level to another. Look here at the video that compares radial speed in Drawboard and CollaBoard. (Ask Michael Gorog for video). 

--> In the video the radial is faster, but the animation is still visible. 

Surface Hub 
2.0.16

**Comment by corradocavalli** [comment]
Made animation a bit slower on v 2.0.17, we need to find a trade off between speed and animation effect.

**Comment by mtg1986** [comment]
I think this behaviour is much better now, so I would close this issue.
