### ISSUE TITLE
Telemetry trace unsuccessfull log in

### ISSUE THREAD

**Issue by gsantopaolo** [IBVSoftware/CollaBoard-Feedback#546]
it seems that public static void TraceLogIn(string windowsFamily, bool isAnonymous, string provider, string email, Guid uniqueMachineId, bool isSuccesful = true) is never called from outside to trace unsuccessful login

**Comment by gsantopaolo** [comment]
![image](https://user-images.githubusercontent.com/9937149/37828361-3907b1be-2e9b-11e8-9989-0e9c93e82309.png)

**Comment by corradocavalli** [comment]
Implementation is in vnext branch.

**Comment by agorog** [comment]
We have now (starting with version 2.0.17.0) "LogIn Failure" as new Telemetry.Name
