### ISSUE TITLE
CollaBoard in German - Missing Translations and issues

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#549]
Info Tile: 

![image](https://user-images.githubusercontent.com/19570958/37873891-6e479868-3025-11e8-9736-452d4c0f10f1.png)

Radial 
![image](https://user-images.githubusercontent.com/19570958/37873896-8fa3731a-3025-11e8-9a3a-c3e2d6217ffa.png)

![image](https://user-images.githubusercontent.com/19570958/37873901-a989504c-3025-11e8-9fca-afaafc104416.png)

![image](https://user-images.githubusercontent.com/19570958/37873904-bee801e0-3025-11e8-8ab7-b2a6c47a10dd.png)

![image](https://user-images.githubusercontent.com/19570958/37873908-cf0bf61c-3025-11e8-8271-032d93765b48.png)

**Comment by corradocavalli** [comment]
Hi Michi,
Looks like German translation is out of sync. I will send you the updated strings via mail for you to check.

**Comment by corradocavalli** [comment]
Fixed and tested in v 2.0.25, closing.
