### ISSUE TITLE
Problems with Microsoft Authentication

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#55]
1.Open CollaBoard
2.Authenticate with franz.meier1980@outlook.com Account
3.Fill in E-Mail and Password
4.Grant Permission to the App
5.Form closes
6.Click on blue "OK" Button next to the Authentication 
7.Form to fill in E-Mail and Password appears again (the whole process starts from begin)

Device: Surface Pro 4
Time: 14:35
Version: 1.2.8.0

**Comment by gsantopaolo** [comment]
We need a way to reproduce this otherwise is impossible to debug. We can try when i'll be in bonstetten...

**Comment by gsantopaolo** [comment]
?

**Comment by gsantopaolo** [comment]
@mtg1986  ???

**Comment by mtg1986** [comment]
Authentication with Microsoft Account is working.
v.1.3.6.0
