### ISSUE TITLE
Ink with the finger - Not working 

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#550]
1.Create new project 
2.Create Sticky Note
3.Ink on Sticky note with Mouse 
4.Switch ink with the finger on
5.It is not possible to ink with the finger, and when switching it off it is not possible at all to ink on the background. 

-When not inking first on a sticky note then it does work

Surface Pro 
2.0.016

**Comment by corradocavalli** [comment]
Fixed in 2.0.17, as temporary workaround, close and reopen the project.

**Comment by mtg1986** [comment]
Tested with 2.0.19, fixed.
