### ISSUE TITLE
Sharing Contracts - Image Quality

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#551]
If possible it would be great if we can increase the quality of the .png file we share with the project data by E-Mail.

Please see here on the left the image and on the right CollaBoard. The ink on sticky notes in a grid library is not readable on the image:

![image](https://user-images.githubusercontent.com/19570958/37887511-75661f64-30c2-11e8-85f3-8217ea1a15d7.png)

**Comment by corradocavalli** [comment]
Unfortunately we can't do much on this since what get shared is a screen shot of the entire canvas and so when you zoom some loosing in resolution is inevitable

**Comment by mtg1986** [comment]
Ok, when it is by design then we close this for now.
