### ISSUE TITLE
Tile Header - Office Documents

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#553]
1.Upload Office Document2
2.Wait until header diasapperas 

-->Result does look strange: 

![image](https://user-images.githubusercontent.com/19570958/38017058-3fda7416-3271-11e8-8da3-0d5899a23699.png)

**Comment by corradocavalli** [comment]
Fixed in 2.0.20

**Comment by mtg1986** [comment]
Tested with 2.0.20 on Surface Pro. Looks much better now :). Therefore closing.
