### ISSUE TITLE
Panda when using Team modus

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#556]
1,Launch CollaBoard
2.Slect Team Mode
3.Get a Panda (It seems there is a problem)
4.I click the Panda away and can start working with it

-->I cannot logout (the button is grey and not tabable) 

Version: 2.0.18
Surface Hub

**Comment by corradocavalli** [comment]
Fixed in v 2.0.19

**Comment by mtg1986** [comment]
Tested with 2.0.19 ion Surface Hub. Panda still appears.

**Comment by mtg1986** [comment]
Tested with 2.0.20. Now it is fixed. Closing the bug.
