### ISSUE TITLE
Close CollaBoard using right top x does not store open ink / project image

### ISSUE THREAD

**Issue by agorog** [IBVSoftware/CollaBoard-Feedback#557]
Version 2.0.18.0/ 2.0.17.0 (maybe also earlier versions):

Open a project, add a sticky note, ink sticky note, close App using top right x. 
No message, that there are unsaved sticky notes. 
Ink is not stored and project image (for project lists) is not updated. 
IF you open project other device the sticky note stays locked, for the locking user a read circle is shown. 

If User closes app having a project open, same logic should run as when closing a project.

**Comment by gsantopaolo** [comment]
Hi Andi. Thanks for reporting the bug. Appreciate your commitment. 
There are several things to take in consideration to sole this. I need to be back and discuss with Corrado.
We will care about this as soon as i'll be back in europe.

thank you
/g

**Comment by corradocavalli** [comment]
Feature added in 2.0.24.

**Comment by mtg1986** [comment]
Tested with 2.0.24. Now there is the pop up message that says to me that there are unsolved tiles. 
Tested on Surface Pro. 
Close issue.

**Comment by mtg1986** [comment]
Tested on Surface Hub with 2.02.24. The same message appears, when clicking on X and having unsaved tiles.

**Comment by gsantopaolo** [comment]
@mtg1986  and igf you kill the app on surface hub with the gesture by sliding the window down?

**Comment by gsantopaolo** [comment]
if you also tested this on the hub feel free to close again

**Comment by mtg1986** [comment]
Yes we tested this and the behaviour is different. When killing the app the message does not appear.
I think this feature is very important on a personal device. On Surface Hub I never closed CollaBoard accidentaly with the sliding down feature.

**Comment by gsantopaolo** [comment]
@mtg1986 fine. I want just to test that there is no crash on the hub.
feel free to close this if you are satisfacted

**Comment by mtg1986** [comment]
Ok, then lets close it.
