### ISSUE TITLE
Play Video - Progress not showed

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#558]
1.Record a Video
2.Play the Video
3.In the viedo progress bar the black point stays on 0:00 although the video is playing.

Tested 2.0.19
08.05.2018
Surface Hub and other devices

**Comment by corradocavalli** [comment]
Looks like a machine related regression introduced when we fixed #497,it was working on my machine but not on Surface 3 i use for testing.
Looks like a behavior mismatch of MediaTransportControl UWP control.
It should work on v 2.0.20

**Comment by mtg1986** [comment]
Works now. Tested with 2.0.20 and 2.0.21. Surface Pro & Surface Hub

**Comment by gsantopaolo** [comment]
@gsantopaolo mention to trigger vsts import
