### ISSUE TITLE
Take photo - No access to camera

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#559]
1.Click on taka a photo
2.Camer tile appears
3.It is possible to take a photo
-->This makes no sense, as no photo is taken.

![image](https://user-images.githubusercontent.com/19570958/39758294-c1d7d3d6-52cf-11e8-9aef-ce75588b5532.png)

2.0.19
Laptop PC
08.05.2018

**Comment by corradocavalli** [comment]
There were some mis-alignments that could lead to this beaviour, please verify with version 2.0.20

**Comment by mtg1986** [comment]
It is not possible anymore to take a picture when camera is not accessible. Problem solved. 
Tested with 2.0.20
Surface Pro.

**Comment by gsantopaolo** [comment]
@gsantopaolo mention to trigger vsts import
