### ISSUE TITLE
Get Evaluation License

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#56]
I had a license on my device before, but under another user. Then I unregistered and logged in with one of my twitter accounts (to make sure that it was not registered). 

1.Login with Twitter 
2.New Project
3.Go to Info
4.Get "Evaluation License" -->This works "Registered until 27.02)
Then I requested the “Evaluation License” and that worked. Then the Pop Up came. When trying to request the evaluation license again, then I got this “NA” message and I could not proceed to the second form in the “Evaluation Request” Wizard. 

Device: Surface Pro 4
Time: 14:46 27.01.2017
User: mgorog@live.com
Version: 1.2.8.0

**Comment by gsantopaolo** [comment]
what happen if you close collaboard open it and go on info?
are you registered or not?

**Comment by mtg1986** [comment]
When I close and open again, I am registered.

**Comment by corradocavalli** [comment]
Fixed
