### ISSUE TITLE
QAT - Not shown 

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#560]
1.Go to settings
2.Enable show QAT 
3.QAT is not displayed 
![image](https://user-images.githubusercontent.com/19570958/39758386-ffb71914-52cf-11e8-8cba-6bd63cd1ca9d.png)

-->Difficult to reproduce as it seems to happen randomly 

2.0.19
Laptop 
08.05.2018

**Comment by corradocavalli** [comment]
Tried several times on different devices without being able to reproduce.
Please reopen the bug when you have a reproducible scenario.

**Comment by gsantopaolo** [comment]
@gsantopaolo mention to trigger vsts import
