### ISSUE TITLE
Panda on Lenovo ThinkPad E550

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#561]
Description: Was working on an imported PDF and suddenly it started lagging and the following Text pops up: “Closing Project”.
But I didn’t click on closing Project.
Afterwards CollaBoard crashed.
Timestamp: 14:01

Device: Lenovo ThinkPad E550
OS: Windows 10 Edu
2.0.19
08.05.2018

**Comment by gsantopaolo** [comment]
@gsantopaolo mention to trigger vsts import

**Comment by corradocavalli** [comment]
No interesting info in Telemetry, need a repro case.

**Comment by mtg1986** [comment]
As we are not able to reproduce we need to close this bug and repopen if it appears again.
