### ISSUE TITLE
Creating new Project failed

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#562]
2.0.19 
08.05.19 13:56 
On Laptop 
User: Basil

**Comment by gsantopaolo** [comment]
@gsantopaolo mention to trigger vsts import

**Comment by corradocavalli** [comment]
Had a look at telemetry, no valuable info there, need a repro case to investigate more.

**Comment by mtg1986** [comment]
Tried again with 2.0.41. As we did not faced any issues with project creation anymore I will close this but. If it happens again we will create a new one.
