### ISSUE TITLE
Panda 13:50 08.05.2018

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#564]
User 1 Inks on a Sticky Note
User 2-6 add multiple sticky notes at the same time 
-->Panda on the device where User 1 was inking on the Sticky Note 

2.0.19
08.05.2018 13:50
Multiple devices (Panda appeard on Surface Pro)

**Comment by gsantopaolo** [comment]
@gsantopaolo mention to trigger vsts import

**Comment by corradocavalli** [comment]
Telemetry doesn't provide enough info to investigate more w/o a repro case.

**Comment by mtg1986** [comment]
Tried to reproduce it with 2.0.41 on 5 devices. We were not able to create this Panda again. Therefore we will close the bug for the moment.
