### ISSUE TITLE
Panda 08.05.2018

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#565]
Panda on a Surface Pro at 13:40
No repo scenario
2.0.19
Surface Pro

**Comment by corradocavalli** [comment]
Looks like that i cannot longer access telemetry on Azure using Azure@ibv-solutions.com account, i get an access denied message.
@gsantopaolo @kasuken Has something changed?

**Comment by corradocavalli** [comment]
Solved, I was not listed as Contributor :-)

**Comment by gsantopaolo** [comment]
@gsantopaolo mention to trigger vsts import

**Comment by corradocavalli** [comment]
Looked at issues on that date, unfortunately information don't give enough information to investigate more w/o a repro case.

**Comment by mtg1986** [comment]
Closing as not reproducable and not valuable info in telemtry.
