### ISSUE TITLE
Field of View Junmping

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#566]
Scenario: Multiple people working in the same project

User 1: Edits a sticky note. Then the filed of view of this users jumps randomly to another point of the canvas. The sticky notes stays in edit mode and the user needs to navigate back to the sticky note. 

User 2-6 randomly working on Sticky Notes in the project

2.0.19 
08.05.2018
Laptop PC

**Comment by corradocavalli** [comment]
Can you elaborate more? What is "field of view"?  are the users working on their own machines?
Tried with three machines and everything looks ok, the sticky note that is in edit mode doesn't move.

**Comment by mtg1986** [comment]
Field of view is the part of the canvas the users sees. Each user was working on his own machine. I had the issue today again, only me in a project. May be this is something where we need to do a debug session as it is difficult to find a repo-scenario. How should we proceed?

**Comment by gsantopaolo** [comment]
@gsantopaolo mention to trigger vsts import

**Comment by mtg1986** [comment]
@corradocavalli : We tested again with 2.0.23 and the issue is still here. Let me know how we should proceed here as it is almost impossible to reproduce.

**Comment by corradocavalli** [comment]
I need a repro case, otherwise I have no opportunity to fix it.


________________________________

**Comment by mtg1986** [comment]
I tried now several times but it seems impossible to reproduce. Never happend to me so far. I will close the bug for the moment and reopen if I am able to reproduce myself.
