### ISSUE TITLE
Sticky Note - Full Screena nd back

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#567]
1.Make a Sticky Note full screen
2.Write with Keyboard on Sticky Note
3.Leave full screen mode. The QAT stays in the sticky note and zooming is not possible anymore (see screenshot)
-->I remember we had this bug in previous versions already 
2.0.19
Laptop 

![image](https://user-images.githubusercontent.com/19570958/39758994-b8deb3ec-52d1-11e8-97a9-2592e0755cd2.png)

**Comment by corradocavalli** [comment]
I can't reproduce it on my machines, do you have a specific case where this happens all the times?

**Comment by gsantopaolo** [comment]
@gsantopaolo mention to trigger vsts import

**Comment by gsantopaolo** [comment]
@mtg1986 what about that?

**Comment by mtg1986** [comment]
Could not reproduce anymore with 2.0.24. Therefore I close the bug.
