### ISSUE TITLE
Performance Issues

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#569]
We tested with 7-8 people and devices today. 
We faced severe performance issues with 2.0.19 when working on project.
-->The lagging of the app seems to start much earlier than in previous versions. This means altough there were not that many objects in a project it stated to lag. 

08.05.2018
Multiple devices

**Comment by corradocavalli** [comment]
What do you mean with "lagging"? can you share key and code?
Thanks

**Comment by gsantopaolo** [comment]
@gsantopaolo mention to trigger vsts import

**Comment by mtg1986** [comment]
Tested today with 6 people in one project working at the same time. Performance is much better and we did not faced the issued we had in the last testing session. 
2.0.23
Therefore I close the bug.
