### ISSUE TITLE
Tiles in Grid Library different order

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#57]
Devices: Surface Pro 4
time: 15:00
Project Code: 1413
Project Key: dbq6e

1.Create Grid Libraries
2.Create 2 Sticky Notes
3.Upload Picture
4.Take a pcitre with Camara
5.Put tiles from one Grid library to another
6.Add Library 
7.Move tiles from Library to Grid library
8.Tiles in one grid library are not in the same order

![grafik](https://cloud.githubusercontent.com/assets/19570958/22373361/c2d10a84-e4a1-11e6-8324-18f6369e1047.png)

**Comment by corradocavalli** [comment]
Tried but can reproduce without success but ordering might be the same issue that causes issue #88

**Comment by gsantopaolo** [comment]
this is now fixed! I'm going to close this, feel free to reopen if you will experience this issue
