### ISSUE TITLE
Login Issue - Facebook

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#570]
1.Login to Facebook
2.Click on Button and enter credentials to CollaBoard, accept data security stuff
3.Click ok and then there is a turning wheel, the pop up closes and nothing else happens. 

Tried to login with Facebook. Tried my own and one of the test account

08.05.2018 
Surface Pro 
2.0.19

**Comment by corradocavalli** [comment]
Looks like that Facebook has changed something in his login API and facebook lib we use to authentication doesn't work anymore.
Looking for an alternative...

**Comment by mtg1986** [comment]
Thanks. Works now.
Tested with 2.0.20
Surface Pro

**Comment by gsantopaolo** [comment]
@gsantopaolo mention to trigger vsts import
