### ISSUE TITLE
Radial Menu - Ink with the finger

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#571]
1.Enable ink with the finger 
2.Tap and hold to the screen
-->The radial menu does not appear

If I unable ink with the finger the radial menu appears again

Tested with 
2.0.19
08.05.2018
Surface Pro

**Comment by corradocavalli** [comment]
When in finger drawing mode, all touch interactions are handled as 'drawing' gestures and so we have no way to intercept a long press. Even if it would be possible, you would see a 'dot' each time you press and hold to activate the radial menu. :-)

**Comment by gsantopaolo** [comment]
@gsantopaolo mention to trigger vsts import

**Comment by mtg1986** [comment]
We can live with that
