### ISSUE TITLE
Resizing Camera Tile

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#572]
In earlier versions it was possible to resize the camera tile. 
Would be nice to have this back. 

2.0.19
Surface Pro & Surface Hub

**Comment by corradocavalli** [comment]
I honestly don't remember this feature available in the past.
It is available in 2.0.20

**Comment by mtg1986** [comment]
Tested 2.0.20
Surface Pro
works again, therefore closing.

**Comment by gsantopaolo** [comment]
@gsantopaolo mention to trigger vsts import
