### ISSUE TITLE
Header Buttons on Video Tiles

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#573]
Button on video tiles. As discussed before.

![image](https://user-images.githubusercontent.com/19570958/40099673-3c0b4d06-58e1-11e8-9fab-39610a0e0d0b.png)

2.0.21
Surface Hub

**Comment by corradocavalli** [comment]
Fixed in 2.0.23

**Comment by gsantopaolo** [comment]
@gsantopaolo mention to trigger vsts import

**Comment by mtg1986** [comment]
Tested with 2.0.23 on Surface Hub.
Issue is solved
