### ISSUE TITLE
Ink with two pens

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#574]
1.Create a new project 
2.Start inking with two pens in blue 
3.Change with one pen Color to red. 
4.Ink again with both pens. 
-->Color of both pens is now red. 

Tested with 2.0.22 on Surface Hub

**Comment by corradocavalli** [comment]
Fixed in 2.0.23

**Comment by gsantopaolo** [comment]
@gsantopaolo mention to trigger vsts import

**Comment by mtg1986** [comment]
Tested with 2.0.23 on Surface Hub and could not reproduce.
