### ISSUE TITLE
Ink color changes

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#575]
Not easy to reproduce and seems to appear randomly. Behaviour is like that. 

1.Ink with two pens - both are blue 
2.Change one pen Color to red 
3.Both are red (reported ina nother bug)
4.Change Color of one pen to blue 
5.Change Color with pen several times and ink 
6.Then ink with one pen. While inking the Color changes from red to blue and vice versa

2.0.22
Surface Hub

**Comment by mtg1986** [comment]
Please see here an image where it happend when drawing a rectangle 
![image](https://user-images.githubusercontent.com/19570958/40101114-a724f7ea-58e6-11e8-9c03-2ce5042591a8.png)

**Comment by corradocavalli** [comment]
Please try again with version 2.0.23 to see if the fix solved this issue as well?

**Comment by gsantopaolo** [comment]
@gsantopaolo mention to trigger vsts import

**Comment by mtg1986** [comment]
Tested with 2.0.23 on Surface Pro. 
Issue is stille here, that sometimes Color of the ink on a pen changes randomly

**Comment by corradocavalli** [comment]
Please try to provide a repro case.


________________________________

**Comment by mtg1986** [comment]
1.Ink with two pens, both are blue 
2.Choose with left pen red Color 
3.Ink with left pen, this is red. With the right pen it is red
4.With right pen click on Color. Now it should display blue, but is shows read. Altough we use the left (blue) pen the Color is red. When we select then the red Color, the ink of the pen stays blue.

Please see here a short video of the repo sequence: 
https://ibvinfo-my.sharepoint.com/:v:/g/personal/michael_gorog_ibv_ch/EUpHhsJAORtOike70mFSGewBA67YnwZRCUw44mrA7bT6EQ

Tested it with 2.0.41 on Surface Hub

**Comment by corradocavalli** [comment]
Fixed in 2.0.47

**Comment by mtg1986** [comment]
Tested the scenario with 2.0.47 on Surface Hub. Scenario does now work as expected. Closing this bug.
