### ISSUE TITLE
Tile header visibility

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#576]
When having an image with a dark Color, the icons of the tile headers are not that good visible. 

![image](https://user-images.githubusercontent.com/19570958/40100524-818f2ae8-58e4-11e8-86cd-8528a1093146.png)

Tested with 2.0.22
Surface Pro

**Comment by gsantopaolo** [comment]
@gsantopaolo mention to trigger vsts import

**Comment by corradocavalli** [comment]
I did several test and i agree that experience was not the best, so i changed the color of the toolbar and related icons to make them more revealing in a different combinations.
Give it a try with version 2.0.24, styling or reverting back is easily doable now.
Some examples:
![image](https://user-images.githubusercontent.com/5617938/40417405-faaa178a-5e7f-11e8-8119-5d1b374f32c2.png)
![image](https://user-images.githubusercontent.com/5617938/40417464-1a954524-5e80-11e8-883e-917815d0a272.png)
![image](https://user-images.githubusercontent.com/5617938/40417505-2d9ef840-5e80-11e8-939d-b46ec87fce77.png)
![image](https://user-images.githubusercontent.com/5617938/40417544-48244a6c-5e80-11e8-9dbb-c8a01a19fd41.png)

**Comment by mtg1986** [comment]
Tested with 2.0.24. I like the new style. Therefore I close the issue.
