### ISSUE TITLE
PDF Quality

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#577]
When importing a PDF the quality seems to be worse than in previous versions. For example text is pixled and not good to read. See screenshot.
2.0.22

![image](https://user-images.githubusercontent.com/19570958/40100685-2462d1ac-58e5-11e8-953f-10d7c80b2ebd.png)

**Comment by corradocavalli** [comment]
We didn't change anything regarding that part, can you make a test with the version from the store?
Is also on your usb stick in case... (v 15)

**Comment by gsantopaolo** [comment]
@gsantopaolo mention to trigger vsts import

**Comment by mtg1986** [comment]
It seems that it depends on different factors (also pdf quality) Tested this now on Hub, DELL and Surface Pro with 2.0.41. I think we can close this bug, as it is more an enhancement of PDF, that is on the roadmap as well.
