### ISSUE TITLE
Sharing Contracts

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#578]
When I click on the share button on the Surface Hub I can't share the project. 

"CollaBoard can't share it right now. Try again later" is the message. This is the only text I see and no icons for the apps where to share. 

Tested with 2.0.22 on Surface Hub

**Comment by corradocavalli** [comment]
Feature is not complete yet on CollaBoard.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by gsantopaolo** [comment]
@gsantopaolo mention to trigger vsts import

**Comment by corradocavalli** [comment]
Completed in v 2.0.24

**Comment by mtg1986** [comment]
Bug isn't fixed yet, sharing still doesn't work in CollaBoard.

Tested on Surface Hub, Version 2.0.24
![sharing bug](https://user-images.githubusercontent.com/19570958/40489170-d1f419a0-5f68-11e8-9ee5-2ea72141eea6.JPG)

**Comment by corradocavalli** [comment]
@mtg1986 
What app are you sharing from? What exactly happen? What sequence are you executing?

**Comment by mtg1986** [comment]
@corradocavalli : we share direct from CollaBoard. 

Click on the Share icon on the lower right corner and then it is not possible to send the project credentials with the key and code by E-Mail on Surface Hub. 

On Surface Pro and Desktop PC it works perfectly.

**Comment by corradocavalli** [comment]
I've tried with both Hub at the entrance and one in DEV floor and it works
![img_3128](https://user-images.githubusercontent.com/5617938/40646896-ceed812c-632a-11e8-91de-c8788a3ca7ad.JPG)

**Comment by corradocavalli** [comment]
Think it depends on email client, we don't differentiate between environments.

**Comment by mtg1986** [comment]
Ok, then I assume we cant do anything and we should close this bug.
