### ISSUE TITLE
edit and save sticky note 

### ISSUE THREAD

**Issue by tamarawasser** [IBVSoftware/CollaBoard-Feedback#58]
Project Code: 1414
Project Key: yozu7
ibv-collaboard:open?code=1414&key=yozu7
Date: 27th of January
Time: 15:21
Device: Surface Pro 4
Version: 1.2.8.0

Steps:
create a sticky note
edit sticky note and ink over the border
save
enlarge sticky note
![image](https://cloud.githubusercontent.com/assets/25382402/22374045/b0b8779e-e4a4-11e6-8594-4c4cbeb89905.png)

edit sticky note again
![image](https://cloud.githubusercontent.com/assets/25382402/22374066/c74db80c-e4a4-11e6-8bde-c8f9490f227b.png)

**Comment by corradocavalli** [comment]
We have a fix for this but we need more time to investigate side effects.

**Comment by teguria** [comment]
@corradocavalli @gsantopaolo FYI this happened again in a meeting this morning. I asked others in the project to ink on the same tile and they could.
![bug1](https://cloud.githubusercontent.com/assets/19929395/22506232/a28838ce-e87f-11e6-9d75-2f5414dbad99.png)

**Comment by corradocavalli** [comment]
We should have fixed it, please try with the new release and if ok, please close the issue.

**Comment by agorog** [comment]
Works as excepted. User cannot ink outside the tile
