### ISSUE TITLE
Panda 09:51

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#585]
On Surface Hub I got a Panda at 09:51. 
Project: 15728, 92zga

I was try to upload files. I cant click the panda away (nothing happens when clicking on OK) and I need to restart CollaBoard.

2.0.23

No Repo scenario

**Comment by gsantopaolo** [comment]
@agorog  do you have any thing on telemetry?

**Comment by gsantopaolo** [comment]
@corradocavalli next week we shall try reproduce this with @mtg1986

**Comment by corradocavalli** [comment]
Got the exception from Telemetry (2018-05-17T08:34:22.986) but w/o a repro case can't fix this.

Exception CLASS: Application  METHOD: Global Application MESSAGE: System.InvalidCastException: Arg_InvalidCastException
   at CollaBoard!<BaseAddress>+0x2855fe1
--- End of stack trace from previous location where exception was thrown ---
   at CollaBoard!<BaseAddress>+0x277caa1
   at CollaBoard!<BaseAddress>+0x277ca7e
   at CollaBoard!<BaseAddress>+0x2a1eae6
   at CollaBoard!<BaseAddress>+0x27954f1
   at CollaBoard!<BaseAddress>+0x284f9b5
   at CollaBoard!<BaseAddress>+0x284f8db
   at Microsoft.HockeyApp.Extensibility.Windows.UnhandledExceptionTelemetryModule.CoreApplication_UnhandledErrorDetected(Object sender, ApplicationModel.Core.UnhandledErrorDetectedEventArgs e)
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at CollaBoard!<BaseAddress>+0x2a92f76
   at CollaBoard!<BaseAddress>+0x2a93433  MachineId: 54a3a2a6-e17e-7168-9ff8-e5d4d1f2fe43
--

**Comment by mtg1986** [comment]
Tried to find a repo scenario. Very difficult. File upload was working with 2.0.41 good and no issue so far. Therefore I close this bug.
