### ISSUE TITLE
Ink Color

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#587]
If you want to change the ink color in the quick access toolbar, you click on the color dot with your pen or finger. If you tap right in the middle of the dot, it changes the color as usual. If you click outside of the dot but still in rectangle of the color (a blue rectangle appears around a dot), it shows that the color has changed, but it hasn't actually changed the ink color.
![ink color](https://user-images.githubusercontent.com/19570958/40164483-edeea04e-59b9-11e8-8ca0-210ac87d3d15.png)

Tested on Surface Hub and Surface Pro

Version 2.0.23.0

**Comment by corradocavalli** [comment]
Fixed in 2.0.24

**Comment by mtg1986** [comment]
Tested with 2.0.24.. It works now. Therfore closing the bug.

**Comment by mtg1986** [comment]
If you try to change the ink color on the Surface Hub and click outside of the round color dot, there is no ink anymore. 

Version 2.0.24

**Comment by corradocavalli** [comment]
Hopefully should be fixed in 2.0.26

**Comment by mtg1986** [comment]
Tested with 2.0.28 and it works now. Closing the bug.
