### ISSUE TITLE
Load PowerPoint

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#588]
On Surface Pro I import a PowerPoint with 5.5 MB this works

On Surface Hub I try to import the same PowerPoint via USB stick and I get the message that the filesize esceeds 15 MB. 

2.0.23

**Comment by corradocavalli** [comment]
You have the issue with all ppt presentations or just with that? if so, can you send it to me via mail?

**Comment by mtg1986** [comment]
Please see here the presentation. Tested again with 2.0.24, same issue.
[Digital-Workshops-FHNW-Presentation_ohneVideo.pptx](https://github.com/IBVSoftware/CollaBoard-Feedback/files/2035643/Digital-Workshops-FHNW-Presentation_ohneVideo.pptx)

**Comment by corradocavalli** [comment]
Tried as well and can't reproduce it, does it happen with all ppt presentations or just this?

**Comment by corradocavalli** [comment]
Fixed in 2.0.26

**Comment by mtg1986** [comment]
Tested with 2.0.28 and it works now :). 
Closing the bug.
