### ISSUE TITLE
Overlaying Tiles dont show correctly after closing/opening project 

### ISSUE THREAD

**Issue by agorog** [IBVSoftware/CollaBoard-Feedback#59]
Projekt Code: 1188
Projekt Schlüssel: 1lr8i
ibv-collaboard:open?code=1188&key=1lr8i

Date: 27th of January
Time: 15:25-15:35
Device: Surface Hub and on Surface Pro 4
Version: 1.2.8.0

In the left part there are 4 tiles in this project: 
PDF, wich should be unter the 3 sticky notes. 
Top1, which should be above pdf but under Top2 sticky note.
Top2, which should be between Top1 and Top3 sticky note.
Top3, which should over Top 2 sticky note.  So we have the sequence
PDF / Top 1 / Top 2 / Top 3 

Arragen the tiles like this. On both devices shown correctly.
Close project on hub, open it again: Then we have the following sequence on the hub:
Top 1 / PDF / Top 3 / Top 2 
Surface Pro still shows the correct sequence. 
Close on Surface Pro, open it again: Same wrong sequence will be displayed.

**Comment by gsantopaolo** [comment]
don't think this is a bug... you have to show me the behavior

**Comment by agorog** [comment]
With 1.2.9 we did some Videos. Michi will share them: The video shows how the tiles after opening a project are not in the same order they had when closing the project. Also only part of the inking is shown on Hub and on PC

**Comment by gsantopaolo** [comment]
@agorog  can we close this?

**Comment by agorog** [comment]
Project Code: 3474
Project Key: 0pr1u
ibv-collaboard:open?code=3474&key=0pr1u
Version 1.3.6.0 
Date 07.02.2017 14:36 
There are 4 stickys inked/texted 1/2/3/4. The have been saved as 1/2/3/4, i.e. 4 is on top of 3 and so on. 
No change that so that 1 is on top of 2. This will be displayed on all devices where the project is open. 
Close the project on one device and load project again. On this device the tiles are shown with 4 on top, the other device still show 1 on top. As soon as you close and load then stickys are shown with 4 on top instead of 1 on top. 
If I then I ink sticky 1 on Surface and save, the ink is not shown on the hub, i.e. the sticky is shown without ink. After closing and loading the project on hub the ink is shown. Then put sticky 1 on Surface again on top and ink it, on the hub the sticky is shown without ink and then the error message "Is seems that we have a problem..." is displayed. Happened at 07.02.207 14:45.

**Comment by agorog** [comment]
[p3474_overlappingStickyProblems.docx](https://github.com/IBVSoftware/CollaBoard-Feedback/files/757918/p3474_overlappingStickyProblems.docx)

**Comment by agorog** [comment]
Still same with 1.3.9.0

**Comment by gsantopaolo** [comment]
As @corradocavalli said at the moment tile stacking is only saved when 

- project closes
- app is suspended

Created an internal issue to enhance this behavior with low priority, so expect this in some time.
