### ISSUE TITLE
Telemetry InkEnabled

### ISSUE THREAD

**Issue by agorog** [IBVSoftware/CollaBoard-Feedback#591]
InkEnabled is always False, i.e. from any Surface Device with StartApplication TouchEnabled = "true" and InkEnabled = "false". This is the case since the beginning, but also noticed yet, when we check no other InkEnabled devices.

**Comment by corradocavalli** [comment]
We were always passing false as InkEnabled parameter, since InkEnabled is meaningless in general since we can ink with any device, starting from version 2.0.25 that parameter is true when device supports Pen as input type, leading to a more predominant use of Ink.

**Comment by mtg1986** [comment]
@agorog : Can we close this bug or is it not solved yet?
