### ISSUE TITLE
Get Evaluation License

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#597]
1.Log in with MS outlook account
2.Try to get evaluation license, fil out the form and click on Request a license
3.-->Panda

Tested with 2.0.24 
Desktop PC

**Comment by corradocavalli** [comment]
Fixed in 2.0.28

**Comment by mtg1986** [comment]
Tested with 2.0.28 and it works now. Closing the bug.
