### ISSUE TITLE
Sharing contracts - Non Surface Hub pc

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#598]
Sharing contracts does not show any sharing options. When clicking on the share button it says "Try again" but nothing changes. 

Tested with Surface Pro and Laptop 
2.0.24 and 2.0.25

**Comment by corradocavalli** [comment]
Fixed on 2.0.28

**Comment by mtg1986** [comment]
Tested it with 2.0.28 

I create a new project
Then I click immediately on share. Then no option to share is displayed. 
When I click the second time it works. 
Tested on desktop PC. 

On my Surface I have the issue that it works sometimes and sometimes not. 

Is this anything we have control about or is this Win10 related? 

It works now more or less, but not as good as I hoped. 

Tested with 2.0.28

**Comment by corradocavalli** [comment]
Please try again with 2.0.30

**Comment by mtg1986** [comment]
Tested with 2.0.30, and it worked every time so far.

**Comment by mtg1986** [comment]
Tested now several times and it works. Closing the bug.
