### ISSUE TITLE
Starting CollaBoard from other Applications

### ISSUE THREAD

**Issue by agorog** [IBVSoftware/CollaBoard-Feedback#600]
Several partners (including strategic ones) have the request to start CollaBoard out of their Control Centers or other Applications.

We need the following possibilities in addition to the Windows Run possibility to start CollaBoard automatically opening a project using  ibv-collaboard: uri ibv-collaboard:open?code=nnnnn&key=zzzzz: 

From command line (i.e. cmd.exe): 1. Start CollaBoard, 2. Start CollaBoard automatically opening a project (like we have now with Windows Run). 

From Windows Run: Start CollaBoard without opening a project, i.e. something like ibv-collaboard: uri ibv-collaboard:start

**Comment by corradocavalli** [comment]
Starting from version 2.0.42 is possible to launch CollaBoard using this uri: bv-collaboard:start

**Comment by mtg1986** [comment]
@agorog : How can we test this now?

**Comment by mtg1986** [comment]
@corradocavalli : I am not sure how to test this. Can you help me here?


Can I enter this "ibv-collaboard:start" into the command line? 

![image](https://user-images.githubusercontent.com/19570958/43201527-0f2db520-9019-11e8-8334-adb5a3bc45b4.png)

**Comment by corradocavalli** [comment]
You can use the run command from Windows or use **start**" from a DOS prompt: >start ibv-collaboard:start

**Comment by mtg1986** [comment]
Thank you. Tested it and it is working. Closing this issue now.
