### ISSUE TITLE
Log out User and clear credentials programmatically

### ISSUE THREAD

**Issue by agorog** [IBVSoftware/CollaBoard-Feedback#601]
Same partners as #600. 

Running instance of CollaBoard, allow other process to log out of CollaBoard and clear credentials, i.e. after that Log out if user starts CollaBoard again, user has to login again.

**Comment by corradocavalli** [comment]
Available from version 2.0.42 on

**Comment by mtg1986** [comment]
@agorog : How can we test that?

**Comment by corradocavalli** [comment]
These are supported commands
**Run collaboard**: ibv-collaboard:start
**Run collaboard and open a project**: ibv-collaboard:open?code=[Code]&key=[key]
**Logout**: ibv-collaboard:logout

**Comment by mtg1986** [comment]
Thank you. I forwarded the information to the relevant partner. Closing this now.
