### ISSUE TITLE
CollaBoard Freeze & Ink Loss

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#603]
On Surface Hub only: 

1.Open project from sample (Mind-Map sample)
2.Work in the project, like do all standard procedures 

-->Then suddently CollaBoard freezes and all ink disappears. 

Tested with 2.0.28

![image](https://user-images.githubusercontent.com/19570958/41471367-bb89da36-70b3-11e8-8fb3-c88e740313a5.png)

**Comment by corradocavalli** [comment]
Can you test with 2.0.30?

**Comment by mtg1986** [comment]
Tested with 2.0.41 on Surface Hub and we are not able to reproduce that. Therefore I close the bug.
