### ISSUE TITLE
Images are not shown on Surface Hub

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#608]
1.Create project on Hub
2.Login to project with Surface Pro
3.Upload Images on Surface Pro
4.On Surface Hub image tiles are there, but withouth any content. 

When we do it with images, pdfs and videos it is like that. 
If we upload office documents we do not see the edit bar with the icons to open or save a document. 

Tested with 2.0.30 pointing to on-prem on Surface Hub and Surface Pro

![image](https://user-images.githubusercontent.com/19570958/41765903-bc4a3fcc-7605-11e8-97df-b3d7aee6edd3.png)

![image](https://user-images.githubusercontent.com/19570958/41766045-2fdd4ca4-7606-11e8-87b5-03ce837e8117.png)

**Comment by corradocavalli** [comment]
Regression introduced on 2.0.30 it is fixed on 2.0.31 not HUB related.

**Comment by mtg1986** [comment]
Tested with 2.0.31 and the issue is still here

**Comment by mtg1986** [comment]
Solved with 3.0.33
