### ISSUE TITLE
Parameter cannot be null

### ISSUE THREAD

**Issue by gsantopaolo** [IBVSoftware/CollaBoard-Feedback#61]
While loading a project, i was trying to replicate the ghost tiles, i got the message: "Parameter cannot be null Parameter name source"
Notthing was loaded, that's fine i was trying to hack the project.
But the when i try to close the project, hitting close button on radial menu i wasn't able to close the project.

Can we do something like this happens we show a message to the user saying "there was a problem loading the project" and the user is kicked automatically off the project?

![image](https://cloud.githubusercontent.com/assets/9937149/22378223/2f1bf8da-e4b5-11e6-8a08-38d1fb66768a.png)

**Comment by corradocavalli** [comment]
This kind of errors will now appear with the new Panda look, would be nice if you could provide a repro case for this specific bug so that we can fix it.
