### ISSUE TITLE
PDF upload did not worked correctly

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#611]
I uploaded a PDF two time. Once it was the wrong size and once it was correct: 
Tested with 2.0.31 on Surface Pro 
Not reproducable at the moment.

![image](https://user-images.githubusercontent.com/19570958/41768846-b59ee210-760d-11e8-8e78-3412e5d70527.png)

**Comment by gsantopaolo** [comment]
@mtg1986 I'm afraid nothing we can do because this is about PDF. I don;t want to invest time is something we shall get a third party component.
If you feel we had the need please ask for budget for a third party pdf component.
Can you close this?

**Comment by mtg1986** [comment]
Ok, I will not test PDF anymore until we have this 3rd party pdf component. As it is not reproducabe I will close this bug.
