### ISSUE TITLE
CollaBoard crash at 11:19

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#612]
CollaBoard crashed on my Surface Pro. I was doing something with the video and then it suddenly closed itself, without asking if I want to close the project.

Version:2.0.31.0 - ApplicationId:54a3a2a6-e17e-7168-9ff8-e5d4d1f2fe43

**Comment by gsantopaolo** [comment]
@mtg1986  are you able to reproduce anyways?

**Comment by gsantopaolo** [comment]
@corradocavalli  can you give an eye to telemetry?

**Comment by gsantopaolo** [comment]
@mtg1986  so better to close and reopen if it happens again and we do have a pattern for that
