### ISSUE TITLE
Issue to load a project 

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#613]
If I try to load the project 112 I get the following error message: 

Tested on DELL. 2.0.31.0

![image](https://user-images.githubusercontent.com/19570958/41769626-3ab09b04-7610-11e8-95ea-3e383b66ec11.png)

**Comment by corradocavalli** [comment]
Looks like an issue raising when the same message gets processed twice. I added code to handle this scenario.
Available from build 2.0.47

**Comment by mtg1986** [comment]
Tested again with 2.0.47 to load several older projects on Surface Pro and Surface Hub. Did not faced any issues. Therefore closing this issue.
