### ISSUE TITLE
Load project with QR Code - Panda

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#620]
1.Load a porject via QR Code
2.There is a panda

The project loads somehow but the radial is a very old one. 
Tested with. v. 2.0.38 on Surface Pro

![image](https://user-images.githubusercontent.com/19570958/42881197-183a98ae-8a97-11e8-8528-f75bbff070b9.png)

**Comment by mtg1986** [comment]
Tested on the Surface Hub with 2.0.41. Same issue as with 2.0.38 on Surface Pro.

**Comment by corradocavalli** [comment]
Works for me...
1-Does it work with other projects?
2-Can you share code and key of failing project?

**Comment by mtg1986** [comment]
Tested now on two devices with 2.0.41 and we get each time the panda. Tested it with old and with new QR codes. 
What should we do?

**Comment by corradocavalli** [comment]
What is project key and code?

**Comment by mtg1986** [comment]
![image](https://user-images.githubusercontent.com/19570958/42885871-7a28c3d2-8aa2-11e8-9fc8-31bfeeb1afe9.png)

**Comment by corradocavalli** [comment]
2.0.15??? what machine is that?

**Comment by mtg1986** [comment]
The pcitre is from a QR code I took a few weeks ago. Tested everything with 2.0.41.

**Comment by corradocavalli** [comment]
Looks like something failed while loading the project, but can't find anything relevant in the telemetry.
Closing since can't investigate it more, re-open if it happens again.

**Comment by mtg1986** [comment]
@corradocavalli : We tried again and it happens all the time. Should we make a sykpe call to show you, or install a debugger on one of the devices?

**Comment by corradocavalli** [comment]
If it happens all the times, it would be awesome to if we could debug it to definitively fix it. Let's make a test together tomorrow.

**Comment by mtg1986** [comment]
Fixed with 2.0.42. Tested on Surface Pro. Closing the bug.
