### ISSUE TITLE
Change Ink Color creates Sticky Note

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#625]
Tested with 2.0.41 on Surface Hub. 

When I change the Color of Ink in the radial menu, each time I click on the Color, a sticky note is created. 
Only happens on Surface Hub, could not reproduce on Surface Pro.

![image](https://user-images.githubusercontent.com/19570958/42936068-76471850-8b4b-11e8-9348-91e41a015109.png)

**Comment by corradocavalli** [comment]
Doh! fixed in 2.0.43

**Comment by mtg1986** [comment]
Tested with 2.0.47 and can confirm the fix. Closing the bug.
