### ISSUE TITLE
[OnPremise] Project doesn't load properly.

### ISSUE THREAD

**Issue by corradocavalli** [IBVSoftware/CollaBoard-Feedback#631]
Using Azure Test invironment.
-Create a brand new project and upload a picture.
-Close and reopen the project, the tile appears empty.

I've investigates and looks like that **DocumentExplorerServiceClient.GetUserItemsByShareAsync()** returns no errors, but zero files on the server, and so the rest of the code deletes the original files from local storage, since they no longer exist on server, so the image is missing.
Looks like a server side issue, so i add the label.

**Comment by agorog** [comment]
After install the actual server version works fine tested with 51.
