### ISSUE TITLE
erase credentials / user data from external app

### ISSUE THREAD

**Issue by agorog** [IBVSoftware/CollaBoard-Feedback#637]
QuickLaunch (Dell) needs in addition to logout from CB an additional option which is erasing all user data.

**Comment by corradocavalli** [comment]
All data means just credentials or also all user related projects?
A new option like /clearall looks good?

On 15 Aug 2018, at 17:35, agorog <notifications@github.com<mailto:notifications@github.com>> wrote:


QuickLaunch (Dell) needs in addition to logout from CB an additional option which is erasing all user data.

**Comment by agorog** [comment]
/clearall is ok. Only local userdata has to cleared, i.e. nothing in the DB, same as the hub is doing automatically when ending the session.

**Comment by corradocavalli** [comment]
The /logout option deletes all user information.
From version 2.0.51 there's a new /clearall option that deletes user credentials.

**Comment by agorog** [comment]
Changed clearall to exit. Does logout, clear credentials and ends app. Available from 2.0.51.
