### ISSUE TITLE
Login via Google

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#639]
When I try to login via Google then no sign in pop-up appears and I am just redirected to the start screen.

When I create a project I am signed in with "JD".
Test-Project:
18332
j088i

This project does not appear in the list of my projects. 

Tested with 2.0.51

![image](https://user-images.githubusercontent.com/19570958/44514415-5aacb600-a6c0-11e8-8e0d-e13aae95311d.png)

**Comment by corradocavalli** [comment]
It works for me, can you try with a different version, i think 51 has a bug regarding Google login.

**Comment by mtg1986** [comment]
Tested with 2.0.50 on Surface Hub and here it works.

**Comment by corradocavalli** [comment]
Ok, thanks, look like a regression then… investigating

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by mtg1986** [comment]
Tested with 2.0.55 and it is solved. Closing the bug.
