### ISSUE TITLE
Collection was modified error

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#640]
Time: 10:42 
User: mgorog@live.com
Version:2.0.51.0 - ApplicationId:58987b6a-7315-d653-a4b4-114cde27c9e3

![image](https://user-images.githubusercontent.com/19570958/44514762-3b625880-a6c1-11e8-8da1-f4215f36c591.png)

**Comment by corradocavalli** [comment]
Put a guard on reentrancy on LoadUsers code.
Closing, reopen if raises again.
