### ISSUE TITLE
Report from the filed: Copy & Paste of an image

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#644]
As this is a report from the filed we need to check the telemetry.

-	Go to the web browser and nagivate to a web page 
-	Right click on a image and click copy 
-	Go to Collaboard and try to paste it
-	You should get the error you see in the image below

![image](https://user-images.githubusercontent.com/19570958/44658527-70dcae00-aa01-11e8-89eb-95e4cec48ed4.png)

I tested now with 2.0.53 copy & past of images from: 

-Edge: Ok
-Firefox: Ok
-Internet Explorer: OK 

-Chrom: n.OK 
-->If I copy an image in the google image search from chrome and try to paste it to Collaboard, there is nothing to paste. Copy&Paste to Word for example works. In CollaBoard the past icon stays greyed out.

**Comment by corradocavalli** [comment]
Looks like that Google Chrome behaves differently than other browsers regarding clipboard sharing.
Fixed in 2.0.54

**Comment by mtg1986** [comment]
Tested with 2.0.55 and it is working. Closing the bug.
