### ISSUE TITLE
Unable to update CB

### ISSUE THREAD

**Issue by teguria** [IBVSoftware/CollaBoard-Feedback#645]
Unable to update public version of CB, tested on 2 devices.
Error code: 0x800B0100

**Comment by mtg1986** [comment]
It seems that there is an issue with CollaBoard in the store: 

Andi: Could not update CB. He deinstalled it and try to re-install it and gets the same error as Ale. 

Michi: Uninstall CB and re-install. This worked.

**Comment by corradocavalli** [comment]
Have you tried running the Windows Store Troubleshooter on those machines? 
https://support.microsoft.com/en-us/help/4027498/microsoft-store-fix-problems-with-apps

**Comment by teguria** [comment]
I tried to uninstall and reinstall - lo luck. I used the troubleshooter, no luck. Will try to restart

**Comment by teguria** [comment]
Restarted the machine but get the same message and can't install CB anymore
Code: 0x800B0100

**Comment by mtg1986** [comment]
I tested also on the Hub and there it works. Gianluca installed as well on several devices and it works. 
It seems an issue with your device. 
Can you try to sideload 2.0.53? 
You can find the package here: Z:\Collaboard\Versions

**Comment by teguria** [comment]
@mtg1986  I tried and got this error message: ''App Installer failed to install package dependencies. Ask the developer for Microsoft.NET.CoreRuntime.1.1 package. ''

**Comment by mtg1986** [comment]
I have someone who reported this bug now as well. It is the same error code Ale was sending. 

![image](https://user-images.githubusercontent.com/19570958/44724203-56bed080-aad2-11e8-9e3a-d4c760fe8041.png)

**Comment by corradocavalli** [comment]
@alead<mailto:notifications@github.com> Did you fill First and Last name in the live profile associated with email used for login?

________________________________

**Comment by teguria** [comment]
Yes @corradocavalli and it's licensed to my email account (O365)

**Comment by corradocavalli** [comment]
What happens if you use another account?

On 28 Aug 2018, at 18:27, alead <notifications@github.com<mailto:notifications@github.com>> wrote:


Yes @corradocavalli<https://github.com/corradocavalli> and it's licensed to my email account (O365)

**Comment by corradocavalli** [comment]
Did a check, there's no JD inside client code so i presume JD comes from the server when some combination is triggered on the user.

**Comment by teguria** [comment]
ok good to know, thanks. I was also wondering if the installation issue, from the Store, have been fixed? Thanks

**Comment by mtg1986** [comment]
If you install CB on a fresh device there is usually no issue. Tried it several times and was always working. I will close this issue, ok?

**Comment by teguria** [comment]
I tested it on 3 devices, updating to the latest version and it works. Closing
