### ISSUE TITLE
Error while loading project 

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#646]
When loading this project I get sometimes this error. 
Version 2.0.53

Project Code: 18460
Project Key: ayqpx

![image](https://user-images.githubusercontent.com/19570958/44772788-20835e80-ab6f-11e8-9633-3d5817e6a29f.png)

**Comment by mtg1986** [comment]
When we try it several times then it always works.

**Comment by corradocavalli** [comment]
I was able to reproduce it, it was a race condition so very machine and load dependent.
Fixed in 2.0.55

**Comment by mtg1986** [comment]
Tested with 2.0.55 and it is wokring. Closing this issue.
