### ISSUE TITLE
Help Audio Record Tile

### ISSUE THREAD

**Issue by agorog** [IBVSoftware/CollaBoard-Feedback#67]
Version 1.2.9.0  all devices, no project opened 

Click on help, Show audio record tile
![grafik](https://cloud.githubusercontent.com/assets/19590642/22395446/a11faee8-e53e-11e6-8764-ce16d667a809.png)

When you record here something and then stop recording, an error occurs: 

![grafik](https://cloud.githubusercontent.com/assets/19590642/22395450/b9351fcc-e53e-11e6-921c-45a0fbeed2f9.png)

The picture shows the German error message, which is too long, english is ok.

**Comment by corradocavalli** [comment]
Fixed
