### ISSUE TITLE
Moving tiley in/out gridlibrary causes out of sync, ghost tiles

### ISSUE THREAD

**Issue by agorog** [IBVSoftware/CollaBoard-Feedback#69]
Project Code: 1424
Project Key: iynxh
ibv-collaboard:open?code=1424&key=iynxh
Version 1.2.9.0 
Date 28.02.2017 14:05-14:13

In this project you have a grid library with 6 tiles. Open project on 2 devices. Move on one device all tiles out of the grid library seqentually then move them back. Shows correct on device where you do the moves on the seconde devices it looks crazy and sometimes you also get ghost tiles.

**Comment by agorog** [comment]
Sample view on 2nd device 
![grafik](https://cloud.githubusercontent.com/assets/19590642/22396853/33fcf93a-e564-11e6-8a71-f3b6683282f8.png)

**Comment by agorog** [comment]
should look like this 
![grafik](https://cloud.githubusercontent.com/assets/19590642/22396886/5b49dc56-e564-11e6-81a9-c03186206c41.png)

**Comment by agorog** [comment]
closed/opened project on both devices, tried again move out / in, Got en error that something went wrong, after loading the project again one tile was lost, see screenshot. 
![grafik](https://cloud.githubusercontent.com/assets/19590642/22396923/fda93578-e564-11e6-97a5-78a5458d23be.png)

**Comment by gsantopaolo** [comment]
this is now fixed! I'm going to close this, feel free to reopen if you will experience this issue
