### ISSUE TITLE
Video Recording

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#72]
Surface Pro 4
Time: 09:11 2017
Project Code: 1431
Project Key: w3r31
ibv-collaboard:open?code=1431&key=w3r31

Procedure: 
1.Create New Project
2.Record video for less than 1 sec (longer videos work, not sure if someone in real-life will make such sort videos)
3.Video Tile is created and the message appears "Unsupported File Format". Video is not playable

![image](https://cloud.githubusercontent.com/assets/19570958/22402782/0dc8a86e-e603-11e6-9a1c-b866aa574afb.png)

**Comment by agorog** [comment]
On my Surface Pro 4 (new system update has been installed this night). I can only record a video not longer then 11 seconds. If it is longer, nothing happens, no tiles is generated no message to user.

**Comment by corradocavalli** [comment]
Added a minimum recording time to 1 second, on my system i have no problem recording more than 11 seconds. Please verify again with next build.

**Comment by teguria** [comment]
Tested on my laptop, 1 second-video works.
