### ISSUE TITLE
Video Records on NB, displays Error on NB, displays correctly on Hub and Surface

### ISSUE THREAD

**Issue by agorog** [IBVSoftware/CollaBoard-Feedback#74]
Projekt Code: 1436
Projekt Schlüssel: b9y5e
ibv-collaboard:open?code=1436&key=b9y5e
Version: 1.3.0.0
Date: 29.01.2017 10:15 - 10:45 

I record Video on NB (HP Envy TouchSmart), Video is recording and showing, stop recording, tile will be produced, but shows Error: Unsupported video type or invalid file path. Can ink video without problems. On the hub and the surface pro the video is shown correctly. 
If you open the project you see in the middle 3 tiles, one sticky note with yellow backkground, then the video (correctly on Hub and Surface Pro, but with the error on NB) and then a screenshot of how it looks on the NB.

**Comment by corradocavalli** [comment]
Does it happen all the times? If so we need to debug it on that specific machine.

**Comment by gsantopaolo** [comment]
@agorog  any feedback?

**Comment by agorog** [comment]
1.3.6.0 works now.
