### ISSUE TITLE
Size of imported or camera picture

### ISSUE THREAD

**Issue by agorog** [IBVSoftware/CollaBoard-Feedback#76]
Version 1.3.0.0

If I import a jpg or take a camera picture, then the generated tile is quit big and I can't make it smaller then size the tile was generated.  Can we implement the sizing to a smaller size like the minimal size of a sticky note ?

**Comment by gsantopaolo** [comment]
Where are you testing it? On the surface hub is of an appropriate size...

**Comment by agorog** [comment]
I test on the hub and there the size is too big, same on Surface Pro 4. See screenshot from Hub. 
![whiteboard](https://cloud.githubusercontent.com/assets/19590642/22424002/cda14c80-e6f4-11e6-9ff2-d67aab096188.png)

**Comment by agorog** [comment]
Yellow sticky shows the size of a new created sticky note. 
Picture under it with red ink shows image out of camera with too big size, can't be made smaller.
Right of this is camera itself. If I take video then video has the size as the camera itself.

**Comment by corradocavalli** [comment]
Made Tile Picture the same size as Sticky note, keep in mind that we have to satisfy aspect ratio.
Test it with the new version and if ok, close the issue
![image](https://cloud.githubusercontent.com/assets/5617938/22433681/7d62681a-e719-11e6-9d96-140e25894578.png)

**Comment by gsantopaolo** [comment]
@agorog  does it looks good for you now?

**Comment by agorog** [comment]
1.3.6.0 ok
