### ISSUE TITLE
Add Help for Mouse/Keyboard

### ISSUE THREAD

**Issue by agorog** [IBVSoftware/CollaBoard-Feedback#77]
Version 1.3.0.0

According to downloads we have lot of users not having touch screen. Can we have a list of Mouse/Keyboard commands (like zoom in/out, size tile etc.) which we can provide to these type of users ?

**Comment by corradocavalli** [comment]
Ctrl+wheel=Tile Zoom or Canvas Zoom
Ctrl+Shift+click=zoom in
Ctrl+alt+click=zoom out
Ctrl+shit+click or ctrl+alt+shift= fit content
Right click on a tilr enters edit mode.
Ctrl+wheel=scroll load project content horizontally

Please verify them, i'm going with memory.

On 29 Jan 2017, at 11:10, agorog <notifications@github.com<mailto:notifications@github.com>> wrote:


Version 1.3.0.0

According to downloads we have lot of users not having touch screen. Can we have a list of Mouse/Keyboard commands (like zoom in/out, size tile etc.) which we can provide to these type of users ?

-

**Comment by gsantopaolo** [comment]
You can add to the manual. Btw keep in mind that Collaboard is designed and developed for being used with touch and ink.
There could came a moment when we wouldn't be able any more to support mouse and keyboard for some features...
@mtg1986  @teguria  Please let us know when you added those keyboard shortcuts to manual so we will close this

**Comment by agorog** [comment]
Here is the doc from Tamara. @corradocavalli can you please check and if ok we close this issue. 

[CB work with mouse and keyboard.pdf](https://github.com/IBVSoftware/CollaBoard-Feedback/files/774498/CB.work.with.mouse.and.keyboard.pdf)

**Comment by corradocavalli** [comment]
Document is not correct:
Zoom out: Ctrl+Shift+Click
Zoom In: Ctrl+Click
Fit Content: Alt+Click

Please update it and close.

**Comment by tamarawasser** [comment]
Here is the adjusted doc @corradocavalli. 
[CB work with mouse and keyboard.pdf](https://github.com/IBVSoftware/CollaBoard-Feedback/files/777415/CB.work.with.mouse.and.keyboard.pdf)
