### ISSUE TITLE
Can't ink on a recording audio tile

### ISSUE THREAD

**Issue by teguria** [IBVSoftware/CollaBoard-Feedback#80]
Hub
Time: 16.28
Date: 29/01/2017

I created a new "recording audio" tile. I recorded some audio, stopped and started inking on it. At some point I wasn't able to write as if it was a limit in the area I could write. I tried different times but cannot replicate

Key: 1441
Code: s1454

![wp_20170129_16_17_50_pro](https://cloud.githubusercontent.com/assets/19929395/22405253/42061b74-e640-11e6-987c-12d708e46a02.jpg)

**Comment by teguria** [comment]
16.42 Same behavior happened on a picture I loaded. I can't ink on the whole picture.

**Comment by corradocavalli** [comment]
What if you resize it? Can you ink on entire area? Can you provide a repro sequence?

On 29 Jan 2017, at 16:43, alead <notifications@github.com<mailto:notifications@github.com>> wrote:


16.42 Same behavior happened on a picture I loaded. I can't ink on the whole picture.

-

**Comment by teguria** [comment]
16.45 This also happened wiht a PDF. I inked with different colors and pen types, then I left it there, I inked again with orange color and, as you can see from the picture, that seems the limit I cannot cross to type in again.
![wp_20170129_16_45_31_pro](https://cloud.githubusercontent.com/assets/19929395/22405460/563c4458-e643-11e6-80ee-7380f90aa1c7.jpg)

**Comment by teguria** [comment]
I tried to rotate, resize and ink again but it doesn't let me do it anymore I cleaned the entire area but that tile seems "bugged" somehow (same with the recording audio tile I mentioned previously). I made a video so you can have a look https://1drv.ms/v/s!AokjDqTnRRs8zd8FWC_PkuozVVsEKA

**Comment by teguria** [comment]
Repro steps: create a new project, click on X when you close the new project info -> Load a PDF from a USB stick, start inking on it. Same occurs with a picture

**Comment by gsantopaolo** [comment]
@agorog @corradocavalli  tomorrow we have to check this please...

**Comment by teguria** [comment]
Definitely @gsantopaolo , this has to be tested on laptops as well

**Comment by corradocavalli** [comment]
This is a duplication of bug #58, we had a fix but we need to better test it, i close it, please use issue #58 thread.
