### ISSUE TITLE
Camera doesn't switch when I move

### ISSUE THREAD

**Issue by teguria** [IBVSoftware/CollaBoard-Feedback#82]
HUB
16.36
29/01/2017

When I record a video, the camera doesn't switch from one to another if I move (or my voice goes towards the other camera).

Code: 1441
Key: s1454

**Comment by corradocavalli** [comment]
We don't have a switch camera option yet.

On 29 Jan 2017, at 16:38, alead <notifications@github.com<mailto:notifications@github.com>> wrote:


HUB
16.36
29/01/2017

When I record a video, the camera doesn't switch from one to another if I move (or my voice goes towards the other camera).

Code: 1441
Key: s1454

-

**Comment by gsantopaolo** [comment]
@teguria is asking the same feature skype for business on surface hub has! Is you move arreound to swith camera on real time.
Oh yes I would love to have that. 
Just a little question: Do you know how many developers the skype / skype for business team has?
Doable but it requires time, we should plan this functionality...

**Comment by corradocavalli** [comment]
Chose camera feature has been added. Feature not available on Surface Hub.

**Comment by corradocavalli** [comment]
Added support for left/right camera on Hub, please test it and close the issue if ok.

**Comment by corradocavalli** [comment]
Confirmed that it works also on Surface Hub, issue closed.
