### ISSUE TITLE
Edit Mode VS Normal mode

### ISSUE THREAD

**Issue by teguria** [IBVSoftware/CollaBoard-Feedback#84]
Hub
17.11, 29/01/2017
When you use the highlighter you have 2 different outcomes whether you are in normal mode or in edit mode. See the 2 pictures.
![wp_20170129_17_10_25_pro](https://cloud.githubusercontent.com/assets/19929395/22405739/b40c3ddc-e647-11e6-87b8-3a1ba35212aa.jpg)
![wp_20170129_17_10_20_pro](https://cloud.githubusercontent.com/assets/19929395/22405740/b40c711c-e647-11e6-8641-9d74740face4.jpg)

**Comment by gsantopaolo** [comment]
@teguria  thank you for make us notice this.
This is related to #58 technically is the same bug so i'm going to close this as @58 is still open
