### ISSUE TITLE
Evaluation Registration

### ISSUE THREAD

**Issue by teguria** [IBVSoftware/CollaBoard-Feedback#85]
HUB
17.26, 29/01/2017

I register for the evaluation version and the registration menu box pops up. I fill in all the info.
First: I can put anything on the "phone number" filed and I don't get any issue

Second (and most importantly): when I get the message "You're done - installation now fully functional...." I click OK but nothing happens !!
![wp_20170129_17_26_48_pro](https://cloud.githubusercontent.com/assets/19929395/22405807/9de9098a-e648-11e6-8b5f-9aba188303f5.jpg)

**Comment by corradocavalli** [comment]
Does it happen on pc too?

On 29 Jan 2017, at 17:30, alead <notifications@github.com<mailto:notifications@github.com>> wrote:


HUB
17.26, 29/01/2017

I register for the evaluation version and the registration menu box pops up. I fill in all the info.
First: I can put anything on the "phone number" filed and I don't get any issue

Second (and most importantly): when I get the message "You're done - installation now fully functional...." I click OK but nothing happens !!
[wp_20170129_17_26_48_pro]<https://cloud.githubusercontent.com/assets/19929395/22405807/9de9098a-e648-11e6-8b5f-9aba188303f5.jpg>

-

**Comment by teguria** [comment]
I don't have the beta so we need to ask @mtg1986 about it

**Comment by teguria** [comment]
This HUB is in Dev Mode, can it be a reason for this behavior?

**Comment by corradocavalli** [comment]
It was a regression, i have fixed it.

**Comment by gsantopaolo** [comment]
@teguria free coffee from @corradocavalli  🥇

**Comment by corradocavalli** [comment]
Let's have a splut! :-)

**Comment by teguria** [comment]
Hurrah, Splut and Rivella for everyone !! 🥇
