### ISSUE TITLE
Message "No Audio Capture devices are present on this system"

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#86]
When I launch CollaBoard on a Desktop PC I get the following Message: 

"No Audio Capture devices are present on this system"
I click on "Close" and I can continue

When I launch a New Project I get the message again: 

"No Audio Capture devices are present on this system"

-->Here I got the same message again and I need to click twice on "Close" to get rid of the message.¨

Tested: 
HP Desktop PC
Time: 08:09 30.012.017
Version: 1.3.1.0

**Comment by corradocavalli** [comment]
Are audio capture devices present? (e.g webcam) the message is the one with the Panda on the left?

**Comment by mtg1986** [comment]
When I click on search, I get the message again twice. 
![image](https://cloud.githubusercontent.com/assets/19570958/22414998/43eaf020-e6c4-11e6-8a45-13202542ed32.png)

**Comment by mtg1986** [comment]
There are no audio capture devices on this Desktop PC.

**Comment by corradocavalli** [comment]
Is there a webcam integrated or attached? a webcam is required to use CollaBoard.

**Comment by mtg1986** [comment]
No there is only an audio out. I do not have any additional conferencing tools connected to this PC, except the headphones on the audio out, and they do not have a microphone.

**Comment by corradocavalli** [comment]
This is not a scenario we cover, I've anyway found what generates the dialog (audio enabled Text input) and I'll investigate if we can add a system check at startup. Do you confirm that, apart dialogs everything else works?

**Comment by mtg1986** [comment]
Yes everything is working fine, expect that I get the message several times.

**Comment by corradocavalli** [comment]
In the new version messages won't show up anymore and user will get (once) this message at startup in case of missing audio hardware. Please test it when new version will go out.
![image](https://cloud.githubusercontent.com/assets/5617938/22415701/b9ba07f0-e6c9-11e6-834c-86d3aa5c03fd.png)
