### ISSUE TITLE
loss of tile / out of sync reproduced

### ISSUE THREAD

**Issue by agorog** [IBVSoftware/CollaBoard-Feedback#88]
Project Code: 3302
Project Key: bei5v
ibv-collaboard:open?code=3302&key=bei5v
Version 1.3.1.0 
Date 30.01.2017 13:15-13:49 

Version 1.3.3.0 2.2.2017 08:20: EASIER WAY to reproduce: 
-Open any project or Create new project 
-Add grid library 
-Add sticky note, move to grid library
-Add sticky note, move to grid library 
- on all devices, where project is open, everything looks fine, but in DB problem is already here 
-Close project/Open project
-Grid library will be shown only with one sticky note 

OLD: Do the following: 
Open project, you see on grid library containing one sticky note. 
Add 2 sticky notes 
Delete 2nd sticky note
Move 1st sticky note into grid library
Close project 
Open Project the moved sticky note does not exist any more or is not shown anymore 

If you have the project open on another device you see all the sticky notes as ghost tiles, you can move, ink, save them but they are not shown on the device where you reopened the project. Then close on this device the project again and open it and then the tiles are here again. So I assume nothing is really deleted, system just don't know where to display the tiles ? 

We have project 3295 / lde5e which this first appeard 30.01.2017 10:30 - 11:05. Would be really great if get here the 2 stickies back which are not shown anymore.

**Comment by corradocavalli** [comment]
I identified what causes the issue but i need some server side support from @gsantopaolo to better understand what is the cause. Please don't use or modify this project.

**Comment by agorog** [comment]
Still same with 1.3.3.0 but only happens when dropping into grid library, with library I cannot reproduce

**Comment by agorog** [comment]
I found several ways to reproduce. Problems happens when you drop a tile into a library grid, which already has one tile in it.

**Comment by corradocavalli** [comment]
@agorog could you please test with the new release and if correct close the bug?

**Comment by gsantopaolo** [comment]
@agorog  we are going to close this in case of no answer

**Comment by agorog** [comment]
Close this issue with 1.3.6.0 but see issue #59 with some similar problem
