### ISSUE TITLE
Highlighting looks different before and after saving

### ISSUE THREAD

**Issue by tamarawasser** [IBVSoftware/CollaBoard-Feedback#90]
31th of January
around 2 pm
on a Surface Pro 4
Project Code: 3333
Project Key: y794f

Before saving
![image](https://cloud.githubusercontent.com/assets/25382402/22474125/5b7353e6-e7db-11e6-83c7-1a2f61fc9c01.png)

after saving
![image](https://cloud.githubusercontent.com/assets/25382402/22474154/6a342a0e-e7db-11e6-9646-ce3fe2a0de7e.png)

**Comment by corradocavalli** [comment]
This is unfortunately a known issue, we had to implement a (not perfect) workaround to circumvent an operative system issue. We hope to get some positive news with forthcoming release and go back with standard behavior.

On 31 Jan 2017, at 17:34, tamarawasser <notifications@github.com<mailto:notifications@github.com>> wrote:


31th of January
around 2 pm
on a Surface Pro 4
Project Code: 3333
Project Key: y794f

Before saving
[image]<https://cloud.githubusercontent.com/assets/25382402/22474125/5b7353e6-e7db-11e6-83c7-1a2f61fc9c01.png>

after saving
[image]<https://cloud.githubusercontent.com/assets/25382402/22474154/6a342a0e-e7db-11e6-9646-ce3fe2a0de7e.png>

-

**Comment by gsantopaolo** [comment]
this is related to #58 please feel free to reopen after #58 will be fixed
