### ISSUE TITLE
Add tiles into library / reopen wrong order 

### ISSUE THREAD

**Issue by agorog** [IBVSoftware/CollaBoard-Feedback#91]
Project Code: 3372
Project Key: l1o3o
ibv-collaboard:open?code=3372&key=l1o3o
Version 1.3.3.0 
Date 1.2.2017 08:15 
All Devices
Maybe similar to #59 

Add one library, move 3 sticky notes inked with 0,1,2. Add 0, then 1, then 2. Close project, reopen project
Library shows 2/0/1
![grafik](https://cloud.githubusercontent.com/assets/19590642/22498166/f4bba852-e856-11e6-9198-5afbb660e2ae.png)

**Comment by gsantopaolo** [comment]
this is now fixed! I'm going to close this, feel free to reopen if you will experience this issue
