### ISSUE TITLE
Lost Tile(s)

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#93]
1.Create Project
2. Add some sticky notes and images to a grid library, upload a pdf
3.Conenct over VPN to IBV network (No Internet Connection fro CollaBoard)
4.Project Closes
5.Disconnetc VPN to IBV
5.Load Project again 
-->All tiles except the ones in the grid library disappeard. 

Surface Pro 4
09:12 02.02.2016
1.3.5.0
Project Code: 3443
Project Key: g777j
ibv-collaboard:open?code=3443&key=g777j

I will try to reproduce and refine the sequence. May be you see my tiles somewhere...

**Comment by mtg1986** [comment]
Same Project I created some new tiles. Then I had the error that I could not ink  on the sticky note, when I enlarged it on the enlarged region. On the default region it was possible to ink. 

I closed the project and opened it again. The sticky notes were lost.

**Comment by corradocavalli** [comment]
Ink issue is a duplicate of bug #58 can you elaborate more how to reproduce the lost tile issue?

**Comment by gsantopaolo** [comment]
@mtg1986  4 days no action

**Comment by mtg1986** [comment]
was not able to reproduce.
