### ISSUE TITLE
Settings: Disable Voice commands

### ISSUE THREAD

**Issue by agorog** [IBVSoftware/CollaBoard-Feedback#94]
When I discuss in a meeting suddenly CollaBoard show a tile for example active users and at another time starts to talk. This is cool, but that what we want. It should possible to deactivate/activate voice commands, so CollaBoard is not listening to discussions and start to do things we do not expect.

**Comment by corradocavalli** [comment]
What about prefixing commands with 'Collaboard: add tile...'?

On 2 Feb 2017, at 09:24, agorog <notifications@github.com<mailto:notifications@github.com>> wrote:


When I discuss in a meeting suddenly CollaBoard show a tile for example active users and at another time starts to talk. This is cool, but that what we want. It should possible to deactivate/activate voice commands, so CollaBoard is not listening to discussions and start to do things we do not expect.

-

**Comment by mtg1986** [comment]
It is impossible to do a demo when the voice commands are activiated.

**Comment by agorog** [comment]
Fixed with 1.3.6.0
