### ISSUE TITLE
CollaBoard Screen Freeze

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#96]
Not possible to reproduce, I did not found a sequence. 

All other application are working, but CollaBoard screen is freezed. Need to restart the app to continue working. 

Surface Pro 4
02.02.2017 10:13
3449
vb317

![image](https://cloud.githubusercontent.com/assets/19570958/22543410/adef1924-e930-11e6-92af-95da250543f8.png)

**Comment by corradocavalli** [comment]
Closing since we can't do absolutely nothing with these info, please reopen it when you have a repro case.
