### ISSUE TITLE
Enhancement - Unregister

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#97]
For unregistering it might be an idea that you are asked with another pop-up if you really want to unregister. I accidently unregistered my version.

**Comment by corradocavalli** [comment]
Absolutely make sense.

On 2 Feb 2017, at 13:11, Michael G?r?g <notifications@github.com<mailto:notifications@github.com>> wrote:


For unregistering it might be an idea that you are asked with another pop-up if you really want to unregister. I accidently unregistered my version.

-

**Comment by corradocavalli** [comment]
Feature has been added into new release that we're going to publish today, please test it and confirm that's ok closing the bug.

**Comment by mtg1986** [comment]
working. Thanks
