### ISSUE TITLE
Double-Tap to enlarge font size

### ISSUE THREAD

**Issue by mtg1986** [IBVSoftware/CollaBoard-Feedback#98]
When I make a double tab, to enlarge the font size of text in a sticky note then zoom-out of the canvas happens, instead that the font gets bigger. 

It is possible to enlarge the font size but you need to be carful and not tapping to quick on the "enlarge font-size button".

**Comment by corradocavalli** [comment]
Double tap is the command we use to "zoom to fit" the canvas, when you're using a zoomed in canvas you probably double tap the canvas triggering the behavior you see. We need to figure out how to resolve this.

**Comment by gsantopaolo** [comment]
honestly, in a touch world double tap is the worst gesture you can think on

**Comment by corradocavalli** [comment]
What do you propose?

On 6 Feb 2017, at 19:48, Gian Paolo Santopaolo <notifications@github.com<mailto:notifications@github.com>> wrote:


honestly, in a touch world double tap is the worst gesture you can think on
